In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

In [ ]:
t1 = pd.read_csv('/content/bhopal_land_details1.csv')
t2 = pd.read_csv('/content/bhopal_land_details2.csv')
t3 = pd.read_csv('/content/bhopal_land_details3.csv')
t4 = pd.read_csv('/content/bhopal_land_details4.csv')
t5 = pd.read_csv('/content/bhopal_land_details5.csv')
t6 = pd.read_csv('/content/bhopal_land_details6.csv')
t7 = pd.read_csv('/content/bhopal_land_details7.csv')
t8 = pd.read_csv('/content/bhopal_land_details8.csv')
t9 = pd.read_csv('/content/bhopal_land_details9.csv')
t10 = pd.read_csv('/content/bhopal_land_details10.csv')
t11 = pd.read_csv('/content/bhopal_land_details11.csv')
t12 = pd.read_csv('/content/bhopal_land_details12.csv')
t13 = pd.read_csv('/content/bhopal_land_details13.csv')
t14 = pd.read_csv('/content/bhopal_land_details14.csv')

In [ ]:
t = pd.concat([t1,t2,t3,t4,t5,t6,t7,t8,t9,t10,t11,t12,t13,t14])
print('shape',t1.shape[0]+t2.shape[0]+t3.shape[0]+t4.shape[0]+t5.shape[0]+t6.shape[0]+t7.shape[0]+t8.shape[0]+t9.shape[0]+t10.shape[0]+t11.shape[0]+t12.shape[0]+t13.shape[0]+t14.shape[0])
print("t",t.shape)

shape 1158
t (1158, 22)

In [ ]:
t.to_csv('bhopal_merge_plot.csv',index=False)

# After cleaning in excel

In [ ]:
l1 = pd.read_csv('bhopal_merge_plot_l1_clean.csv')
l1.head()

,pname,society,price,price_per_sqft,total_area,area_sqm,area_type,possesion,description,Dimensions,Price,Address,Facing,No. of Open Sides,Overlooking,Possession,Boundary wall,Gated Society,Width of facing road,Authority approved,Floors Allowed For Construction,Corner Property
0,"Residential land / Plot in Phanda Kala, Bhopal","Phanda Kala, Bhopal",₹28.42 Lac,₹700 /sqft,"4,055 sqft",(377 sqm),Plot Area,Ready To Move,We have a farm land available for sale in phan...,Plot area 4055\n(376.72 sq.m.) \nsq.ft.,₹ 28.42 Lac\n@ 700 per sq.ft.,"Phanda Kala, Bhopal",East,2.0,Park/Garden,Immediate,NaN,Yes,NaN,NaN,NaN,NaN
1,"Residential land / Plot in Bypass Road, Bhopal","Bypass Road, Bhopal",₹37 Lac,"₹1,607 /sqft","2,301 sqft",(214 sqm),Plot Area,Ready To Move,Plot is in indore bhopal highway bakaniya all ...,Plot area 2301\n(213.77 sq.m.) \nsq.ft.,"₹ 37 Lac+ Govt Charges & Tax\n@ 1,607 per sq.f...","Bypass Road, Bhopal",West,1.0,NaN,Immediate,No,NaN,31.0 Feet,NaN,NaN,NaN
2,"Residential land / Plot in Kokta Bypass Road, ...","Kokta Bypass Road, Bhopal",₹44 Lac,₹706 /sqft,"6,230 sqft",(579 sqm),Plot Area,Ready To Move,East phasing Lake phasing On kokta transport b...,Plot area 6230\n(578.79 sq.m.)\nl x b : 102.00...,₹ 44 Lac+ Govt Charges & Tax\n@ 706 per sq.ft....,"Kokta Bypass Road, Bhopal",East,1.0,"Park/Garden,Others,Main Road,Club",NaN,NaN,Yes,NaN,Yes,NaN,NaN
3,"Residential land / Plot in Sehore Road, Bhopal","Sehore Road, Bhopal",₹57.49 Lac,₹699 /sqft,"8,225 sqft",(764 sqm),Plot Area,Under Construction,Anandam hill view residential diverted farmhou...,Plot area 8225\n(764.13 sq.m.) \nsq.ft.,₹ 57.49 Lac\n@ 699 per sq.ft. (Negotiable),"Sehore Road, Bhopal",NaN,1.0,"Pool,Park/Garden,Club,Main Road",By 2026,No,NaN,NaN,NaN,NaN,NaN
4,"Residential land / Plot in Airport Road, Bhopal",Airport City,₹71.84 Lac,"₹5,150 /sqft","1,395 sqft",(130 sqm),Plot Area,Ready To Move,"Covered campus, around 22 acres, east and lawn...",Plot area 1395\n(129.6 sq.m.)\nl x b : 53.55 f...,"₹ 71.84 Lac\n@ 5,150 per sq.ft. (All inclusive...","Airport City\nAirport Road, Bhopal",East,1.0,"Park/Garden,Club,Main Road",NaN,NaN,Yes,NaN,Yes,NaN,NaN

In [ ]:
# Info
l1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1080 entries, 0 to 1079
Data columns (total 22 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   pname                            1080 non-null   object
 1   society                          1080 non-null   object
 2   price                            1080 non-null   object
 3   price_per_sqft                   1079 non-null   object
 4   total_area                       1080 non-null   object
 5   area_sqm                         1080 non-null   object
 6   area_type                        1080 non-null   object
 7   possesion                        1080 non-null   object
 8   description                      1080 non-null   object
 9   Dimensions                       1079 non-null   object
 10  Price                            1079 non-null   object
 11  Address                          1079 non-null   object
 12  Facing                           703 non-null    object
 13  No. of Open Sides                921 non-null    float64
 14  Overlooking                      512 non-null    object
 15  Possession                       880 non-null    object
 16  Boundary wall                    527 non-null    object
 17  Gated Society                    364 non-null    object
 18  Width of facing road             57 non-null     object
 19  Authority approved               336 non-null    object
 20  Floors Allowed For Construction  240 non-null    object
 21  Corner Property                  157 non-null    object
dtypes: float64(1), object(21)
memory usage: 185.8+ KB

In [ ]:
# Null values percentage in each columns
l1.isnull().sum()/l1.shape[0]*100

pname                               0.000000
society                             0.000000
price                               0.000000
price_per_sqft                      0.092593
total_area                          0.000000
area_sqm                            0.000000
area_type                           0.000000
possesion                           0.000000
description                         0.000000
Dimensions                          0.092593
Price                               0.092593
Address                             0.092593
Facing                             34.907407
No. of Open Sides                  14.722222
Overlooking                        52.592593
Possession                         18.518519
Boundary wall                      51.203704
Gated Society                      66.296296
Width of facing road               94.722222
Authority approved                 68.888889
Floors Allowed For Construction    77.777778
Corner Property                    85.462963
dtype: float64

In [ ]:
# duplicate rows
print("Number of Duplicated Rows : ",l1.duplicated().sum())

Number of Duplicated Rows :  144

In [ ]:
l1.drop_duplicates(inplace=True)

In [ ]:
l1.head(2)

,pname,society,price,price_per_sqft,total_area,area_sqm,area_type,possesion,description,Dimensions,Price,Address,Facing,No. of Open Sides,Overlooking,Possession,Boundary wall,Gated Society,Width of facing road,Authority approved,Floors Allowed For Construction,Corner Property
0,"Residential land / Plot in Phanda Kala, Bhopal","Phanda Kala, Bhopal",₹28.42 Lac,₹700 /sqft,"4,055 sqft",(377 sqm),Plot Area,Ready To Move,We have a farm land available for sale in phan...,Plot area 4055\n(376.72 sq.m.) \nsq.ft.,₹ 28.42 Lac\n@ 700 per sq.ft.,"Phanda Kala, Bhopal",East,2.0,Park/Garden,Immediate,NaN,Yes,NaN,NaN,NaN,NaN
1,"Residential land / Plot in Bypass Road, Bhopal","Bypass Road, Bhopal",₹37 Lac,"₹1,607 /sqft","2,301 sqft",(214 sqm),Plot Area,Ready To Move,Plot is in indore bhopal highway bakaniya all ...,Plot area 2301\n(213.77 sq.m.) \nsq.ft.,"₹ 37 Lac+ Govt Charges & Tax\n@ 1,607 per sq.f...","Bypass Road, Bhopal",West,1.0,NaN,Immediate,No,NaN,31.0 Feet,NaN,NaN,NaN

In [ ]:
l1['pname'].value_counts().shape

(241,)

In [ ]:
l1['pname'].str.lower().str.split(" in ").str.get(1).value_counts().shape

(240,)

In [ ]:
temp1 = l1['pname'].str.lower().str.split(" in ").str.get(1)

In [ ]:
temp =  (
    temp1
    .str.replace(r",\s*bhopal$", "", regex=True)   # remove ending , bhopal
    .str.split(",")                               # split by commas
    .str[-1]                                      # take the last part
    .str.strip()                                  # remove extra spaces
)

temp.value_counts()

pname
kolar road                                       79
salaiya                                          39
awadhpuri                                        36
neelbad                                          32
misrod                                           32
bhauri                                           30
katara hills                                     29
bypass road                                      28
ratibad                                          24
hoshangabad road                                 24
phanda kala                                      22
bawadia kalan                                    18
airport road                                     17
sukhi sewania                                    17
karond chouraha                                  16
huzur                                            15
lambakheda                                       14
danish kunj                                      14
indus towne                                      13
vidisha road                                     13
mandideep                                        11
patel nagar                                      10
raisen road                                       9
bagli                                             9
phanda                                            9
gandhinagar                                       9
gulmohar colony                                   8
danish nagar                                      8
bhanpur                                           8
bagmugaliya                                       8
new central jail                                  8
arvind vihar                                      8
sikandrabad                                       8
karond                                            8
bhojpur road                                      7
amrawad khurd                                     7
parwaliya sadak                                   7
acharpura                                         7
malikhedi                                         6
thua kheda                                        6
e 7 arera colony                                  6
jatkhedi                                          6
chopra kalan                                      6
kolar                                             6
kokta bypass road                                 6
ayodhya nagar                                     6
hinotiya alam                                     6
bairagarh                                         6
raksha vihar                                      6
arera colony                                      5
mungalia kot                                      5
saket nagar                                       5
samardha                                          5
sant ashram nagar                                 5
ayodhya bypass                                    5
badwai                                            5
khejrabaramad                                     5
gopal nagar                                       5
bda colony                                        5
e 3 arera colony                                  5
sanjeev nagar                                     5
kohefiza                                          4
bairagarh chichali                                4
suraj nagar                                       4
rajharsh colony                                   4
data colony                                       4
sehore road                                       4
shri rameshwaram                                  4
rohit nagar                                       4
katara                                            4
semri kalan                                       4
chuna bhatti                                      4
bawadiya kalan                                    4
good shepherd colony                              3
barkheda nathu                                    3
gondermau                                         3
peoples campus                                    3
mandakini colony                                  3
barrai                                            3
priyanka nagar                                    3
peepalner                                         3
chandukhedi                                       3
b sector shahpura                                 3
rusalli                                           3
ratanpur                                          3
khajuri kalan                                     3
kalapani                                          3
e 2 arera colony                                  3
mendua                                            3
dehri kalan                                       3
taraisewaniya                                     3
navi bagh                                         3
golden city                                       3
mubarikpur                                        3
borda                                             2
l n sharma colony aero city                       2
aerocity i lakshmi nararain residential plots     2
kotwali                                           2
khajuri                                           2
sarvdharm                                         2
e 4 arera colony                                  2
nirmal estate                                     2
barkheda bonder                                   2
barkheda salam                                    2
bagarauda                                         2
rapadiya                                          2
bhadbhada                                         2
rasla khedi                                       2
bairagarh kalan                                   2
new market                                        2
morga                                             2
nehru nagar                                       2
industrial area                                   2
arhedi                                            2
kunjan nagar phase 1                              2
berasia                                           2
shamli                                            2
pipaliya jahirpeer                                2
laharpur                                          2
shiv city                                         2
semra                                             2
yashoda vihar colony                              2
gora gaon                                         2
kalyanpur                                         2
rajat bihar colony                                2
bangrasia                                         2
hoshangabad                                       2
nayapura                                          2
new choksey nagar                                 2
swami vivekanand colony katara                    2
shirdipuram                                       2
zone 2                                            2
sewaniya onkar                                    2
nalgonda bypass telangana not bhopal mp           1
shyampur                                          1
khajoori sadak                                    1
himanshu green colony                             1
near ayodhya nagar                                1
bagh umrao dulha                                  1
residential plot                                  1
khudaganj                                         1
sahara by pass                                    1
sahra by pass                                     1
e 6 arera colony                                  1
salliya tribhuvan vihar                           1
pipaliya gajju mandideep                          1
jahangirabad                                      1
gulabi nagar                                      1
12 no stop arera colony                           1
sarvadharam c sector                              1
old ashoka garden                                 1
umadham downtown                                  1
prem nagar colony                                 1
kotra sultanabad                                  1
taramandal deoria bypass road                     1
khedi                                             1
basant kunj                                       1
hoshangabad road phase 3 rohit nagar              1
tagore nagar                                      1
imliya                                            1
gulmohar g3                                       1
suvidh vihar colony                               1
sneh nagar                                        1
ashoka garden                                     1
bhel sangam colony                                1
gol khedi                                         1
chola                                             1
sankhedi                                          1
deep nagar                                        1
malviya nagar                                     1
nandni                                            1
ayodhya bypass bhopal                             1
sant asharam nagar phase 2                        1
padariya jat                                      1
ichhawar naka road sehore                         1
custom colony danish chouraha                     1
area pin 462038                                   1
piyor                                             1
sant asharam nagar phase 3                        1
shri ram colony                                   1
housing board colony                              1
sehore                                            1
adharshila                                        1
itwara                                            1
pipaliya berkhedi                                 1
jk road                                           1
govindpura                                        1
radha krishna colony                              1
maksi                                             1
chhawani adampur                                  1
laukhedi                                          1
sudama nagar                                      1
neelbadh                                          1
sarvadharam d sector                              1
badbada road..opposite whispering falm            1
krishna campus                                    1
berkhedi kalan                                    1
e 5 arera colony                                  1
kalpana nagar                                     1
lalghati                                          1
kalara                                            1
sector a shahpura                                 1
new tt nagar                                      1
narela                                            1
mahawadiya                                        1
adarsh nagar                                      1
goalkedi ratua ratanpur bhopal                    1
shahjahanabad                                     1
lalghati chouraha                                 1
eint khedi                                        1
ayodhya bypass rd                                 1
pipalia pende khan                                1
aakriti ecocity                                   1
chatrasal nagar                                   1
ruchi lifescape                                   1
bagsewaniya                                       1
isro colony                                       1
shymapalli colony                                 1
pragati nagar                                     1
punjabi bagh                                      1
nishat colony                                     1
surajpur                                          1
navri                                             1
arwaliya                                          1
barkhedi abdulla                                  1
raja bhoj airport area                            1
kailash nagar                                     1
amjhira                                           1
kunjan nagar                                      1
amrabad kolar                                     1
indra vihar colony                                1
transport nagar                                   1
janki nagar                                       1
dam kheda                                         1
kahna sayiya                                      1
sant hirdaram nagar                               1
indus city campus                                 1
Name: count, dtype: int64

In [ ]:
l1['colony'] = temp

In [ ]:
l1.head(5)

,pname,society,price,price_per_sqft,total_area,area_sqm,area_type,possesion,description,Dimensions,Price,Address,Facing,No. of Open Sides,Overlooking,Possession,Boundary wall,Gated Society,Width of facing road,Authority approved,Floors Allowed For Construction,Corner Property,colony
0,"Residential land / Plot in Phanda Kala, Bhopal","Phanda Kala, Bhopal",₹28.42 Lac,₹700 /sqft,"4,055 sqft",(377 sqm),Plot Area,Ready To Move,We have a farm land available for sale in phan...,Plot area 4055\n(376.72 sq.m.) \nsq.ft.,₹ 28.42 Lac\n@ 700 per sq.ft.,"Phanda Kala, Bhopal",East,2.0,Park/Garden,Immediate,NaN,Yes,NaN,NaN,NaN,NaN,phanda kala
1,"Residential land / Plot in Bypass Road, Bhopal","Bypass Road, Bhopal",₹37 Lac,"₹1,607 /sqft","2,301 sqft",(214 sqm),Plot Area,Ready To Move,Plot is in indore bhopal highway bakaniya all ...,Plot area 2301\n(213.77 sq.m.) \nsq.ft.,"₹ 37 Lac+ Govt Charges & Tax\n@ 1,607 per sq.f...","Bypass Road, Bhopal",West,1.0,NaN,Immediate,No,NaN,31.0 Feet,NaN,NaN,NaN,bypass road
2,"Residential land / Plot in Kokta Bypass Road, ...","Kokta Bypass Road, Bhopal",₹44 Lac,₹706 /sqft,"6,230 sqft",(579 sqm),Plot Area,Ready To Move,East phasing Lake phasing On kokta transport b...,Plot area 6230\n(578.79 sq.m.)\nl x b : 102.00...,₹ 44 Lac+ Govt Charges & Tax\n@ 706 per sq.ft....,"Kokta Bypass Road, Bhopal",East,1.0,"Park/Garden,Others,Main Road,Club",NaN,NaN,Yes,NaN,Yes,NaN,NaN,kokta bypass road
3,"Residential land / Plot in Sehore Road, Bhopal","Sehore Road, Bhopal",₹57.49 Lac,₹699 /sqft,"8,225 sqft",(764 sqm),Plot Area,Under Construction,Anandam hill view residential diverted farmhou...,Plot area 8225\n(764.13 sq.m.) \nsq.ft.,₹ 57.49 Lac\n@ 699 per sq.ft. (Negotiable),"Sehore Road, Bhopal",NaN,1.0,"Pool,Park/Garden,Club,Main Road",By 2026,No,NaN,NaN,NaN,NaN,NaN,sehore road
4,"Residential land / Plot in Airport Road, Bhopal",Airport City,₹71.84 Lac,"₹5,150 /sqft","1,395 sqft",(130 sqm),Plot Area,Ready To Move,"Covered campus, around 22 acres, east and lawn...",Plot area 1395\n(129.6 sq.m.)\nl x b : 53.55 f...,"₹ 71.84 Lac\n@ 5,150 per sq.ft. (All inclusive...","Airport City\nAirport Road, Bhopal",East,1.0,"Park/Garden,Club,Main Road",NaN,NaN,Yes,NaN,Yes,NaN,NaN,airport road

In [ ]:
# Price column
l1 = l1[l1['price']!='Price on Request']
l1['price'].value_counts()

price
₹20 Lac       24
₹45 Lac       21
₹30 Lac       21
₹10 Lac       20
₹40 Lac       19
₹55 Lac       17
₹12 Lac       17
₹7 Lac        16
₹36 Lac       15
₹50 Lac       15
₹25 Lac       14
₹35 Lac       14
₹15 Lac       14
₹75 Lac       13
₹90 Lac       13
₹70 Lac       12
₹80 Lac       12
₹16 Lac       12
₹1.5 Cr       12
₹18 Lac       11
₹60 Lac       11
₹42 Lac       11
₹1.15 Cr      11
₹32 Lac       11
₹1.1 Cr       10
₹8 Lac        10
₹65 Lac        9
₹14 Lac        9
₹9 Lac         8
₹2.5 Cr        8
₹3 Cr          8
₹48 Lac        8
₹1.25 Cr       7
₹1.6 Cr        7
₹85 Lac        7
₹1 Cr          7
₹7.2 Lac       6
₹31.5 Lac      6
₹1.05 Cr       6
₹10.5 Lac      6
₹3.5 Cr        6
₹44 Lac        6
₹1.3 Cr        6
₹95 Lac        6
₹1.26 Cr       6
₹11 Lac        6
₹28 Lac        6
₹22 Lac        6
₹2.7 Cr        5
₹24 Lac        5
₹12.5 Lac      5
₹1.14 Cr       5
₹2 Cr          5
₹72 Lac        5
₹2.8 Cr        5
₹1.51 Cr       5
₹4 Cr          5
₹15 Cr         5
₹24.5 Lac      5
₹6 Cr          4
₹9.5 Lac       4
₹8.5 Lac       4
₹1.65 Cr       4
₹6 Lac         4
₹1.32 Cr       4
₹1.23 Cr       4
₹89 Lac        4
₹2.25 Cr       4
₹5 Cr          4
₹26 Lac        4
₹56 Lac        4
₹7.2 Cr        4
₹1.9 Cr        4
₹1.58 Cr       4
₹6.5 Lac       4
₹1.2 Cr        4
₹5.5 Cr        4
₹1.43 Cr       4
₹1.37 Cr       4
₹23 Lac        4
₹52.5 Lac      3
₹9.5 Cr        3
₹11 Cr         3
₹18.75 Lac     3
₹1.09 Cr       3
₹82.5 Lac      3
₹13.5 Lac      3
₹40.7 Lac      3
₹2.1 Cr        3
₹21 Lac        3
₹16.8 Lac      3
₹9.6 Lac       3
₹2.4 Cr        3
₹1.54 Cr       3
₹7.5 Lac       3
₹29 Lac        3
₹42.19 Lac     3
₹51 Lac        3
₹59.8 Lac      3
₹2.2 Cr        3
₹17 Lac        3
₹56.5 Lac      3
₹37.5 Lac      3
₹68 Lac        3
₹1.13 Cr       3
₹67.5 Lac      3
₹1.68 Cr       3
₹1.16 Cr       3
₹13 Lac        3
₹80.85 Lac     2
₹47.5 Lac      2
₹1.64 Cr       2
₹28.11 Lac     2
₹37 Lac        2
₹3.25 Cr       2
₹65.36 Lac     2
₹22 Cr         2
₹9 Cr          2
₹46 Lac        2
₹69 Lac        2
₹3.77 Cr       2
₹2.05 Cr       2
₹70.5 Lac      2
₹1.7 Cr        2
₹77 Lac        2
₹1.34 Cr       2
₹17.8 Lac      2
₹3.99 Cr       2
₹3.13 Cr       2
₹14.4 Lac      2
₹99.9 Lac      2
₹25 Cr         2
₹27.5 Lac      2
₹71.5 Lac      2
₹66 Lac        2
₹41 Lac        2
₹43.56 Lac     2
₹5 Lac         2
₹31 Lac        2
₹33 Lac        2
₹28.8 Lac      2
₹15.5 Lac      2
₹38.5 Lac      2
₹7 Cr          2
₹79.86 Lac     2
₹39 Lac        2
₹4.5 Cr        2
₹47 Lac        2
₹63 Lac        2
₹34.5 Lac      2
₹46.5 Lac      2
₹1.88 Cr       2
₹4.86 Cr       2
₹88 Lac        2
₹43 Lac        2
₹1.8 Cr        2
₹15.6 Lac      2
₹4 Lac         2
₹29.38 Lac     2
₹17.6 Lac      2
₹41.25 Lac     2
₹8.75 Lac      2
₹30.49 Lac     2
₹1.02 Cr       2
₹3.6 Cr        2
₹54.05 Lac     2
₹19 Lac        2
₹58 Lac        2
₹1.19 Cr       2
₹1.35 Cr       2
₹1.41 Cr       2
₹1.4 Cr        2
₹38 Lac        2
₹84 Lac        2
₹94 Lac        2
₹6.88 Lac      2
₹64 Lac        2
₹15.54 Lac     2
₹53.75 Lac     2
₹52 Lac        2
₹20.16 Cr      1
₹3.15 Cr       1
₹23.5 Lac      1
₹26.6 Lac      1
₹22.68 Lac     1
₹18.5 Lac      1
₹14 Cr         1
₹2.86 Cr       1
₹15.9 Lac      1
₹14.9 Lac      1
₹16.4 Lac      1
₹88.55 Lac     1
₹25.5 Cr       1
₹99.28 Lac     1
₹3.18 Cr       1
₹11.5 Lac      1
₹24.8 Lac      1
₹10.8 Lac      1
₹19.31 Lac     1
₹26.27 Lac     1
₹20.4 Lac      1
₹1.08 Cr       1
₹2.08 Cr       1
₹2.52 Cr       1
₹3.68 Cr       1
₹3.4 Cr        1
₹6.37 Cr       1
₹60.9 Lac      1
₹65.25 Lac     1
₹1.73 Cr       1
₹4.8 Cr        1
₹48.76 Lac     1
₹36.3 Lac      1
₹94.38 Lac     1
₹23.99 Lac     1
₹11.75 Lac     1
₹2.9 Cr        1
₹21.6 Lac      1
₹1.33 Cr       1
₹2.94 Cr       1
₹3.65 Cr       1
₹1.45 Cr       1
₹48.4 Lac      1
₹49.95 Lac     1
₹43.4 Lac      1
₹18.9 Lac      1
₹39.38 Lac     1
₹3.8 Cr        1
₹1.44 Cr       1
₹2.16 Cr       1
₹36.5 Lac      1
₹49 Lac        1
₹38.44 Lac     1
₹49.45 Lac     1
₹28.5 Lac      1
₹15.2 Lac      1
₹1.82 Cr       1
₹9.45 Cr       1
₹2.75 Cr       1
₹78 Lac        1
₹6.75 Cr       1
₹8 Cr          1
₹5.25 Cr       1
₹4.2 Cr        1
₹1.31 Cr       1
₹2.35 Cr       1
₹2.92 Cr       1
₹3.02 Cr       1
₹4.32 Cr       1
₹1.22 Cr       1
₹2.32 Cr       1
₹16.72 Lac     1
₹11.2 Lac      1
₹31.25 Lac     1
₹1.53 Cr       1
₹7.65 Cr       1
₹1.11 Cr       1
₹76.74 Lac     1
₹71.81 Lac     1
₹11.4 Lac      1
₹2.88 Cr       1
₹26.4 Lac      1
₹8.4 Lac       1
₹4.75 Cr       1
₹33.75 Lac     1
₹59 Lac        1
₹2.59 Cr       1
₹45.5 Lac      1
₹54.53 Lac     1
₹46.2 Lac      1
₹34 Lac        1
₹9.25 Cr       1
₹2.64 Cr       1
₹62.5 Lac      1
₹26.35 Lac     1
₹2.68 Cr       1
₹9.99 Lac      1
₹5.13 Cr       1
₹79.5 Lac      1
₹8.1 Lac       1
₹36.8 Lac      1
₹30.8 Lac      1
₹22.25 Lac     1
₹72.5 Lac      1
₹24.3 Lac      1
₹8.4 Cr        1
₹40.5 Lac      1
₹1.03 Cr       1
₹28 Cr         1
₹62 Lac        1
₹42.51 Lac     1
₹27.72 Lac     1
₹1.39 Cr       1
₹21.12 Lac     1
₹3 Lac         1
₹7.8 Lac       1
₹42.5 Lac      1
₹55.66 Lac     1
₹60.55 Lac     1
₹1.12 Cr       1
₹22.5 Cr       1
₹12 Cr         1
₹2.55 Cr       1
₹5.2 Cr        1
₹3.78 Cr       1
₹2.99 Cr       1
₹4.15 Cr       1
₹75.5 Lac      1
₹1.18 Cr       1
₹63.6 Lac      1
₹30.5 Lac      1
₹1.63 Cr       1
₹1.47 Cr       1
₹92 Lac        1
₹64.5 Lac      1
₹1.55 Cr       1
₹2.11 Cr       1
₹61 Lac        1
₹82 Lac        1
₹94.5 Lac      1
₹49.5 Lac      1
₹49.99 Lac     1
₹20.8 Lac      1
₹21.99 Lac     1
₹1.06 Cr       1
₹50.4 Lac      1
₹1.01 Cr       1
₹91.98 Lac     1
₹72.6 Lac      1
₹63.75 Lac     1
₹65.1 Lac      1
₹75.64 Lac     1
₹33.6 Lac      1
₹84.24 Lac     1
₹26.62 Lac     1
₹43.5 Lac      1
₹55.5 Lac      1
₹2.27 Cr       1
₹71.3 Lac      1
₹5.4 Cr        1
₹3.9 Cr        1
₹8.51 Lac      1
₹32.4 Lac      1
₹3.2 Cr        1
₹29.4 Lac      1
₹34.99 Lac     1
₹67 Lac        1
₹20 Cr         1
₹97.5 Lac      1
₹5.4 Lac       1
₹3.37 Cr       1
₹6.3 Lac       1
₹76.8 Lac      1
₹85.21 Lac     1
₹27 Lac        1
₹12.08 Lac     1
₹25.6 Lac      1
₹78.75 Lac     1
₹29.99 Lac     1
₹32.25 Lac     1
₹71.84 Lac     1
₹57.49 Lac     1
₹28.42 Lac     1
₹63.78 Lac     1
Name: count, dtype: int64

In [ ]:
l1 = l1[l1['price']!="₹7.2 - 45 Lac"]

In [ ]:

def convert_to_lakh(value):
    if pd.isna(value):
        return None

    # Remove rupee symbol and spaces
    value = value.replace("₹", "").strip()


    # Handle Crores
    if "Cr" in value:
        num = float(value.replace("Cr", "").strip())
        return num * 100  # convert Cr to Lakh

    # Handle Lakhs
    if "Lac" in value or "Lakh" in value:
        num = float(value.replace("Lac", "").replace("Lakh", "").strip())
        return num


# Apply conversion
l1['price'] = l1["price"].apply(convert_to_lakh)

In [ ]:
# price_per_sqrt
l1['price_per_sqft'].value_counts()

price_per_sqft
₹5,000 /sqft       27
₹6,000 /sqft       27
₹2,000 /sqft       26
₹1,000 /sqft       26
₹3,000 /sqft       23
₹1,200 /sqft       22
₹4,500 /sqft       21
₹2,500 /sqft       18
₹700 /sqft         17
₹5,500 /sqft       17
₹6,500 /sqft       15
₹1,500 /sqft       15
₹4,000 /sqft       13
₹1,600 /sqft       11
₹3,500 /sqft       10
₹4,200 /sqft        9
₹2,800 /sqft        9
₹750 /sqft          9
₹1,400 /sqft        7
₹400 /sqft          7
₹18,000 /sqft       7
₹2,600 /sqft        7
₹2,200 /sqft        7
₹7,000 /sqft        7
₹900 /sqft          7
₹3,200 /sqft        7
₹1,300 /sqft        6
₹500 /sqft          6
₹2,100 /sqft        6
₹8,000 /sqft        6
₹1,250 /sqft        6
₹2,400 /sqft        6
₹5,200 /sqft        5
₹5,333 /sqft        5
₹1,100 /sqft        5
₹7,500 /sqft        5
₹4,600 /sqft        5
₹459 /sqft          4
₹3,750 /sqft        4
₹4,166 /sqft        4
₹1,333 /sqft        4
₹3,700 /sqft        4
₹3,600 /sqft        4
₹850 /sqft          4
₹1,166 /sqft        4
₹5,800 /sqft        4
₹4,300 /sqft        4
₹1,900 /sqft        4
₹4,700 /sqft        4
₹6,200 /sqft        3
₹840 /sqft          3
₹1,850 /sqft        3
₹5,440 /sqft        3
₹20,000 /sqft       3
₹10,500 /sqft       3
₹833 /sqft          3
₹1,750 /sqft        3
₹92 /sqft           3
₹1,666 /sqft        3
₹3,333 /sqft        3
₹2,700 /sqft        3
₹888 /sqft          3
₹3,800 /sqft        3
₹126 /sqft          3
₹6,190 /sqft        3
₹370 /sqft          3
₹146 /sqft          3
₹6,666 /sqft        3
₹7,916 /sqft        3
₹699 /sqft          3
₹3,300 /sqft        3
₹600 /sqft          3
₹2,857 /sqft        3
₹2,916 /sqft        2
₹1,087 /sqft        2
₹5,172 /sqft        2
₹625 /sqft          2
₹8,333 /sqft        2
₹3,928 /sqft        2
₹3,996 /sqft        2
₹1,818 /sqft        2
₹8,200 /sqft        2
₹3,888 /sqft        2
₹633 /sqft          2
₹5,378 /sqft        2
₹2,875 /sqft        2
₹1,444 /sqft        2
₹1,231 /sqft        2
₹4,520 /sqft        2
₹5,400 /sqft        2
₹626 /sqft          2
₹1,618 /sqft        2
₹2,455 /sqft        2
₹2,350 /sqft        2
₹1,515 /sqft        2
₹1,777 /sqft        2
₹1,571 /sqft        2
₹1,982 /sqft        2
₹1,269 /sqft        2
₹4,642 /sqft        2
₹3,620 /sqft        2
₹4,501 /sqft        2
₹1,143 /sqft        2
₹4,192 /sqft        2
₹1,950 /sqft        2
₹2,560 /sqft        2
₹1,125 /sqft        2
₹4,179 /sqft        2
₹54,347 /sqft       2
₹492 /sqft          2
₹2,753 /sqft        2
₹26,600 /sqft       2
₹1,065 /sqft        2
₹9,110 /sqft        2
₹3,636 /sqft        2
₹918 /sqft          2
₹3,100 /sqft        2
₹3,142 /sqft        2
₹2,065 /sqft        2
₹1,598 /sqft        2
₹767 /sqft          2
₹736 /sqft          2
₹1,894 /sqft        2
₹32,608 /sqft       2
₹884 /sqft          2
₹5,600 /sqft        2
₹2,538 /sqft        2
₹6,250 /sqft        2
₹2,909 /sqft        2
₹777 /sqft          2
₹1,993 /sqft        2
₹229 /sqft          2
₹904 /sqft          2
₹1,550 /sqft        2
₹39,285 /sqft       2
₹16,204 /sqft       2
₹2,880 /sqft        2
₹1,189 /sqft        2
₹1,800 /sqft        2
₹450 /sqft          2
₹714 /sqft          2
₹5,238 /sqft        2
₹225 /sqft          2
₹10,909 /sqft       2
₹2,066 /sqft        2
₹4,285 /sqft        2
₹2,666 /sqft        2
₹866 /sqft          2
₹7,407 /sqft        2
₹7,666 /sqft        2
₹250 /sqft          2
₹5,933 /sqft        2
₹344 /sqft          2
₹3,285 /sqft        2
₹7,700 /sqft        2
₹2,333 /sqft        2
₹4,958 /sqft        2
₹2,250 /sqft        2
₹19,000 /sqft       2
₹12,000 /sqft       2
₹6,157 /sqft        2
₹2,727 /sqft        2
₹12,500 /sqft       2
₹8,620 /sqft        2
₹11,000 /sqft       2
₹5,509 /sqft        2
₹1,350 /sqft        2
₹8,500 /sqft        2
₹3,826 /sqft        2
₹5,750 /sqft        2
₹1,779 /sqft        1
₹706 /sqft          1
₹5,150 /sqft        1
₹3,466 /sqft        1
₹4,350 /sqft        1
₹50,000 /sqft       1
₹1,158 /sqft        1
₹729 /sqft          1
₹285 /sqft          1
₹2,599 /sqft        1
₹2,197 /sqft        1
₹3,440 /sqft        1
₹1,467 /sqft        1
₹7,142 /sqft        1
₹1,786 /sqft        1
₹401 /sqft          1
₹724 /sqft          1
₹622 /sqft          1
₹901 /sqft          1
₹133 /sqft          1
₹1,625 /sqft        1
₹681 /sqft          1
₹385 /sqft          1
₹44 /sqft           1
₹2,054 /sqft        1
₹1,700 /sqft        1
₹4,612 /sqft        1
₹5,100 /sqft        1
₹1,175 /sqft        1
₹4,142 /sqft        1
₹5,578 /sqft        1
₹4,650 /sqft        1
₹7,533 /sqft        1
₹1,996 /sqft        1
₹6,644 /sqft        1
₹9,022 /sqft        1
₹9,791 /sqft        1
₹7,200 /sqft        1
₹9,000 /sqft        1
₹6,300 /sqft        1
₹15,012 /sqft       1
₹15,526 /sqft       1
₹2,708 /sqft        1
₹9,200 /sqft        1
₹5,475 /sqft        1
₹2,884 /sqft        1
₹7,608 /sqft        1
₹689 /sqft          1
₹804 /sqft          1
₹3,400 /sqft        1
₹17,857 /sqft       1
₹24,107 /sqft       1
₹5,952 /sqft        1
₹13,333 /sqft       1
₹13,176 /sqft       1
₹4,298 /sqft        1
₹4,583 /sqft        1
₹12,458 /sqft       1
₹6,333 /sqft        1
₹2,998 /sqft        1
₹6,780 /sqft        1
₹17,000 /sqft       1
₹6,802 /sqft        1
₹9,032 /sqft        1
₹13,518 /sqft       1
₹1,946 /sqft        1
₹2,291 /sqft        1
₹6,904 /sqft        1
₹5,593 /sqft        1
₹5,507 /sqft        1
₹999 /sqft          1
₹5,324 /sqft        1
₹6,545 /sqft        1
₹6,910 /sqft        1
₹5,806 /sqft        1
₹8,693 /sqft        1
₹6,095 /sqft        1
₹3,363 /sqft        1
₹627 /sqft          1
₹3,475 /sqft        1
₹48 /sqft           1
₹3,099 /sqft        1
₹731 /sqft          1
₹3,017 /sqft        1
₹3,539 /sqft        1
₹1,820 /sqft        1
₹5,652 /sqft        1
₹3,041 /sqft        1
₹5,568 /sqft        1
₹12,666 /sqft       1
₹1,08,696 /sqft     1
₹3,833 /sqft        1
₹2,525 /sqft        1
₹1,139 /sqft        1
₹2,305 /sqft        1
₹5,714 /sqft        1
₹4,416 /sqft        1
₹5,411 /sqft        1
₹13,666 /sqft       1
₹5,833 /sqft        1
₹7,190 /sqft        1
₹6,494 /sqft        1
₹2,203 /sqft        1
₹618 /sqft          1
₹12,096 /sqft       1
₹11,333 /sqft       1
₹666 /sqft          1
₹3,268 /sqft        1
₹2,222 /sqft        1
₹7,250 /sqft        1
₹12,533 /sqft       1
₹499 /sqft          1
₹4,545 /sqft        1
₹1,263 /sqft        1
₹1,650 /sqft        1
₹184 /sqft          1
₹19 /sqft           1
₹5,483 /sqft        1
₹17,142 /sqft       1
₹4,800 /sqft        1
₹3,295 /sqft        1
₹230 /sqft          1
₹3,968 /sqft        1
₹4,442 /sqft        1
₹1,470 /sqft        1
₹398 /sqft          1
₹2,083 /sqft        1
₹5,476 /sqft        1
₹1,080 /sqft        1
₹631 /sqft          1
₹3,443 /sqft        1
₹5,517 /sqft        1
₹2,307 /sqft        1
₹1,875 /sqft        1
₹1,951 /sqft        1
₹2,745 /sqft        1
₹5,174 /sqft        1
₹4,233 /sqft        1
₹21,739 /sqft       1
₹1,466 /sqft        1
₹811 /sqft          1
₹4,497 /sqft        1
₹556 /sqft          1
₹2,157 /sqft        1
₹73,333 /sqft       1
₹30,000 /sqft       1
₹420 /sqft          1
₹38 /sqft           1
₹1,384 /sqft        1
₹1,923 /sqft        1
₹979 /sqft          1
₹1,375 /sqft        1
₹2,061 /sqft        1
₹4,190 /sqft        1
₹69 /sqft           1
₹4,857 /sqft        1
₹1,553 /sqft        1
₹5,183 /sqft        1
₹6,153 /sqft        1
₹851 /sqft          1
₹15,000 /sqft       1
₹13,779 /sqft       1
₹15,238 /sqft       1
₹6,507 /sqft        1
₹10,625 /sqft       1
₹321 /sqft          1
₹3,007 /sqft        1
₹6,404 /sqft        1
₹1,010 /sqft        1
₹3,555 /sqft        1
₹2,582 /sqft        1
₹3,641 /sqft        1
₹4,333 /sqft        1
₹4,615 /sqft        1
₹333 /sqft          1
₹2,352 /sqft        1
₹7,333 /sqft        1
₹413 /sqft          1
₹12,346 /sqft       1
₹53 /sqft           1
₹467 /sqft          1
₹1,235 /sqft        1
₹4,014 /sqft        1
₹1,823 /sqft        1
₹8,503 /sqft        1
₹2,631 /sqft        1
₹7,652 /sqft        1
₹25,000 /sqft       1
₹3,243 /sqft        1
₹5,015 /sqft        1
₹1,889 /sqft        1
₹4,705 /sqft        1
₹940 /sqft          1
₹3,195 /sqft        1
₹3,581 /sqft        1
₹5,555 /sqft        1
₹8,178 /sqft        1
₹4,066 /sqft        1
₹1,510 /sqft        1
₹4,230 /sqft        1
₹7,187 /sqft        1
₹6,071 /sqft        1
₹3,754 /sqft        1
₹5,466 /sqft        1
₹3,225 /sqft        1
₹2,995 /sqft        1
₹8,666 /sqft        1
₹5,681 /sqft        1
₹7,413 /sqft        1
₹4,693 /sqft        1
₹2,221 /sqft        1
₹4,400 /sqft        1
₹2,735 /sqft        1
₹22,500 /sqft       1
₹2,590 /sqft        1
₹9,876 /sqft        1
₹488 /sqft          1
₹574 /sqft          1
₹404 /sqft          1
₹1,643 /sqft        1
₹5,190 /sqft        1
₹8,095 /sqft        1
₹3,913 /sqft        1
₹11,500 /sqft       1
₹5,589 /sqft        1
₹7,619 /sqft        1
₹5,720 /sqft        1
₹16,667 /sqft       1
₹1,219 /sqft        1
₹800 /sqft          1
₹4,218 /sqft        1
₹3,900 /sqft        1
₹801 /sqft          1
₹0 /sqft            1
₹77 /sqft           1
₹5,217 /sqft        1
₹3,562 /sqft        1
₹2,332 /sqft        1
₹1,222 /sqft        1
₹1,862 /sqft        1
₹5,765 /sqft        1
₹57 /sqft           1
₹25,882 /sqft       1
₹1,682 /sqft        1
₹1,562 /sqft        1
₹1,050 /sqft        1
₹1,568 /sqft        1
₹1,866 /sqft        1
₹3,437 /sqft        1
₹2,651 /sqft        1
₹3,004 /sqft        1
₹4,516 /sqft        1
₹3,125 /sqft        1
₹2,113 /sqft        1
₹2,439 /sqft        1
₹1,181 /sqft        1
₹3,571 /sqft        1
₹929 /sqft          1
₹1,987 /sqft        1
₹2,483 /sqft        1
₹3,813 /sqft        1
₹9,722 /sqft        1
₹1,583 /sqft        1
₹1,266 /sqft        1
₹976 /sqft          1
₹1,912 /sqft        1
₹6,993 /sqft        1
₹5,111 /sqft        1
₹1,461 /sqft        1
₹1,148 /sqft        1
₹4,123 /sqft        1
₹363 /sqft          1
₹16,666 /sqft       1
₹10,000 /sqft       1
₹3,564 /sqft        1
₹2,260 /sqft        1
₹705 /sqft          1
₹2,380 /sqft        1
₹4,973 /sqft        1
₹3,088 /sqft        1
₹2,039 /sqft        1
₹4,363 /sqft        1
₹4,062 /sqft        1
₹10,533 /sqft       1
₹113 /sqft          1
₹1,714 /sqft        1
₹2,654 /sqft        1
₹533 /sqft          1
₹6,875 /sqft        1
₹479 /sqft          1
₹1,206 /sqft        1
₹550 /sqft          1
₹1,041 /sqft        1
₹7,526 /sqft        1
₹7,150 /sqft        1
₹997 /sqft          1
₹1,277 /sqft        1
₹1,057 /sqft        1
₹387 /sqft          1
₹15,797 /sqft       1
₹1,187 /sqft        1
₹21,000 /sqft       1
₹4,636 /sqft        1
₹497 /sqft          1
₹3,666 /sqft        1
₹3,227 /sqft        1
₹613 /sqft          1
₹920 /sqft          1
₹5,864 /sqft        1
₹60 /sqft           1
₹270 /sqft          1
₹451 /sqft          1
₹2,626 /sqft        1
₹1,821 /sqft        1
₹3,501 /sqft        1
₹2,196 /sqft        1
₹15,500 /sqft       1
₹27,777 /sqft       1
₹7,100 /sqft        1
₹425 /sqft          1
₹9,500 /sqft        1
₹1,607 /sqft        1
₹3,525 /sqft        1
₹8,750 /sqft        1
₹2,822 /sqft        1
₹197 /sqft          1
₹4,476 /sqft        1
₹2,499 /sqft        1
₹2,777 /sqft        1
₹6,266 /sqft        1
₹504 /sqft          1
₹4,012 /sqft        1
Name: count, dtype: int64

In [ ]:
def clean_price_sqft(value):
    try:
        # remove ₹, commas, /sqft, spaces
        value = (
            value.replace("₹", "")
                 .replace("/sqft", "")
                 .replace(",", "")
                 .strip()
        )
        return float(value)
    except:
        return None

# Apply cleaning
l1["price_per_sqft"] = l1["price_per_sqft"].apply(clean_price_sqft)

In [ ]:
n = l1[l1['price_per_sqft']==0.0]
n

Empty DataFrame
Columns: [pname, society, price, price_per_sqft, total_area, area_sqm, area_type, possesion, description, Dimensions, Price, Address, Facing, No. of Open Sides, Overlooking, Possession, Boundary wall, Gated Society, Width of facing road, Authority approved, Floors Allowed For Construction, Corner Property, colony]
Index: []

In [ ]:
l1.drop(n.index,inplace=True)

In [ ]:
# total_area
l1['total_area'] = l1['total_area'].str.replace("sqft"," ").str.replace(",","").str.strip().astype('int')

In [ ]:
# area_sqm
l1['area_sqm'] = l1['area_sqm'].str.replace("(","").str.replace("sqm","").str.replace(")","").str.replace(",","").str.strip().astype('int')

In [ ]:
l1.head()

,pname,society,price,price_per_sqft,total_area,area_sqm,area_type,possesion,description,Dimensions,Price,Address,Facing,No. of Open Sides,Overlooking,Possession,Boundary wall,Gated Society,Width of facing road,Authority approved,Floors Allowed For Construction,Corner Property,colony
0,"Residential land / Plot in Phanda Kala, Bhopal","Phanda Kala, Bhopal",28.42,700.0,4055,377,Plot Area,Ready To Move,We have a farm land available for sale in phan...,Plot area 4055\n(376.72 sq.m.) \nsq.ft.,₹ 28.42 Lac\n@ 700 per sq.ft.,"Phanda Kala, Bhopal",East,2.0,Park/Garden,Immediate,NaN,Yes,NaN,NaN,NaN,NaN,phanda kala
1,"Residential land / Plot in Bypass Road, Bhopal","Bypass Road, Bhopal",37.00,1607.0,2301,214,Plot Area,Ready To Move,Plot is in indore bhopal highway bakaniya all ...,Plot area 2301\n(213.77 sq.m.) \nsq.ft.,"₹ 37 Lac+ Govt Charges & Tax\n@ 1,607 per sq.f...","Bypass Road, Bhopal",West,1.0,NaN,Immediate,No,NaN,31.0 Feet,NaN,NaN,NaN,bypass road
2,"Residential land / Plot in Kokta Bypass Road, ...","Kokta Bypass Road, Bhopal",44.00,706.0,6230,579,Plot Area,Ready To Move,East phasing Lake phasing On kokta transport b...,Plot area 6230\n(578.79 sq.m.)\nl x b : 102.00...,₹ 44 Lac+ Govt Charges & Tax\n@ 706 per sq.ft....,"Kokta Bypass Road, Bhopal",East,1.0,"Park/Garden,Others,Main Road,Club",NaN,NaN,Yes,NaN,Yes,NaN,NaN,kokta bypass road
3,"Residential land / Plot in Sehore Road, Bhopal","Sehore Road, Bhopal",57.49,699.0,8225,764,Plot Area,Under Construction,Anandam hill view residential diverted farmhou...,Plot area 8225\n(764.13 sq.m.) \nsq.ft.,₹ 57.49 Lac\n@ 699 per sq.ft. (Negotiable),"Sehore Road, Bhopal",NaN,1.0,"Pool,Park/Garden,Club,Main Road",By 2026,No,NaN,NaN,NaN,NaN,NaN,sehore road
4,"Residential land / Plot in Airport Road, Bhopal",Airport City,71.84,5150.0,1395,130,Plot Area,Ready To Move,"Covered campus, around 22 acres, east and lawn...",Plot area 1395\n(129.6 sq.m.)\nl x b : 53.55 f...,"₹ 71.84 Lac\n@ 5,150 per sq.ft. (All inclusive...","Airport City\nAirport Road, Bhopal",East,1.0,"Park/Garden,Club,Main Road",NaN,NaN,Yes,NaN,Yes,NaN,NaN,airport road

In [ ]:
# area_type
l1['area_type'].value_counts()

area_type
Plot Area    1077
Name: count, dtype: int64

In [ ]:
# possesion
l1['possesion'].value_counts()

possesion
Ready To Move         937
Under Construction    140
Name: count, dtype: int64

In [ ]:
# address
l1['Address'].value_counts()

Address
Kolar Road, Bhopal                                                                             31
Neelbad, Bhopal                                                                                29
Danish Hills View\nKolar Road, Bhopal                                                          27
BDA Sardar Vallab Bhai Patel Apsi Karar Yojna\nSalaiya, Bhopal                                 27
Bypass Road, Bhopal                                                                            25
, Bhopal                                                                                       25
Awadhpuri, Bhopal                                                                              23
Bhauri, Bhopal                                                                                 21
Ratibad, Bhopal                                                                                21
Sukhi Sewania, Bhopal                                                                          16
Misrod, Bhopal                                                                                 16
Katara Hills, Bhopal                                                                           15
Karond Chouraha, Bhopal                                                                        15
Hoshangabad Road, Bhopal                                                                       14
Danish Kunj, Bhopal                                                                            14
Lambakheda, Bhopal                                                                             13
Airport Road, Bhopal                                                                           12
Phanda Kala, Bhopal                                                                            12
BDA Aerocity Phase 1\nHuzur, Bhopal                                                             8
Raisen Road, Bhopal                                                                             8
Gulmohar Colony, Bhopal                                                                         8
Bawadia Kalan, Bhopal                                                                           8
Arvind Vihar, Bhopal                                                                            8
Sikandrabad, Bhopal                                                                             8
Sage Suncity\nKatara Hills, Bhopal                                                              7
Vidisha Road, Bhopal                                                                            7
Phanda, Bhopal                                                                                  7
Indus Towne, Bhopal                                                                             7
Mandideep, Bhopal                                                                               6
Karond, Bhopal                                                                                  6
Danish Nagar, Bhopal                                                                            6
Acharpura, Bhopal                                                                               6
Raksha Vihar, Bhopal                                                                            6
Globus Coral Woods\nMisrod, Bhopal                                                              6
Kolar, Bhopal                                                                                   6
Patel Nagar, Bhopal                                                                             6
Salaiya, Bhopal                                                                                 6
Malikhedi, Bhopal                                                                               6
Kokta Bypass Road, Bhopal                                                                       5
E 3 Arera Colony, Bhopal                                                                        5
E 7 Arera colony, Bhopal                                                                        5
Ishaan Grand Estate\nIndus Towne, Bhopal                                                        5
BDA Colony, Bhopal                                                                              5
Bhanpur, Bhopal                                                                                 5
Saket Nagar, Bhopal                                                                             5
Bhavishya Metro City Sector A\nMungalia Kot, Bhopal                                             5
CI Estate\nThua Kheda, Bhopal                                                                   5
Parwaliya Sadak, Bhopal                                                                         5
Bagmugaliya, Bhopal                                                                             5
Hinotiya Alam, Bhopal                                                                           4
BDA Raja Bhoj Awasiy Yojna\nGandhinagar, Bhopal                                                 4
Bagli, Bhopal                                                                                   4
Sant Ashram Nagar, Bhopal                                                                       4
Chopra Kalan, Bhopal                                                                            4
Bairagarh Chichali, Bhopal                                                                      4
Data Colony, Bhopal                                                                             4
Chuna Bhatti, Bhopal                                                                            4
Amrawad Khurd, Bhopal                                                                           4
Sehore Road, Bhopal                                                                             4
Bhojpur Road, Bhopal                                                                            4
Amaltas Golden Mile\nPhanda Kala, Bhopal                                                        4
Sanjeev Nagar, Bhopal                                                                           4
Katara, Bhopal                                                                                  4
Kohefiza, Bhopal                                                                                4
Khejrabaramad, Bhopal                                                                           4
Jatkhedi, Bhopal                                                                                4
Rajharsh Colony, Bhopal                                                                         4
Semri Kalan, Bhopal                                                                             4
Shri Rameshwaram, Bhopal                                                                        3
Ayodhya Bypass , Bhopal                                                                         3
Mandakini Colony, Bhopal                                                                        3
E 2 Arera Colony, Bhopal                                                                        3
Crystal Smart City\nBawadia Kalan, Bhopal                                                       3
Gopal Nagar, Bhopal                                                                             3
Fortune Blue Ridge\nKolar Road, Bhopal                                                          3
Signature S Nine\nSamardha, Bhopal                                                              3
Suraj Nagar, Bhopal                                                                             3
Priyanka Nagar, Bhopal                                                                          3
Golden City, Bhopal                                                                             3
Narela Shankri, Ayodhya Nagar, Bhopal                                                           3
Ayodhya Nagar, Bhopal                                                                           3
Huzur, Bhopal                                                                                   3
Rohit Nagar, Bhopal                                                                             3
Mubarikpur, Bhopal                                                                              3
Arera Colony, Bhopal                                                                            3
Sanskriti City\nBadwai, Bhopal                                                                  3
B sector shahpura, Bhopal                                                                       3
Bima Kunj\nKolar Road, Bhopal                                                                   3
Barkheda Nathu, Bhopal                                                                          3
Chandukhedi, Bhopal                                                                             3
Taraisewaniya, Bhopal                                                                           3
Sid Saffron Valley\nMendua, Bhopal                                                              3
Good Shepherd Colony, Bhopal                                                                    3
Bhavishya Metro City\nVidisha Road, Bhopal                                                      3
Barrai, Bhopal                                                                                  3
Green Meadows\nBhojpur Road, Bhopal                                                             3
Gandhinagar, Bhopal                                                                             3
Ratanpur, Bhopal                                                                                3
Navi Bagh, Bhopal                                                                               3
Amritdhara Officers Town\nBhauri, Bhopal                                                        2
Shri Krishnapuram\nSamardha, Bhopal                                                             2
VDB Ghar Aangan\nMandideep, Bhopal                                                              2
Paras Midas\nBhauri, Bhopal                                                                     2
Airport City\nAirport Road, Bhopal                                                              2
Ultimate Garden City\nKolar Road, Bhopal                                                        2
People World\n, Bhopal                                                                          2
A30\nPatel Nagar, Bhopal                                                                        2
AG8 Aakriti Highlands\nPhanda Kala, Bhopal                                                      2
Shanti Nagar\nGondermau, Bhopal                                                                 2
Khajuri, Bhopal                                                                                 2
Chopra kala ,Vidisha road\nChopra Kalan, Bhopal                                                 2
Amaltas Golden Mile Phase 2\nPhanda Kala, Bhopal                                                2
Barkheda Bonder, Bhopal                                                                         2
Barkheda Salam, Bhopal                                                                          2
IBD Raisina\nPatel Nagar, Bhopal                                                                2
Bairagarh Kalan, Bhopal                                                                         2
L N Sharma colony aero city, Bhopal                                                             2
Bundelkhand Golden City\nJatkhedi, Bhopal                                                       2
Swarn Kunj Colony\nKatara Hills, Bhopal                                                         2
Borda, Bhopal                                                                                   2
Zone 2, Bhopal                                                                                  2
Bagarauda, Bhopal                                                                               2
awadhpuri, samanvay nagar\nAwadhpuri, Bhopal                                                    2
Himalaya Pride\nAwadhpuri, Bhopal                                                               2
Nehru Nagar , Bhopal                                                                            2
Rajat Bihar Colony, Bhopal                                                                      2
Kunjan nagar phase 1, Bhopal                                                                    2
JDN Kasturi Smart City\nBagli, Bhopal                                                           2
Morga, Bhopal                                                                                   2
indra nagari, gopal nagar\nGopal Nagar, Bhopal                                                  2
JAMUNIYA VILLAGE\nParwaliya Sadak, Bhopal                                                       2
Nirmal Estate, Bhopal                                                                           2
Arhedi, Bhopal                                                                                  2
Gora Gaon, Bhopal                                                                               2
People World\nBhanpur, Bhopal                                                                   2
Rasla Khedi, Bhopal                                                                             2
Kotwali, Bhopal                                                                                 2
Sewaniya Onkar, Bhopal                                                                          2
Shyamkunj\nRusalli, Bhopal                                                                      2
Agrawal Sagar Green Hills\nKolar Road, Bhopal                                                   2
Nakatia Bareilly, UP\nBypass Road, Bhopal                                                       2
Industrial Area, Bhopal                                                                         2
Aerocity I Lakshmi Nararain Residential Plots, Bhopal                                           2
Jai Shiv Om Green City\nBhauri, Bhopal                                                          2
Sarvdharm, Bhopal                                                                               2
New Choksey Nagar, Bhopal                                                                       2
Amaltas Gold Estate\nBagli, Bhopal                                                              2
Abhyudayam Janki Residency\nHinotiya Alam, Bhopal                                               2
Khajuri Kalan , Bhopal                                                                          2
Peepalner, Bhopal                                                                               2
Global Park City\nKatara Hills, Bhopal                                                          2
BDA Swami Vivekanand Parisar\nKatara Hills, Bhopal                                              2
Rapadiya, Bhopal                                                                                2
Bhadbhada, Bhopal                                                                               2
New Market, Bhopal                                                                              2
Bangrasia, Bhopal                                                                               2
Hoshangabad, Bhopal                                                                             2
E 4 Arera Colony, Bhopal                                                                        2
Aakriti Ecocity\nSalaiya, Bhopal                                                                2
Shirdipuram, Bhopal                                                                             2
Shree Signature The Address\nBawadia Kalan, Bhopal                                              2
Shiv City, Bhopal                                                                               2
Pipaliya Jahirpeer, Bhopal                                                                      2
Vaishno Saubhagya City\nVidisha Road, Bhopal                                                    2
Sage Nirvana Phase 1\nMisrod, Bhopal                                                            2
Mirakaar Eastern County\nHoshangabad Road, Bhopal                                               2
Haridwar Heights\nKarond, Bhopal                                                                2
Chinarr Nivaasaa\nAirport Road, Bhopal                                                          2
Semra, Bhopal                                                                                   2
Chirayu Hospital\nBairagarh, Bhopal                                                             2
Bairagarh, Bhopal                                                                               2
shamli, Bhopal                                                                                  2
Wazir Amravad Residency\nAmrawad Khurd, Bhopal                                                  2
BOMBAY PARADISE\n, Bhopal                                                                       2
42, Nirmal Kalpana Socity\nYashoda Vihar Colony, Bhopal                                         2
Laharpur, Bhopal                                                                                2
Dehri Kalan, Bhopal                                                                             2
Olive Enclave, Gondermau, Bhopal\nGondermau, Bhopal                                             1
Abhinav Homes Phase 4\nAyodhya Bypass , Bhopal                                                  1
Semanti Capital Greens\nHuzur, Bhopal                                                           1
Amjhira, Bhopal                                                                                 1
The C21 Mall\nMisrod, Bhopal                                                                    1
Kahna Sayiya, Bhopal                                                                            1
Peoples High Rise\nAyodhya Bypass , Bhopal                                                      1
Dhl\nPhanda Kala, Bhopal                                                                        1
Janki Nagar, Bhopal                                                                             1
Transport Nagar, Bhopal                                                                         1
Tilak Nagar Housing society\nIndra Vihar Colony, Bhopal                                         1
amrabad kolar, Bhopal                                                                           1
Kunjan Nagar, Bhopal                                                                            1
sahara by pass, Bhopal                                                                          1
sahra by pass, Bhopal                                                                           1
E 6 Arera Colony, Bhopal                                                                        1
Prabhatam Heights Plots\nRaisen Road, Bhopal                                                    1
Mayur vihar\nAshoka Garden, Bhopal                                                              1
Sahara Estates\nIndus Towne, Bhopal                                                             1
Meenakshi Planet City\nBagmugaliya, Bhopal                                                      1
BHEL Sangam Colony, Bhopal                                                                      1
Ishaan Vista\nKolar Road, Bhopal                                                                1
Sankhedi, Bhopal                                                                                1
awadhpuri ,bda road\nDeep Nagar, Bhopal                                                         1
ayodhya Bypass bhopal, Bhopal                                                                   1
Basant Kunj, Bhopal                                                                             1
Khedi, Bhopal                                                                                   1

In [ ]:
# facing
l1['Facing'].value_counts()

Facing
East          290
West          166
North          96
South          46
North-East     41
South-East     27
North-West     19
South-West     18
Name: count, dtype: int64

In [ ]:
# No.of Open Sides
l1['No. of Open Sides'].value_counts()

No. of Open Sides
1.0    564
2.0    248
3.0     55
4.0     54
Name: count, dtype: int64

In [ ]:
# overlooking
l1['Overlooking'].value_counts()

Overlooking
Main Road                                 121
Park/Garden                                96
Park/Garden,Main Road                      56
Main Road,Others                           28
Park/Garden,Main Road,Others               28
Others                                     21
Park/Garden,Club,Main Road                 15
Park/Garden,Club                           12
Main Road,Park/Garden                      12
Park/Garden,Others,Main Road               10
Pool,Park/Garden,Club,Main Road,Others      9
Park/Garden,Club,Main Road,Others           8
Pool,Others,Park/Garden,Club,Main Road      8
Others,Main Road                            8
Main Road,Park/Garden,Others                7
Park/Garden,Pool,Others,Club,Main Road      5
Pool,Park/Garden,Club,Main Road             4
Park/Garden,Main Road,Club                  3
Others,Main Road,Park/Garden                3
Club,Main Road,Park/Garden                  3
Club,Others                                 2
Park/Garden,Pool                            2
Pool,Park/Garden,Club                       2
Park/Garden,Club,Pool                       2
Main Road,Others,Park/Garden                2
Park/Garden,Club,Main Road,Pool             2
Park/Garden,Others                          2
Park/Garden,Main Road,Club,Others           2
Park/Garden,Pool,Main Road,Others,Club      2
Others,Pool                                 2
Club,Main Road,Park/Garden,Pool,Others      2
Club,Park/Garden,Main Road                  2
Main Road,Others,Club,Park/Garden           2
Park/Garden,Main Road,Others,Club           2
Park/Garden,Others,Main Road,Club           1
Park/Garden,Main Road,Club,Pool             1
Pool,Park/Garden,Others,Club,Main Road      1
Club,Park/Garden,Pool,Main Road,Others      1
Pool,Park/Garden,Main Road,Club             1
Park/Garden,Club,Pool,Main Road             1
Others,Club,Park/Garden                     1
Others,Park/Garden,Club,Main Road           1
Main Road,Pool                              1
Park/Garden,Club,Pool,Main Road,Others      1
Others,Park/Garden,Main Road,Club,Pool      1
Park/Garden,Main Road,Pool,Others,Club      1
Pool,Main Road,Park/Garden,Others,Club      1
Others,Pool,Park/Garden,Club,Main Road      1
Park/Garden,Club,Main Road,Pool,Others      1
Others,Park/Garden                          1
Pool,Club,Park/Garden,Main Road,Others      1
Park/Garden,Club,Others                     1
Club,Main Road,Others                       1
Club                                        1
Pool,Club,Main Road,Park/Garden             1
Pool,Main Road,Park/Garden,Others           1
Club,Park/Garden,Main Road,Others           1
Pool,Others,Main Road,Club,Park/Garden      1
Park/Garden,Club,Others,Main Road,Pool      1
Park/Garden,Pool,Club,Main Road,Others      1
Club,Park/Garden,Others,Main Road           1
Name: count, dtype: int64

In [ ]:

# Split values and create dummy columns
df_overlook = l1["Overlooking"].str.get_dummies(sep=",")

# Select only the required 5 columns (ensure consistent order)
cols = ["Club", "Main Road", "Others", "Park/Garden", "Pool"]
for col in cols:
    if col not in df_overlook.columns:
        df_overlook[col] = 0  # add missing columns

# Convert 0/1 → Yes/No
df_overlook = df_overlook[cols].replace({1: "Yes", 0: "No"})


# Merge back into original dataframe
l1 = pd.concat([l1, df_overlook], axis=1)

In [ ]:
# Boundary wall
l1['Boundary wall'].value_counts()

Boundary wall
No     355
Yes    170
Name: count, dtype: int64

In [ ]:
# Gated Society
l1['Gated Society'].value_counts()

Gated Society
Yes    364
Name: count, dtype: int64

In [ ]:
# Width of facing road
l1['Width of facing road'].value_counts()

Width of facing road
25.0 Feet     16
20.0 Feet     11
30.0 Feet      5
40.0 Feet      4
60.0 Feet      4
200.0 Feet     3
39.4 Feet      3
31.0 Feet      1
46.0 Feet      1
110.0 Feet     1
29.9 Feet      1
55.0 Feet      1
15.0 Feet      1
10.0 Feet      1
50.0 Feet      1
14.0 Feet      1
70.0 Feet      1
81.0 Feet      1
Name: count, dtype: int64

In [ ]:
# authority approved

l1["Authority approved"].value_counts()

Authority approved
Yes    336
Name: count, dtype: int64

In [ ]:
l1.head()

,pname,society,price,price_per_sqft,total_area,area_sqm,area_type,possesion,description,Dimensions,Price,Address,Facing,No. of Open Sides,Overlooking,Possession,Boundary wall,Gated Society,Width of facing road,Authority approved,Floors Allowed For Construction,Corner Property,colony,Club,Main Road,Others,Park/Garden,Pool
0,"Residential land / Plot in Phanda Kala, Bhopal","Phanda Kala, Bhopal",28.42,700.0,4055,377,Plot Area,Ready To Move,We have a farm land available for sale in phan...,Plot area 4055\n(376.72 sq.m.) \nsq.ft.,₹ 28.42 Lac\n@ 700 per sq.ft.,"Phanda Kala, Bhopal",East,2.0,Park/Garden,Immediate,NaN,Yes,NaN,NaN,NaN,NaN,phanda kala,No,No,No,Yes,No
1,"Residential land / Plot in Bypass Road, Bhopal","Bypass Road, Bhopal",37.00,1607.0,2301,214,Plot Area,Ready To Move,Plot is in indore bhopal highway bakaniya all ...,Plot area 2301\n(213.77 sq.m.) \nsq.ft.,"₹ 37 Lac+ Govt Charges & Tax\n@ 1,607 per sq.f...","Bypass Road, Bhopal",West,1.0,NaN,Immediate,No,NaN,31.0 Feet,NaN,NaN,NaN,bypass road,No,No,No,No,No
2,"Residential land / Plot in Kokta Bypass Road, ...","Kokta Bypass Road, Bhopal",44.00,706.0,6230,579,Plot Area,Ready To Move,East phasing Lake phasing On kokta transport b...,Plot area 6230\n(578.79 sq.m.)\nl x b : 102.00...,₹ 44 Lac+ Govt Charges & Tax\n@ 706 per sq.ft....,"Kokta Bypass Road, Bhopal",East,1.0,"Park/Garden,Others,Main Road,Club",NaN,NaN,Yes,NaN,Yes,NaN,NaN,kokta bypass road,Yes,Yes,Yes,Yes,No
3,"Residential land / Plot in Sehore Road, Bhopal","Sehore Road, Bhopal",57.49,699.0,8225,764,Plot Area,Under Construction,Anandam hill view residential diverted farmhou...,Plot area 8225\n(764.13 sq.m.) \nsq.ft.,₹ 57.49 Lac\n@ 699 per sq.ft. (Negotiable),"Sehore Road, Bhopal",NaN,1.0,"Pool,Park/Garden,Club,Main Road",By 2026,No,NaN,NaN,NaN,NaN,NaN,sehore road,Yes,Yes,No,Yes,Yes
4,"Residential land / Plot in Airport Road, Bhopal",Airport City,71.84,5150.0,1395,130,Plot Area,Ready To Move,"Covered campus, around 22 acres, east and lawn...",Plot area 1395\n(129.6 sq.m.)\nl x b : 53.55 f...,"₹ 71.84 Lac\n@ 5,150 per sq.ft. (All inclusive...","Airport City\nAirport Road, Bhopal",East,1.0,"Park/Garden,Club,Main Road",NaN,NaN,Yes,NaN,Yes,NaN,NaN,airport road,Yes,Yes,No,Yes,No

In [ ]:
# Floors Allowed For Construction
print("Non Null Values",l1['Floors Allowed For Construction'].value_counts().sum())
l1['Floors Allowed For Construction'].value_counts()

Non Null Values 240

Floors Allowed For Construction
3 Floors     97
2 Floors     69
0 Floors     30
4 Floors     24
1 Floors     14
30 Floors     2
5 Floors      2
25 Floors     1
6 Floors      1
Name: count, dtype: int64

In [ ]:
# corner property
l1['Corner Property'].value_counts()

Corner Property
Yes    157
Name: count, dtype: int64

In [ ]:
l1.head()

,pname,society,price,price_per_sqft,total_area,area_sqm,area_type,possesion,description,Dimensions,Price,Address,Facing,No. of Open Sides,Overlooking,Possession,Boundary wall,Gated Society,Width of facing road,Authority approved,Floors Allowed For Construction,Corner Property,colony,Club,Main Road,Others,Park/Garden,Pool
0,"Residential land / Plot in Phanda Kala, Bhopal","Phanda Kala, Bhopal",28.42,700.0,4055,377,Plot Area,Ready To Move,We have a farm land available for sale in phan...,Plot area 4055\n(376.72 sq.m.) \nsq.ft.,₹ 28.42 Lac\n@ 700 per sq.ft.,"Phanda Kala, Bhopal",East,2.0,Park/Garden,Immediate,NaN,Yes,NaN,NaN,NaN,NaN,phanda kala,No,No,No,Yes,No
1,"Residential land / Plot in Bypass Road, Bhopal","Bypass Road, Bhopal",37.00,1607.0,2301,214,Plot Area,Ready To Move,Plot is in indore bhopal highway bakaniya all ...,Plot area 2301\n(213.77 sq.m.) \nsq.ft.,"₹ 37 Lac+ Govt Charges & Tax\n@ 1,607 per sq.f...","Bypass Road, Bhopal",West,1.0,NaN,Immediate,No,NaN,31.0 Feet,NaN,NaN,NaN,bypass road,No,No,No,No,No
2,"Residential land / Plot in Kokta Bypass Road, ...","Kokta Bypass Road, Bhopal",44.00,706.0,6230,579,Plot Area,Ready To Move,East phasing Lake phasing On kokta transport b...,Plot area 6230\n(578.79 sq.m.)\nl x b : 102.00...,₹ 44 Lac+ Govt Charges & Tax\n@ 706 per sq.ft....,"Kokta Bypass Road, Bhopal",East,1.0,"Park/Garden,Others,Main Road,Club",NaN,NaN,Yes,NaN,Yes,NaN,NaN,kokta bypass road,Yes,Yes,Yes,Yes,No
3,"Residential land / Plot in Sehore Road, Bhopal","Sehore Road, Bhopal",57.49,699.0,8225,764,Plot Area,Under Construction,Anandam hill view residential diverted farmhou...,Plot area 8225\n(764.13 sq.m.) \nsq.ft.,₹ 57.49 Lac\n@ 699 per sq.ft. (Negotiable),"Sehore Road, Bhopal",NaN,1.0,"Pool,Park/Garden,Club,Main Road",By 2026,No,NaN,NaN,NaN,NaN,NaN,sehore road,Yes,Yes,No,Yes,Yes
4,"Residential land / Plot in Airport Road, Bhopal",Airport City,71.84,5150.0,1395,130,Plot Area,Ready To Move,"Covered campus, around 22 acres, east and lawn...",Plot area 1395\n(129.6 sq.m.)\nl x b : 53.55 f...,"₹ 71.84 Lac\n@ 5,150 per sq.ft. (All inclusive...","Airport City\nAirport Road, Bhopal",East,1.0,"Park/Garden,Club,Main Road",NaN,NaN,Yes,NaN,Yes,NaN,NaN,airport road,Yes,Yes,No,Yes,No

In [ ]:
l1.drop(columns=['pname','society','area_type','Dimensions','Price','Address','Overlooking'],inplace=True)

In [ ]:
l1.rename(columns={'price':'price(lakhs)','total_area':"area(sqft)","area_sqm":"area(sqm)","Facing":"facing"},inplace=True)

In [ ]:
cols = {}
for col in l1.columns:
  cols[col]=col.lower()
l1.rename(columns=cols,inplace=True)

In [ ]:
l1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1077 entries, 0 to 1079
Data columns (total 21 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   price(lakhs)                     1077 non-null   float64
 1   price_per_sqft                   1077 non-null   float64
 2   area(sqft)                       1077 non-null   int64
 3   area(sqm)                        1077 non-null   int64
 4   possesion                        1077 non-null   object
 5   description                      1077 non-null   object
 6   facing                           703 non-null    object
 7   no. of open sides                921 non-null    float64
 8   possession                       878 non-null    object
 9   boundary wall                    525 non-null    object
 10  gated society                    364 non-null    object
 11  width of facing road             57 non-null     object
 12  authority approved               336 non-null    object
 13  floors allowed for construction  240 non-null    object
 14  corner property                  157 non-null    object
 15  colony                           1077 non-null   object
 16  club                             1077 non-null   object
 17  main road                        1077 non-null   object
 18  others                           1077 non-null   object
 19  park/garden                      1077 non-null   object
 20  pool                             1077 non-null   object
dtypes: float64(3), int64(2), object(16)
memory usage: 185.1+ KB

In [ ]:
l1.drop(columns=['possession','width of facing road'],inplace=True)

# Missing Values Treatment

In [ ]:
l1['corner property'].fillna('unspecified',inplace=True)

/tmp/ipython-input-1531618107.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  l1['corner property'].fillna('unspecified',inplace=True)

In [ ]:
l1['floors allowed for construction'].fillna('unspecified',inplace=True)

/tmp/ipython-input-548314188.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  l1['floors allowed for construction'].fillna('unspecified',inplace=True)

In [ ]:
l1['authority approved'].fillna('unspecified',inplace=True)

/tmp/ipython-input-1025719256.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  l1['authority approved'].fillna('unspecified',inplace=True)

In [ ]:
l1['gated society'].fillna('unspecified',inplace=True)

/tmp/ipython-input-3986287464.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  l1['gated society'].fillna('unspecified',inplace=True)

In [ ]:
l1['boundary wall'].fillna('unspecified',inplace=True)

/tmp/ipython-input-493508549.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  l1['boundary wall'].fillna('unspecified',inplace=True)

In [ ]:
l1['no. of open sides'].fillna(l1['no. of open sides'].mode().values[0],inplace=True)

In [ ]:
l1['facing'].fillna('unspecified',inplace=True)

/tmp/ipython-input-1940904459.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  l1['facing'].fillna('unspecified',inplace=True)

In [ ]:
l1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1077 entries, 0 to 1079
Data columns (total 19 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   price(lakhs)                     1077 non-null   float64
 1   price_per_sqft                   1077 non-null   float64
 2   area(sqft)                       1077 non-null   int64
 3   area(sqm)                        1077 non-null   int64
 4   possesion                        1077 non-null   object
 5   description                      1077 non-null   object
 6   facing                           1077 non-null   object
 7   no. of open sides                1077 non-null   float64
 8   boundary wall                    1077 non-null   object
 9   gated society                    1077 non-null   object
 10  authority approved               1077 non-null   object
 11  floors allowed for construction  1077 non-null   object
 12  corner property                  1077 non-null   object
 13  colony                           1077 non-null   object
 14  club                             1077 non-null   object
 15  main road                        1077 non-null   object
 16  others                           1077 non-null   object
 17  park/garden                      1077 non-null   object
 18  pool                             1077 non-null   object
dtypes: float64(3), int64(2), object(14)
memory usage: 168.3+ KB

In [ ]:
l1.to_csv('bhopal_plot_l2_clean.csv')

In [2]:
df = pd.read_csv('bhopal_plot_l2_clean.csv')

In [5]:
df['colony'].unique().shape

(237,)