In [255]:
import pandas as pd 
import numpy as np 
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [256]:
t1 = pd.read_csv("bhopal_houses1.csv")
t2 = pd.read_csv("bhopal_houses2.csv")
t3 = pd.read_csv("bhopal_houses3.csv")
t4 = pd.read_csv("bhopal_houses4.csv")
t5 = pd.read_csv("bhopal_houses5.csv")
t6 = pd.read_csv("bhopal_houses6.csv")
t8 = pd.read_csv("bhopal_houses8.csv")
t9 = pd.read_csv("bhopal_houses9.csv")
t10 = pd.read_csv("bhopal_houses10.csv")
t11 = pd.read_csv("bhopal_houses11.csv")
t12 = pd.read_csv("bhopal_houses12.csv")
t13 = pd.read_csv("bhopal_houses13.csv")

In [257]:
t = pd.concat([t1,t2,t3,t4,t5,t6,t8,t9,t10,t11,t12,t13])
print('shape',t1.shape[0]+t2.shape[0]+t3.shape[0]+t4.shape[0]+t5.shape[0]+t6.shape[0]+t8.shape[0]+t9.shape[0]+t10.shape[0]+t11.shape[0]+t12.shape[0]+t13.shape[0])
print("t",t.shape)

shape 900
t (900, 18)

In [258]:
t.head()

,pname,society,price_outer,price_per_sqft,possesion,description,Area,Configuration,Price,Address,Total Floors,Facing,Property Age,furnishing,features,ratings,Overlooking,Possession in
0,"3 Bedroom House for sale in Kolar Road, Bhopal",Ultimate English Villa,₹60 Lac,"₹8,534 /sqft",Ready To Move,Na....................................,Plot area 703\n(65.31 sq.m.) \nsq.ft.,"3 Bedrooms , 3 Bathrooms, 1 Balcony","₹ 60 Lac+ Govt Charges & Tax\n@ 8,534 per sq.f...","Ultimate English Villa\nKolar Road, Bhopal",2 Floors,West,5 to 10 Year Old,"['2 Wardrobe', '1 Light', '1 Modular Kitchen',...","['Maintenance Staff', 'Water Storage', 'Park',...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]",NaN,NaN
1,"4 Bedroom House for sale in Lalghati, Bhopal",Globus Greens,₹2.25 Cr,"₹15,000 /sqft",Ready To Move,It's very spacious bunglow ..It's prime locati...,Plot area 1500\n(139.35 sq.m.)\nBuilt Up area:...,"4 Bedrooms , 3 Bathrooms, 1 Balcony with Pooja...","₹ 2.25 Crore\n@ 15,000 per sq.ft. (Negotiable)","Globus Greens\nLalghati, Bhopal",2 Floors,West,5 to 10 Year Old,"['4 Bed', '8 Wardrobe', '6 Fan', '1 Sofa', '1 ...","['Private Garden / Terrace', 'Park', 'Visitor ...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]","Park/Garden,Club",NaN
2,"6 Bedroom House for sale in Barkhera Pathani, ...",BASANT VIHAR COLONY,₹48 Lac,"₹2,400 /sqft",Ready To Move,As you can see in the photos the ground floor ...,Plot area 625\n(58.06 sq.m.)\nBuilt Up area: 2...,"6 Bedrooms , 2 Bathrooms, 2 Balconies","₹ 48 Lac\n@ 2,400 per sq.ft. (Negotiable)","BASANT VIHAR COLONY\nBarkhera Pathani, Bhopal",3 Floors,North,1 to 5 Year Old,[],"['Water Storage', 'Park']",[],Park/Garden,NaN
3,"9 Bedroom House for sale in Manak Vihar, Bhopal","Manak Vihar, Bhopal",₹1.5 Cr,"₹5,000 /sqft",Ready To Move,Ground floor bedrooms two with common washroom...,Plot area 3000\n(278.71 sq.m.) \nsq.ft.,"9 Bedrooms , 7 Bathrooms, 1 Balcony with Pooja...","₹ 1.5 Crore\n@ 5,000 per sq.ft. (All inclusive...","Manak Vihar, Bhopal",2 Floors,NaN,10+ Year Old,[],"['Private Garden / Terrace', 'High Ceiling Hei...",[],NaN,NaN
4,"5 Bedroom House for sale in Hoshangabad Road, ...","Hoshangabad Road, Bhopal",₹1.38 Cr,"₹3,484 /sqft",Ready To Move,"East facing bunglow ,prime location at narmada...",Plot area 2135\n(198.35 sq.m.)\nBuilt Up area:...,"5 Bedrooms , 4 Bathrooms, 3 Balconies with Poo...","₹ 1.38 Crore+ Govt Charges & Tax\n@ 3,484 per ...","Hoshangabad Road, Bhopal",2 Floors,East,1 to 5 Year Old,"['4 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]","Park/Garden,Main Road",NaN

In [259]:
t.to_excel('bhopal_merge_plot.xlsx',index=False)

In [260]:
t.shape

(900, 18)

In [261]:
t.info()

<class 'pandas.core.frame.DataFrame'>
Index: 900 entries, 0 to 74
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   pname           900 non-null    object
 1   society         900 non-null    object
 2   price_outer     900 non-null    object
 3   price_per_sqft  897 non-null    object
 4   possesion       900 non-null    object
 5   description     900 non-null    object
 6   Area            868 non-null    object
 7   Configuration   868 non-null    object
 8   Price           868 non-null    object
 9   Address         868 non-null    object
 10  Total Floors    834 non-null    object
 11  Facing          516 non-null    object
 12  Property Age    780 non-null    object
 13  furnishing      900 non-null    object
 14  features        900 non-null    object
 15  ratings         900 non-null    object
 16  Overlooking     402 non-null    object
 17  Possession in   88 non-null     object
dtypes: object(18)
memory usage: 133.6+ KB

In [262]:
# check for duplicates
t.duplicated().sum()

69

In [263]:
t = t.drop_duplicates()

In [264]:
t.shape

(831, 18)

In [265]:
t['furnishing'] = t['furnishing'].replace({"[]":np.nan})

In [266]:
t['features'] = t['features'].replace({"[]":np.nan})

In [267]:
# check for missing values
t.isnull().sum()

pname               0
society             0
price_outer         0
price_per_sqft      2
possesion           0
description         0
Area               31
Configuration      31
Price              31
Address            31
Total Floors       65
Facing            346
Property Age      115
furnishing        529
features          384
ratings             0
Overlooking       453
Possession in     747
dtype: int64

In [268]:
t[t.isnull().sum(axis=1)>10].shape

(31, 18)

In [269]:
t = t[t.isnull().sum(axis=1)<10]

In [270]:
t.shape

(800, 18)

# Society

In [271]:
t['society'].value_counts()

society
Awadhpuri, Bhopal                                   20
Kolar Road, Bhopal                                  13
Ayodhya Bypass , Bhopal                             10
Saket Nagar, Bhopal                                 10
Ayodhya Nagar, Bhopal                                9
Bagmugaliya, Bhopal                                  8
Bypass Road, Bhopal                                  8
Bawadia Kalan, Bhopal                                8
Hoshangabad Road, Bhopal                             8
Chuna Bhatti, Bhopal                                 7
Danish Kunj, Bhopal                                  7
Bairagarh, Bhopal                                    6
Neelbad, Bhopal                                      6
New Minal Residency, Bhopal                          6
Karond, Bhopal                                       6
Trilanga, Bhopal                                     5
Karond Chouraha, Bhopal                              5
Laharpur, Bhopal                                     5
Airport Road, Bhopal                                 5
Janki Nagar, Bhopal                                  5
Aakriti Aqua City                                    5
Rohit Nagar, Bhopal                                  5
Swadesh Red Square                                   5
Shakti Nagar, Bhopal                                 5
Lambakheda, Bhopal                                   4
Nariyalkheda, Bhopal                                 4
Ishaan Grand Estate                                  4
Salaiya, Bhopal                                      4
Crystal Ideal City                                   4
Amrit Bindras Pebble Bay                             4
Khajuri Kalan , Bhopal                               4
Fast Track Heavens Life                              4
Aishbagh, Bhopal                                     4
Ultimate English Villa                               4
IBD Raisina                                          4
E 7 Arera colony, Bhopal                             4
JD Kasturi Vihar                                     4
Idgah Hills, Bhopal                                  4
Sarvadharm Colony                                    4
Ashoka Garden, Bhopal                                4
Mahabali Nagar, Bhopal                               3
Sanjeev Nagar, Bhopal                                3
Globus Coral Casa                                    3
B sector shahpura, Bhopal                            3
Panchwati Colony, Bhopal                             3
Ramayan South Avenue                                 3
Windsor Palms                                        3
Sonagiri, Bhopal                                     3
Kolar, Bhopal                                        3
Jahangirabad, Bhopal                                 3
Mandideep, Bhopal                                    3
Gopal Nagar, Bhopal                                  3
Samardha, Bhopal                                     3
Chinarr 7th Mile                                     3
Sage Suncity                                         3
Ruchi Lifescape, Bhopal                              3
Agrawal Sagar Pearl Phase 1                          3
Danish Nagar, Bhopal                                 3
Lakherapura, Bhopal                                  3
Fortune Landmark                                     3
E 5 Arera colony, Bhopal                             3
Housing Board Colony                                 3
Shahpura, Bhopal                                     3
Karamveer Nagar, Bhopal                              3
Vardhman Green Park                                  3
Arera Colony, Bhopal                                 3
Rajat Bihar Colony, Bhopal                           3
Signature 360                                        3
Ratibad, Bhopal                                      3
Fortune Delight                                      3
Fortune Pride Extension                              3
Girnar Hills                                         3
Globus Coral Cottages                                3
Asnani Pebble Bay Phase 2                            3
Kalpana Nagar, Bhopal                                3
Lalita Nagar, Bhopal                                 3
Misrod, Bhopal                                       2
Lakshya Serene Wood                                  2
People World                                         2
chanchal nagar, sonagiri, bhopal                     2
Sage Milestone                                       2
BDA Colony, Bhopal                                   2
E 3 Arera Colony, Bhopal                             2
BDA Swami Vivekanand Parisar                         2
DK Devsthali                                         2
JDN Kasturi Smart City                               2
Sukhi Sewania, Bhopal                                2
Gautam Nagar, Bhopal                                 2
Katara, Bhopal                                       2
Katara Hills, Bhopal                                 2
Bagsewaniya, Bhopal                                  2
Fortune Estate                                       2
Aradhana Nagar, Bhopal                               2
Sahara States                                        2
Patel Nagar, Bhopal                                  2
Nirupam Royal Palms                                  2
Priyadarshini The Athenaeum                          2
Bhojpal Shri Radhakrishna Residency                  2
Rajved Colony, Bhopal                                2
Sector C Shahpura, Bhopal                            2
MP Nagar, Bhopal                                     2
Shri Rameshwaram, Bhopal                             2
Priyanka Nagar, Bhopal                               2
Agrawal Sagar Pearl                                  2
Rajharsh Colony, Bhopal                              2
Aakriti Eco City                                     2
Ishaan Vista                                         2
Chanakyapuri, Bhopal                                 2
Citi Vistaar                                         2
Narayan Nagar, Bhopal                                2
Tirupati Abhinav Homes                               2
Green Meados                                         2
Shri Balaji Galaxy City                              2
Hinotiya Alam, Bhopal                                2
Teela Jamalpura, Bhopal                              2
Draupadi Shivlok Phase 5                             2
Trebhuvan Vihar                                      2
Rachna Nagar, Bhopal                                 2
Raja Bhoj Airport Area, Bhopal                       2
Nehru Nagar , Bhopal                                 2
Flower City                                          2
Raj Minal Residency                                  2
Globus Greens                                        2
Bima Kunj                                            2
Shree Ganesh Lotus Park                              2
Maharishi Patanjali Parisar                          2
Karariya Sajidabad, Bhopal                           2
My City                                              2
Danish Hills View                                    2
krishna nagar street no 2                            2
Mayur Homes                                          2
Shankracharya Nagar, Bhopal                          2
Tilak Society, Bhopal                                2
Globus Fab City                                      2
bharat nagar, karam veer nagar                       1
C sector                                             1
Naveen nagar, Bhopal                                 1
indenpent house in a society                         1
Phase VI                                             1
Raj Sidharth Lake City                               1
Rai Pink City                                        1
sector -b,h no.4                                     1
Kohefiza, Bhopal                                     1
housing board                                        1
Bhavishya Metro City                                 1
Mahendra Greenwoods                                  1
Lala Lajpat Rai Society                              1
B Type Duplex                                        1
Adarsh Colony, Bhopal                                1
Radhe Krishna residency                              1
DLF Gardencity Phase II                              1
Deep shree homes awadhpuri                           1
Sid Saffron Valley                                   1
Sagar Avenue, Bhopal                                 1
shahpura                                             1
C Sector Shirdipuram, Bhopal                         1
Nikhil Banglow                                       1
Hoshanganad Road                                     1
kajibaag                                             1
Agrawal Sagar Premium Towers                         1
Ritu 11th Mile Garden City                           1
Macker Regalia                                       1
Gulmohar Colony, Bhopal                              1
ISRO Colony, Bhopal                                  1
ABDL Aashima Anupama City                            1
Minal Residency, Bhopal                              1
Fortune Glory Extension 2                            1
Berry Surendra Enclave                               1
Rohit nagar phase-2                                  1
Fortune Greenshire                                   1
Laxmi Nagar, Bhopal                                  1
9B Saket Nagar, Bhopal                               1
Manglam Group Gokul Residency                        1
Global Park City                                     1
kwality paradise                                     1
Sterling Castles                                     1
Vayu Royal Enclave 1                                 1
Essarjee Sampada                                     1
Shubhalay Pride                                      1
AG8 Aakriti Flamingo 3                               1
Kunjan nagar phase 1, Bhopal                         1
AG8 Aakriti Highlands                                1
1100 Quarters Arera Colony, Bhopal                   1
Sarvdharm, Bhopal                                    1
Sheetal Mega City Phase 1                            1
Aakriti Highlands Space                              1
Dilip Nandgaon                                       1
Peer Gate Area, Bhopal                               1
Fortune Soumya Heritage                              1
BHEL Nagar                                           1
Dwarkadheesh Gokuldham                               1
Sourabh Colony, Bhopal                               1
Hazrat Nizamuddin Colony, Bhopal                     1
Ravidas Nagar, Bhopal                                1
Punjabi Bagh, Bhopal                                 1
Bairagarh Chichali, Bhopal                           1
Gate Number 8 Shahpura                               1
MP Housing board                                     1
Sagar Royal Villas                                   1
Akbarpur, Bhopal                                     1
Singarcholi, Bhopal                                  1
Aakriti Garden Phase 4                               1
Bharat Nagar, Indrapuri, Bhopal                      1
Ganesh Colony                                        1
Ruchi Lifescapes                                     1
Khajoori Sadak, Bhopal                               1
Maa Parvati Nagar                                    1
ayodhya bypass rajeev nagar sector B                 1
Barkhedi, Bhopal                                     1
Chitrance Sai vihar                                  1
Congress Nagar, Bhopal                               1
Gandhinagar, Bhopal                                  1
Sajida Nagar, Bhopal                                 1
Nagarjun Nagar, Bhopal                               1
Bhopal Housing Board Society                         1
Malikhedi, Bhopal                                    1
Shahid Nagar Colony, Bhopal                          1
Bagh Umrao Dulha, Bhopal                             1
Aakriti Garden                                       1
Indra Vihar Colony, Bhopal                           1
Royal Estate                                         1
shanti nagar berkhera pathni                         1
nagar nigam colony                                   1
Akashganga Colony, Bhopal                            1
Sundar Nagar                                         1
Budhwara, Bhopal                                     1
Gehukheda, Coverd campus                             1
Lakhumal Nikhil Nestles                              1
Signature Residency                                  1
Harshavardhan Nagar, Bhopal                          1
New Minal Residency                                  1
Sahib Prithvi Courtyard                              1
Shymala Hills, Bhopal                                1
Regal Kasturi                                        1
Aerocity                                             1
Gomti Colony, Bhopal                                 1
Phanda Kala, Bhopal                                  1
Naya Pura, Kolar Road, Bhopal                        1
Vineet Kunj, Bhopal                                  1
Gauri Shankar Parisar                                1
Khajuri, Bhopal                                      1
Shri Parasnath Himanshu Greens                       1
Bhojpur Road, Bhopal                                 1
Rusalli, Bhopal                                      1
j k town kolar                                       1
Firdous Nagar, Bhopal                                1
Girdhar Heights                                      1
Radha Krishna Colony, Bhopal                         1
Regal Mohini Hones                                   1
Indus Regency                                        1
Gharonda Heights                                     1
Krishna Nagar, Bhopal                                1
Neori mandir road                                    1
rajved colony                                        1
Kamla Nagar, Bhopal                                  1
chatrasal nagar                                      1
BDA Colony Gondermau Airport Road Bhopal             1
Pushpa Vihar ayodhya baypass                         1
Meenakshi North Avenue                               1
F-Sector,Kolar Road, Bhopal                          1
Madhav Residency                                     1
Fine Avenue Phase 2, Bhopal                          1
The Bellaire Mint                                    1
Lala Lajpat Rai Colony, Bhopal                       1
Kamlesh Nagar, Bhopal                                1
Signature Business Park                              1
gurunanak pura independent house                     1
kwality paradise girdhar parasar                     1
bx sector rajharsh colony kolar road bhopal          1
New Green City                                       1
Regal Homes                                          1
Suraj Nagar, Bhopal                                  1
MPHIDB Sapphire Park City                            1
Rusia Nagar                                          1
Rohitas Nagar                                        1
bright colony idgah hills                            1
Vijay Nagar, Bhopal                                  1
Karond bye pass road, Bhopal                         1
Ganpati Enclave                                      1
raja bhoj International Airport                      1
Chitrance Sai Vihar                                  1
Green meadows                                        1
Sarla Paradise                                       1
Nayapura, Bhopal                                     1
individual house                                     1
IBD Hallmark Citii                                   1
Shirdipuram, Bhopal                                  1
Karod, Bhopal                                        1
Afkar colony, Bhopal                                 1
Mansa Builders Vaidyanath City                       1
26 janakpuri ayodhya by pass bhopal, Bhopal          1
Sunrise Colony                                       1
Indra Nagar, Bhopal                                  1
Amrawad Khurd, Bhopal                                1
Sneh Nagar, Bhopal                                   1
City Tower                                           1
Krishna Homes Rhythm Park                            1
Anupam Kasturi                                       1
Viswakarma Nagar, Bhopal                             1
Chhatrapati Nagar, Bhopal                            1
shri Aadinath Parisar                                1
Bhavishya Metro City Sector A                        1
LIG 105 KOTRA SULTANA BAD                            1
Priyadarshini Pristine                               1
Morga, Bhopal                                        1
Kadambini, Bhopal                                    1
Old Subhash Nagar Colony, Bhopal                     1
Sector C Indrapuri, Bhopal                           1
Bhopal                                               1
AKS Land Mark Sector A                               1
rajveer colony semara                                1
Habib Ganj, Bhopal                                   1
Sivoy, Bhopal                                        1
Jatkhedi, Bhopal                                     1
Airport Road                                         1
Gulmohar G3, Bhopal                                  1
Emerald Park City                                    1
Fortune Acharya Enclave                              1
Shri Balaji Swastik Grand                            1
Shree Signature The Address                          1
Aakriti Aquacity Mansarovar Cozi Bunglows            1
Tirupati Abhinav Homes Ayodhya Bypass                1
SONAGIRI, CHANCHAL NAGAR                             1
Geet Greens                                          1
LAMBAKHEDA BERASIA ROAD                              1
Prithvi Kilol Bungalows                              1
Sweet Home Residency                                 1
Sagar Royal Homes                                    1
Ankit parisar nayapura                               1
Khajurkalan                                          1
INDUS REGENCY                                        1
Sector B Indrapuri, Bhopal                           1
Independent Duplex House                             1
Bhanpur, Bhopal                                      1
Arwaliya, Bhopal                                     1
Talaiya, Bhopal                                      1
Elixir Gardens                                       1
HIG B 60 vidhya nagar bhopal                         1
Drishti Plaza                                        1
Amrit South Avenue                                   1
Neerja Nagar, Bhopal                                 1
Shangrila Housing Society                            1
Indrapuri, Bhopal                                    1
Manohar colony                                       1
Akash Nagar                                          1
jawahar nagar                                        1
Comfort Green, Airport Road                          1
Dwarka Nagar, Bhopal                                 1
Rasuliya Pathar, Bhopal                              1
eit khedi Bhopal                                     1
Housing Board Colony, Bhopal                         1
Bagh Dilkusha, Bhopal                                1
Manak Vihar, Bhopal                                  1
BASANT VIHAR COLONY                                  1
Chouksey Nagar, Bhopal                               1
Pushpa Nagar, Bhopal                                 1
Kalapani, Bhopal                                     1
Mamta Nagar                                          1
Sagar Estate                                         1
Peace Valley-1, Narela Shankari, Bhopal              1
Shankar Nagar, Bhopal                                1
Barrai, Bhopal                                       1
Rakhi Shankaracharya Flower City                     1

In [272]:
t['society'].value_counts().shape

(469,)

In [273]:
t['society'] = t['society'].str.strip().str.lower().str.replace(",","").str.replace('bhopal','').str.strip()

In [274]:
t['society'].value_counts().shape

(460,)

In [275]:
t = t[t['price_outer']!='Price on Request']

In [276]:
t['price_outer'].value_counts()

price_outer
₹75 Lac       28
₹65 Lac       28
₹1.5 Cr       27
₹1.25 Cr      23
₹55 Lac       23
₹40 Lac       20
₹80 Lac       19
₹85 Lac       19
₹1.2 Cr       19
₹35 Lac       18
₹1 Cr         18
₹2 Cr         18
₹70 Lac       17
₹1.1 Cr       16
₹45 Lac       16
₹60 Lac       16
₹25 Lac       16
₹95 Lac       16
₹1.35 Cr      15
₹1.3 Cr       14
₹90 Lac       12
₹50 Lac       11
₹2.25 Cr      10
₹2.5 Cr       10
₹3 Cr          9
₹1.8 Cr        9
₹30 Lac        8
₹3.25 Cr       8
₹1.4 Cr        7
₹2.1 Cr        7
₹1.15 Cr       7
₹1.75 Cr       7
₹1.6 Cr        7
₹22 Lac        6
₹1.45 Cr       6
₹48 Lac        6
₹1.05 Cr       6
₹20 Lac        6
₹42 Lac        6
₹38 Lac        5
₹18 Lac        5
₹1.55 Cr       5
₹3.5 Cr        5
₹62 Lac        5
₹49 Lac        4
₹1.7 Cr        4
₹58 Lac        4
₹82 Lac        4
₹29 Lac        4
₹15 Lac        4
₹92 Lac        4
₹2.6 Cr        4
₹63 Lac        4
₹2.7 Cr        4
₹27 Lac        4
₹5 Cr          4
₹47 Lac        4
₹2.15 Cr       3
₹28 Lac        3
₹6 Cr          3
₹3.75 Cr       3
₹56 Lac        3
₹26 Lac        3
₹2.3 Cr        3
₹72 Lac        3
₹86 Lac        3
₹52 Lac        3
₹2.9 Cr        3
₹3.2 Cr        3
₹4 Cr          3
₹59 Lac        3
₹24 Lac        3
₹61 Lac        3
₹32 Lac        3
₹5.5 Cr        3
₹2.95 Cr       3
₹68 Lac        3
₹2.2 Cr        3
₹99 Lac        2
₹33 Lac        2
₹1.69 Cr       2
₹12.5 Lac      2
₹1.65 Cr       2
₹5.15 Cr       2
₹7.5 Cr        2
₹16 Lac        2
₹23 Lac        2
₹1.38 Cr       2
₹2.07 Cr       2
₹78 Lac        2
₹2.85 Cr       2
₹1.96 Cr       2
₹1.9 Cr        2
₹2.75 Cr       2
₹2.26 Cr       2
₹2.8 Cr        2
₹11 Cr         1
₹27.99 Lac     1
₹73 Lac        1
₹71 Lac        1
₹12 Cr         1
₹84 Lac        1
₹39.5 Lac      1
₹36.9 Lac      1
₹92.8 Lac      1
₹1.37 Cr       1
₹26.6 Lac      1
₹66 Lac        1
₹10 Lac        1
₹36 Lac        1
₹55.1 Lac      1
₹24.5 Lac      1
₹98 Lac        1
₹73.95 Lac     1
₹7 Cr          1
₹10.4 Lac      1
₹6.25 Lac      1
₹77 Lac        1
₹7.95 Cr       1
₹46 Lac        1
₹13 Lac        1
₹1.52 Cr       1
₹39 Lac        1
₹22.5 Lac      1
₹1.08 Cr       1
₹4.2 Cr        1
₹87 Lac        1
₹1.49 Cr       1
₹64.06 Lac     1
₹96 Lac        1
₹15.5 Lac      1
₹1.28 Cr       1
₹1.27 Cr       1
₹69 Lac        1
₹36.1 Lac      1
₹31 Lac        1
₹3.6 Cr        1
₹1.43 Cr       1
₹54.9 Lac      1
₹8 Cr          1
₹2.55 Cr       1
₹3.65 Cr       1
₹8.6 Cr        1
₹1.29 Cr       1
₹2.61 Cr       1
₹15.5 Cr       1
₹100 Lac       1
₹1.02 Cr       1
₹81 Lac        1
₹2.51 Cr       1
₹89 Lac        1
₹56.5 Lac      1
₹29.11 Lac     1
₹4.5 Cr        1
₹76 Lac        1
₹79.5 Lac      1
₹1.85 Cr       1
₹67 Lac        1
₹5.6 Cr        1
₹22.9 Lac      1
₹2.31 Cr       1
₹4.56 Cr       1
₹2.11 Cr       1
₹4.32 Cr       1
₹5.45 Cr       1
₹37 Lac        1
₹53 Lac        1
₹3.7 Cr        1
₹76.99 Lac     1
₹12 Lac        1
₹2.09 Cr       1
₹8.5 Cr        1
₹2.02 Cr       1
₹6.7 Cr        1
₹6.24 Cr       1
₹2.35 Cr       1
₹2.65 Cr       1
₹2.4 Cr        1
₹3.15 Cr       1
₹56.9 Lac      1
₹34.9 Lac      1
₹6.5 Cr        1
₹17 Cr         1
₹9 Cr          1
₹19.9 Lac      1
Name: count, dtype: int64

In [277]:
def price_treatment(text):
    t = text.replace('₹',"").strip()
    if "Cr" in t:
        return float(t.replace("Cr","").strip())*100
    else:
        return float(t.replace("Lac","").strip())
        
        
t['price_outer'] = t['price_outer'].apply(price_treatment)

In [278]:
t.head()

,pname,society,price_outer,price_per_sqft,possesion,description,Area,Configuration,Price,Address,Total Floors,Facing,Property Age,furnishing,features,ratings,Overlooking,Possession in
0,"3 Bedroom House for sale in Kolar Road, Bhopal",ultimate english villa,60.0,"₹8,534 /sqft",Ready To Move,Na....................................,Plot area 703\n(65.31 sq.m.) \nsq.ft.,"3 Bedrooms , 3 Bathrooms, 1 Balcony","₹ 60 Lac+ Govt Charges & Tax\n@ 8,534 per sq.f...","Ultimate English Villa\nKolar Road, Bhopal",2 Floors,West,5 to 10 Year Old,"['2 Wardrobe', '1 Light', '1 Modular Kitchen',...","['Maintenance Staff', 'Water Storage', 'Park',...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]",NaN,NaN
1,"4 Bedroom House for sale in Lalghati, Bhopal",globus greens,225.0,"₹15,000 /sqft",Ready To Move,It's very spacious bunglow ..It's prime locati...,Plot area 1500\n(139.35 sq.m.)\nBuilt Up area:...,"4 Bedrooms , 3 Bathrooms, 1 Balcony with Pooja...","₹ 2.25 Crore\n@ 15,000 per sq.ft. (Negotiable)","Globus Greens\nLalghati, Bhopal",2 Floors,West,5 to 10 Year Old,"['4 Bed', '8 Wardrobe', '6 Fan', '1 Sofa', '1 ...","['Private Garden / Terrace', 'Park', 'Visitor ...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]","Park/Garden,Club",NaN
2,"6 Bedroom House for sale in Barkhera Pathani, ...",basant vihar colony,48.0,"₹2,400 /sqft",Ready To Move,As you can see in the photos the ground floor ...,Plot area 625\n(58.06 sq.m.)\nBuilt Up area: 2...,"6 Bedrooms , 2 Bathrooms, 2 Balconies","₹ 48 Lac\n@ 2,400 per sq.ft. (Negotiable)","BASANT VIHAR COLONY\nBarkhera Pathani, Bhopal",3 Floors,North,1 to 5 Year Old,NaN,"['Water Storage', 'Park']",[],Park/Garden,NaN
3,"9 Bedroom House for sale in Manak Vihar, Bhopal",manak vihar,150.0,"₹5,000 /sqft",Ready To Move,Ground floor bedrooms two with common washroom...,Plot area 3000\n(278.71 sq.m.) \nsq.ft.,"9 Bedrooms , 7 Bathrooms, 1 Balcony with Pooja...","₹ 1.5 Crore\n@ 5,000 per sq.ft. (All inclusive...","Manak Vihar, Bhopal",2 Floors,NaN,10+ Year Old,NaN,"['Private Garden / Terrace', 'High Ceiling Hei...",[],NaN,NaN
4,"5 Bedroom House for sale in Hoshangabad Road, ...",hoshangabad road,138.0,"₹3,484 /sqft",Ready To Move,"East facing bunglow ,prime location at narmada...",Plot area 2135\n(198.35 sq.m.)\nBuilt Up area:...,"5 Bedrooms , 4 Bathrooms, 3 Balconies with Poo...","₹ 1.38 Crore+ Govt Charges & Tax\n@ 3,484 per ...","Hoshangabad Road, Bhopal",2 Floors,East,1 to 5 Year Old,"['4 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]","Park/Garden,Main Road",NaN

# price_per_sqft

In [279]:
t['price_per_sqft'].value_counts()

price_per_sqft
₹10,000 /sqft      22
₹8,333 /sqft       13
₹6,666 /sqft       12
₹12,000 /sqft      12
₹7,500 /sqft       12
₹8,000 /sqft       10
₹5,000 /sqft       10
₹7,000 /sqft        8
₹6,000 /sqft        8
₹5,833 /sqft        7
₹12,500 /sqft       7
₹9,000 /sqft        6
₹16,666 /sqft       6
₹8,750 /sqft        6
₹10,416 /sqft       6
₹7,142 /sqft        5
₹3,333 /sqft        5
₹15,000 /sqft       5
₹5,500 /sqft        5
₹9,090 /sqft        5
₹6,500 /sqft        5
₹2,000 /sqft        5
₹2,500 /sqft        5
₹9,375 /sqft        5
₹6,250 /sqft        5
₹8,125 /sqft        5
₹5,625 /sqft        5
₹12,083 /sqft       5
₹4,000 /sqft        5
₹13,333 /sqft       5
₹6,818 /sqft        4
₹8,888 /sqft        4
₹5,555 /sqft        4
₹3,750 /sqft        4
₹6,333 /sqft        4
₹7,857 /sqft        4
₹10,666 /sqft       4
₹8,666 /sqft        4
₹5,333 /sqft        4
₹11,363 /sqft       4
₹4,166 /sqft        4
₹7,222 /sqft        4
₹9,166 /sqft        4
₹6,875 /sqft        4
₹12,222 /sqft       4
₹8,500 /sqft        3
₹5,250 /sqft        3
₹7,391 /sqft        3
₹4,666 /sqft        3
₹25,000 /sqft       3
₹11,666 /sqft       3
₹4,333 /sqft        3
₹11,250 /sqft       3
₹2,777 /sqft        3
₹7,666 /sqft        3
₹7,166 /sqft        3
₹10,833 /sqft       3
₹4,336 /sqft        2
₹11,500 /sqft       2
₹4,318 /sqft        2
₹9,523 /sqft        2
₹5,652 /sqft        2
₹4,122 /sqft        2
₹5,375 /sqft        2
₹7,200 /sqft        2
₹11,061 /sqft       2
₹9,829 /sqft        2
₹3,000 /sqft        2
₹4,687 /sqft        2
₹6,521 /sqft        2
₹6,153 /sqft        2
₹21,666 /sqft       2
₹4,454 /sqft        2
₹7,777 /sqft        2
₹6,266 /sqft        2
₹7,812 /sqft        2
₹4,583 /sqft        2
₹4,500 /sqft        2
₹3,611 /sqft        2
₹18,750 /sqft       2
₹11,739 /sqft       2
₹3,500 /sqft        2
₹13,500 /sqft       2
₹16,000 /sqft       2
₹3,125 /sqft        2
₹12,052 /sqft       2
₹9,642 /sqft        2
₹21,000 /sqft       2
₹8,003 /sqft        2
₹10,625 /sqft       2
₹5,666 /sqft        2
₹10,476 /sqft       2
₹8,789 /sqft        2
₹7,083 /sqft        2
₹4,545 /sqft        2
₹13,541 /sqft       2
₹9,047 /sqft        2
₹6,190 /sqft        2
₹7,750 /sqft        2
₹16,071 /sqft       2
₹9,259 /sqft        2
₹10,800 /sqft       2
₹6,111 /sqft        2
₹4,285 /sqft        2
₹7,111 /sqft        2
₹5,600 /sqft        2
₹5,925 /sqft        2
₹5,125 /sqft        2
₹7,894 /sqft        2
₹7,600 /sqft        2
₹8,571 /sqft        2
₹13,888 /sqft       2
₹9,500 /sqft        2
₹18,000 /sqft       2
₹7,727 /sqft        2
₹14,285 /sqft       2
₹4,090 /sqft        2
₹2,328 /sqft        2
₹7,619 /sqft        2
₹5,830 /sqft        1
₹4,347 /sqft        1
₹8,730 /sqft        1
₹8,562 /sqft        1
₹6,024 /sqft        1
₹6,986 /sqft        1
₹3,733 /sqft        1
₹8,463 /sqft        1
₹7,250 /sqft        1
₹8,264 /sqft        1
₹5,966 /sqft        1
₹14,510 /sqft       1
₹11,111 /sqft       1
₹4,363 /sqft        1
₹1,481 /sqft        1
₹3,222 /sqft        1
₹2,123 /sqft        1
₹3,428 /sqft        1
₹3,250 /sqft        1
₹520 /sqft          1
₹6,078 /sqft        1
₹6,538 /sqft        1
₹8,522 /sqft        1
₹13,513 /sqft       1
₹7,875 /sqft        1
₹4,017 /sqft        1
₹9,659 /sqft        1
₹5,641 /sqft        1
₹12,577 /sqft       1
₹7,395 /sqft        1
₹5,597 /sqft        1
₹22,563 /sqft       1
₹6,857 /sqft        1
₹12,416 /sqft       1
₹12,777 /sqft       1
₹11,428 /sqft       1
₹3,830 /sqft        1
₹7,195 /sqft        1
₹87,500 /sqft       1
₹6,944 /sqft        1
₹6,125 /sqft        1
₹8,943 /sqft        1
₹7,909 /sqft        1
₹7,333 /sqft        1
₹8,214 /sqft        1
₹17,758 /sqft       1
₹14,000 /sqft       1
₹7,428 /sqft        1
₹4,880 /sqft        1
₹20,560 /sqft       1
₹7,054 /sqft        1
₹2,222 /sqft        1
₹3,932 /sqft        1
₹3,281 /sqft        1
₹12,700 /sqft       1
₹5,466 /sqft        1
₹10,384 /sqft       1
₹1,533 /sqft        1
₹31,111 /sqft       1
₹4,421 /sqft        1
₹7,833 /sqft        1
₹5,271 /sqft        1
₹4,861 /sqft        1
₹8,534 /sqft        1
₹4,888 /sqft        1
₹36,363 /sqft       1
₹5,063 /sqft        1
₹7,029 /sqft        1
₹3,834 /sqft        1
₹6,632 /sqft        1
₹6,880 /sqft        1
₹2,151 /sqft        1
₹16,192 /sqft       1
₹10,714 /sqft       1
₹8,166 /sqft        1
₹21,176 /sqft       1
₹2,888 /sqft        1
₹7,934 /sqft        1
₹3,636 /sqft        1
₹3,623 /sqft        1
₹3,542 /sqft        1
₹3,421 /sqft        1
₹9,782 /sqft        1
₹17,000 /sqft       1
₹9,583 /sqft        1
₹3,525 /sqft        1
₹7,530 /sqft        1
₹3,800 /sqft        1
₹11,956 /sqft       1
₹12,396 /sqft       1
₹12,580 /sqft       1
₹10,133 /sqft       1
₹5,458 /sqft        1
₹3,471 /sqft        1
₹6,400 /sqft        1
₹6,879 /sqft        1
₹3,696 /sqft        1
₹11,718 /sqft       1
₹3,939 /sqft        1
₹2,142 /sqft        1
₹5,208 /sqft        1
₹3,200 /sqft        1
₹4,200 /sqft        1
₹4,518 /sqft        1
₹8,363 /sqft        1
₹15,463 /sqft       1
₹6,363 /sqft        1
₹11,261 /sqft       1
₹2,083 /sqft        1
₹23,333 /sqft       1
₹3,928 /sqft        1
₹3,692 /sqft        1
₹4,083 /sqft        1
₹6,590 /sqft        1
₹8,986 /sqft        1
₹7,986 /sqft        1
₹2,333 /sqft        1
₹10,417 /sqft       1
₹500 /sqft          1
₹4,949 /sqft        1
₹6,888 /sqft        1
₹7,375 /sqft        1
₹5,800 /sqft        1
₹1,714 /sqft        1
₹2,156 /sqft        1
₹5,166 /sqft        1
₹11,688 /sqft       1
₹9,565 /sqft        1
₹3,252 /sqft        1
₹26,666 /sqft       1
₹2,666 /sqft        1
₹2,111 /sqft        1
₹3,474 /sqft        1
₹6,382 /sqft        1
₹1,38,888 /sqft     1
₹1,388 /sqft        1
₹11,884 /sqft       1
₹7,281 /sqft        1
₹3,038 /sqft        1
₹4,264 /sqft        1
₹2,311 /sqft        1
₹7,700 /sqft        1
₹7,388 /sqft        1
₹3,968 /sqft        1
₹8,255 /sqft        1
₹4,750 /sqft        1
₹6,532 /sqft        1
₹12,413 /sqft       1
₹9,199 /sqft        1
₹5,909 /sqft        1
₹2,591 /sqft        1
₹5,078 /sqft        1
₹10,894 /sqft       1
₹5,617 /sqft        1
₹8,539 /sqft        1
₹8,402 /sqft        1
₹4,444 /sqft        1
₹4,210 /sqft        1
₹6,428 /sqft        1
₹4,828 /sqft        1
₹7,878 /sqft        1
₹2,976 /sqft        1
₹14,666 /sqft       1
₹13,043 /sqft       1
₹7,879 /sqft        1
₹9,950 /sqft        1
₹9,615 /sqft        1
₹10,526 /sqft       1
₹12,666 /sqft       1
₹7,462 /sqft        1
₹7,819 /sqft        1
₹3,790 /sqft        1
₹3,999 /sqft        1
₹6,881 /sqft        1
₹10,492 /sqft       1
₹10,769 /sqft       1
₹7,954 /sqft        1
₹9,417 /sqft        1
₹8,692 /sqft        1
₹5,834 /sqft        1
₹3,088 /sqft        1
₹5,405 /sqft        1
₹8,928 /sqft        1
₹7,730 /sqft        1
₹9,671 /sqft        1
₹19,047 /sqft       1
₹8,076 /sqft        1
₹6,157 /sqft        1
₹10,628 /sqft       1
₹5,164 /sqft        1
₹10,250 /sqft       1
₹3,676 /sqft        1
₹2,738 /sqft        1
₹6,856 /sqft        1
₹12,831 /sqft       1
₹3,947 /sqft        1
₹8,583 /sqft        1
₹9,606 /sqft        1
₹18,571 /sqft       1
₹6,388 /sqft        1
₹12,314 /sqft       1
₹15,476 /sqft       1
₹11,153 /sqft       1
₹17,400 /sqft       1
₹34,444 /sqft       1
₹23,809 /sqft       1
₹7,692 /sqft        1
₹5,900 /sqft        1
₹30,769 /sqft       1
₹12,400 /sqft       1
₹7,360 /sqft        1
₹17,005 /sqft       1
₹17,384 /sqft       1
₹19,417 /sqft       1
₹12,380 /sqft       1
₹9,178 /sqft        1
₹7,005 /sqft        1
₹10,434 /sqft       1
₹6,547 /sqft        1
₹3,234 /sqft        1
₹8,933 /sqft        1
₹3,856 /sqft        1
₹7,272 /sqft        1
₹14,583 /sqft       1
₹3,269 /sqft        1
₹8,866 /sqft        1
₹5,154 /sqft        1
₹7,319 /sqft        1
₹9,689 /sqft        1
₹15,267 /sqft       1
₹9,900 /sqft        1
₹2,962 /sqft        1
₹2,916 /sqft        1
₹2,600 /sqft        1
₹9,333 /sqft        1
₹13,526 /sqft       1
₹3,053 /sqft        1
₹8,228 /sqft        1
₹5,664 /sqft        1
₹3,484 /sqft        1
₹2,400 /sqft        1
₹6,224 /sqft        1
₹8,558 /sqft        1
₹4,634 /sqft        1
₹499 /sqft          1
₹16,304 /sqft       1
₹13,000 /sqft       1
₹13,169 /sqft       1
₹5,384 /sqft        1
₹11,875 /sqft       1
₹1,785 /sqft        1
₹26,250 /sqft       1
₹10,350 /sqft       1
₹11,474 /sqft       1
₹5,281 /sqft        1
₹7,935 /sqft        1
₹9,881 /sqft        1
₹7,829 /sqft        1
₹10,869 /sqft       1
₹18,272 /sqft       1
₹5,974 /sqft        1
₹4,542 /sqft        1
₹12,333 /sqft       1
₹3,267 /sqft        1
₹10,400 /sqft       1
₹10,562 /sqft       1
₹24,333 /sqft       1
₹60,000 /sqft       1
₹10,857 /sqft       1
₹5,450 /sqft        1
₹3,700 /sqft        1
₹22,500 /sqft       1
₹5,299 /sqft        1
₹6,100 /sqft        1
₹3,533 /sqft        1
₹13,703 /sqft       1
₹1,000 /sqft        1
₹10,454 /sqft       1
₹21,250 /sqft       1
₹10,333 /sqft       1
₹21,458 /sqft       1
₹7,013 /sqft        1
₹7,555 /sqft        1
₹18,400 /sqft       1
₹5,859 /sqft        1
₹10,294 /sqft       1
₹8,733 /sqft        1
₹19,230 /sqft       1
₹3,590 /sqft        1
₹7,435 /sqft        1
₹3,050 /sqft        1
₹4,761 /sqft        1
₹3,309 /sqft        1
₹3,378 /sqft        1
₹4,527 /sqft        1
₹9,428 /sqft        1
₹8,626 /sqft        1
₹8,673 /sqft        1
₹7,457 /sqft        1
₹4,800 /sqft        1
₹3,958 /sqft        1
₹2,583 /sqft        1
₹6,510 /sqft        1
₹2,909 /sqft        1
₹2,727 /sqft        1
₹5,370 /sqft        1
₹3,557 /sqft        1
₹3,472 /sqft        1
₹6,750 /sqft        1
₹7,751 /sqft        1
₹6,833 /sqft        1
₹7,614 /sqft        1
₹3,726 /sqft        1
₹5,314 /sqft        1
₹8,178 /sqft        1
₹4,064 /sqft        1
₹12,291 /sqft       1
₹5,816 /sqft        1
₹8,497 /sqft        1
₹16,250 /sqft       1
₹13,764 /sqft       1
₹40,476 /sqft       1
₹17,708 /sqft       1
₹26,000 /sqft       1
₹23,437 /sqft       1
₹15,625 /sqft       1
₹10,227 /sqft       1
₹24,000 /sqft       1
₹15,706 /sqft       1
₹9,240 /sqft        1
₹6,279 /sqft        1
₹7,434 /sqft        1
₹6,970 /sqft        1
₹9,347 /sqft        1
₹14,090 /sqft       1
₹14,134 /sqft       1
₹6,280 /sqft        1
₹16,326 /sqft       1
₹9,027 /sqft        1
₹7,070 /sqft        1
₹8,015 /sqft        1
₹9,540 /sqft        1
₹11,333 /sqft       1
₹16,750 /sqft       1
₹7,037 /sqft        1
₹8,641 /sqft        1
₹10,588 /sqft       1
₹13,636 /sqft       1
₹6,800 /sqft        1
₹11,000 /sqft       1
₹10,300 /sqft       1
₹15,714 /sqft       1
₹8,585 /sqft        1
₹15,666 /sqft       1
₹12,367 /sqft       1
₹15,151 /sqft       1
₹11,736 /sqft       1
₹84,000 /sqft       1
₹2,531 /sqft        1
Name: count, dtype: int64

In [280]:
t["price_per_sqft"] = t["price_per_sqft"].str.replace("₹","").str.replace(",","").str.replace("/sqft","").astype('int')

In [281]:
t.head()

,pname,society,price_outer,price_per_sqft,possesion,description,Area,Configuration,Price,Address,Total Floors,Facing,Property Age,furnishing,features,ratings,Overlooking,Possession in
0,"3 Bedroom House for sale in Kolar Road, Bhopal",ultimate english villa,60.0,8534,Ready To Move,Na....................................,Plot area 703\n(65.31 sq.m.) \nsq.ft.,"3 Bedrooms , 3 Bathrooms, 1 Balcony","₹ 60 Lac+ Govt Charges & Tax\n@ 8,534 per sq.f...","Ultimate English Villa\nKolar Road, Bhopal",2 Floors,West,5 to 10 Year Old,"['2 Wardrobe', '1 Light', '1 Modular Kitchen',...","['Maintenance Staff', 'Water Storage', 'Park',...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]",NaN,NaN
1,"4 Bedroom House for sale in Lalghati, Bhopal",globus greens,225.0,15000,Ready To Move,It's very spacious bunglow ..It's prime locati...,Plot area 1500\n(139.35 sq.m.)\nBuilt Up area:...,"4 Bedrooms , 3 Bathrooms, 1 Balcony with Pooja...","₹ 2.25 Crore\n@ 15,000 per sq.ft. (Negotiable)","Globus Greens\nLalghati, Bhopal",2 Floors,West,5 to 10 Year Old,"['4 Bed', '8 Wardrobe', '6 Fan', '1 Sofa', '1 ...","['Private Garden / Terrace', 'Park', 'Visitor ...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]","Park/Garden,Club",NaN
2,"6 Bedroom House for sale in Barkhera Pathani, ...",basant vihar colony,48.0,2400,Ready To Move,As you can see in the photos the ground floor ...,Plot area 625\n(58.06 sq.m.)\nBuilt Up area: 2...,"6 Bedrooms , 2 Bathrooms, 2 Balconies","₹ 48 Lac\n@ 2,400 per sq.ft. (Negotiable)","BASANT VIHAR COLONY\nBarkhera Pathani, Bhopal",3 Floors,North,1 to 5 Year Old,NaN,"['Water Storage', 'Park']",[],Park/Garden,NaN
3,"9 Bedroom House for sale in Manak Vihar, Bhopal",manak vihar,150.0,5000,Ready To Move,Ground floor bedrooms two with common washroom...,Plot area 3000\n(278.71 sq.m.) \nsq.ft.,"9 Bedrooms , 7 Bathrooms, 1 Balcony with Pooja...","₹ 1.5 Crore\n@ 5,000 per sq.ft. (All inclusive...","Manak Vihar, Bhopal",2 Floors,NaN,10+ Year Old,NaN,"['Private Garden / Terrace', 'High Ceiling Hei...",[],NaN,NaN
4,"5 Bedroom House for sale in Hoshangabad Road, ...",hoshangabad road,138.0,3484,Ready To Move,"East facing bunglow ,prime location at narmada...",Plot area 2135\n(198.35 sq.m.)\nBuilt Up area:...,"5 Bedrooms , 4 Bathrooms, 3 Balconies with Poo...","₹ 1.38 Crore+ Govt Charges & Tax\n@ 3,484 per ...","Hoshangabad Road, Bhopal",2 Floors,East,1 to 5 Year Old,"['4 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]","Park/Garden,Main Road",NaN

# Possesion

In [282]:
t['possesion'].value_counts()

possesion
Ready To Move         754
Under Construction     45
Name: count, dtype: int64

# Configuration

In [283]:
t['Configuration'].value_counts()

Configuration
3 Bedrooms , 3 Bathrooms, 1 Balcony                                                                          45
3 Bedrooms , 3 Bathrooms, 2 Balconies                                                                        42
3 Bedrooms , 2 Bathrooms, 1 Balcony                                                                          34
2 Bedrooms , 2 Bathrooms, 1 Balcony                                                                          33
4 Bedrooms , 4 Bathrooms, 2 Balconies                                                                        30
3 Bedrooms , 2 Bathrooms, 2 Balconies                                                                        21
3 Bedrooms , 2 Bathrooms, No Balcony                                                                         16
4 Bedrooms , 4 Bathrooms, 1 Balcony                                                                          15
2 Bedrooms , 1 Bathroom, No Balcony                                                                          13
4 Bedrooms , 3 Bathrooms, 2 Balconies                                                                        12
2 Bedrooms , 2 Bathrooms, No Balcony                                                                         12
4 Bedrooms , 3 Bathrooms, 1 Balcony                                                                          12
2 Bedrooms , 2 Bathrooms, 2 Balconies                                                                        10
3 Bedrooms , 3 Bathrooms, No Balcony                                                                         10
1 Bedroom , 1 Bathroom, 1 Balcony                                                                             8
4 Bedrooms , 2 Bathrooms, 2 Balconies                                                                         8
5 Bedrooms , 4 Bathrooms, 2 Balconies                                                                         8
1 Bedroom , 1 Bathroom, No Balcony                                                                            8
4 Bedrooms , 4 Bathrooms, 2 Balconies with Pooja Room                                                         8
5 Bedrooms , 4 Bathrooms, 1 Balcony                                                                           7
4 Bedrooms , 3 Bathrooms, No Balcony                                                                          7
4 Bedrooms , 2 Bathrooms, 1 Balcony                                                                           7
4 Bedrooms , 3 Bathrooms, 1 Balcony with Pooja Room                                                           6
3 Bedrooms , 3 Bathrooms, 1 Balcony with Pooja Room                                                           6
3 Bedrooms , 3 Bathrooms, 2 Balconies with Others                                                             5
4 Bedrooms , 4 Bathrooms, 3 Balconies                                                                         5
5 Bedrooms , 3 Bathrooms, 1 Balcony                                                                           5
3 Bedrooms , 3 Bathrooms, 3 Balconies                                                                         5
4 Bedrooms , 3 Bathrooms, 3 Balconies                                                                         5
3 Bedrooms , 4 Bathrooms, 1 Balcony                                                                           4
5 Bedrooms , 4 Bathrooms, 3 Balconies                                                                         4
4 Bedrooms , 2 Bathrooms, No Balcony                                                                          4
3 Bedrooms , 4 Bathrooms, 2 Balconies                                                                         4
3 Bedrooms , 3 Bathrooms, 1 Balcony with Pooja Room,Study Room                                                4
3 Bedrooms , 3 Bathrooms, 1 Balcony with Others                                                               4
2 Bedrooms , 1 Bathroom, 1 Balcony                                                                            4
5 Bedrooms , 5 Bathrooms, 3 Balconies                                                                         4
4 Bedrooms , 4 Bathrooms, No Balcony                                                                          4
4 Bedrooms , 4 Bathrooms, 3 Balconies with Study Room,Pooja Room,Others                                       3
3 Bedrooms , 2 Bathrooms, 1 Balcony with Pooja Room                                                           3
4 Bedrooms , 4 Bathrooms, 1 Balcony with Pooja Room                                                           3
3 Bedrooms , 3 Bathrooms, 2 Balconies with Pooja Room                                                         3
3 Bedrooms , 2 Bathrooms, 2 Balconies with Others                                                             3
5 Bedrooms , 3 Bathrooms, 1 Balcony with Others                                                               3
3 Bedrooms , 3 Bathrooms, 2 Balconies\nView Floor Plan                                                        3
2 Bedrooms , 2 Bathrooms, 1 Balcony with Pooja Room                                                           3
2 Bedrooms , 3 Bathrooms, No Balcony                                                                          3
3 Bedrooms , 3 Bathrooms, 2 Balconies with Pooja Room,Study Room                                              3
2 Bedrooms , 1 Bathroom, 2 Balconies                                                                          3
6 Bedrooms , 4 Bathrooms, No Balcony                                                                          3
5 Bedrooms , 3 Bathrooms, No Balcony                                                                          3
5 Bedrooms , 3 Bathrooms, 2 Balconies                                                                         3
3 Bedrooms , 2 Bathrooms, 1 Balcony with Others                                                               3
4 Bedrooms , 4 Bathrooms, 1 Balcony with Pooja Room,Study Room                                                3
5 Bedrooms , 5 Bathrooms, 2 Balconies with Pooja Room,Study Room,Servant Room,Store Room                      2
4 Bedrooms , 5 Bathrooms, 2 Balconies                                                                         2
4 Bedrooms , 3 Bathrooms, 3 Balconies with Pooja Room,Study Room                                              2
4 Bedrooms , 4 Bathrooms, 2 Balconies with Others                                                             2
5 Bedrooms , 5 Bathrooms, No Balcony                                                                          2
5 Bedrooms , 4 Bathrooms, No Balcony                                                                          2
4 Bedrooms , 3 Bathrooms, 2 Balconies with Pooja Room                                                         2
4 Bedrooms , 4 Bathrooms, 3 Balconies with Pooja Room,Study Room                                              2
3 Bedrooms , 3 Bathrooms, 3+ Balconies                                                                        2
7 Bedrooms , 6 Bathrooms, 2 Balconies                                                                         2
5 Bedrooms , 6 Bathrooms, 3 Balconies                                                                         2
4 Bedrooms , 4 Bathrooms, 1 Balcony with Pooja Room,Study Room,Servant Room,Store Room                        2
6 Bedrooms , 6 Bathrooms, 2 Balconies                                                                         2
3 Bedrooms , 2 Bathrooms, 2 Balconies with Pooja Room                                                         2
4 Bedrooms , 4 Bathrooms, 3 Balconies with Pooja Room,Study Room,Servant Room                                 2
4 Bedrooms , 3 Bathrooms, 2 Balconies with Pooja Room,Study Room,Others                                       2
4 Bedrooms , 4 Bathrooms, 3+ Balconies                                                                        2
7 Bedrooms , 7 Bathrooms, No Balcony                                                                          2
3 Bedrooms , 3 Bathrooms, 3 Balconies with Pooja Room,Study Room                                              2
2 Bedrooms , 2 Bathrooms, No Balcony with Others                                                              2
4 Bedrooms , 4 Bathrooms, 2 Balconies with Pooja Room,Store Room,Study Room,Servant Room                      2
6 Bedrooms , 6 Bathrooms, 2 Balconies with Pooja Room,Study Room,Servant Room,Store Room                      2
6 Bedrooms , 6 Bathrooms, 2 Balconies with Pooja Room,Store Room,Study Room,Servant Room\nView Floor Plan     2
3 Bedrooms , 3 Bathrooms, 1 Balcony with Study Room,Others                                                    2
4 Bedrooms , 4 Bathrooms, 2 Balconies with Study Room,Others                                                  2
4 Bedrooms , 3 Bathrooms, 2 Balconies with Study Room,Others                                                  2
4 Bedrooms , 4 Bathrooms, 2 Balconies with Pooja Room,Others                                                  2
4 Bedrooms , 3 Bathrooms, 2 Balconies with Study Room,Others,Servant Room                                     2
5 Bedrooms , 4 Bathrooms, 2 Balconies with Others                                                             2
3 Bedrooms , 1 Bathroom, No Balcony                                                                           2
4 Bedrooms , 5 Bathrooms, 2 Balconies with Pooja Room                                                         2
10 Bedrooms , 5 Bathrooms, 3 Balconies                                                                        2
4 Bedrooms , 3 Bathrooms, 2 Balconies with Study Room,Servant Room                                            2
4 Bedrooms , 3 Bathrooms, 2 Balconies with Others                                                             2
4 Bedrooms , 3 Bathrooms, 2 Balconies with Study Room                                                         2
3 Bedrooms , 4 Bathrooms, 1 Balcony with Pooja Room                                                           2
2 Bedrooms , 3 Bathrooms, 1 Balcony                                                                           2
4 Bedrooms , 2 Bathrooms, 2 Balconies with Others                                                             2
6 Bedrooms , 4 Bathrooms, 3 Balconies with Pooja Room                                                         2
4 Bedrooms , 3 Bathrooms, 2 Balconies with Pooja Room,Store Room                                              2
8 Bedrooms , 4 Bathrooms, 2 Balconies                                                                         2
6 Bedrooms , 5 Bathrooms, 2 Balconies                                                                         2
5 Bedrooms , 4 Bathrooms, 3 Balconies with Pooja Room,Study Room,Servant Room,Others                          2
4 Bedrooms , 4 Bathrooms, 1 Balcony with Others                                                               1
4 Bedrooms , 4 Bathrooms, 2 Balconies with Servant Room                                                       1
6 Bedrooms , 6 Bathrooms, 2 Balconies with Study Room,Pooja Room,Store Room,Servant Room\nView Floor Plan     1
4 Bedrooms , 4 Bathrooms, 3+ Balconies with Servant Room                                                      1
6 Bedrooms , 5 Bathrooms, 3+ Balconies with Servant Room,Pooja Room,Others                                    1
7 Bedrooms , 4 Bathrooms, 1 Balcony                                                                           1
3 Bedrooms , 3 Bathrooms, No Balcony with Others                                                              1
6 Bedrooms , 7 Bathrooms, 3+ Balconies with Pooja Room,Study Room,Servant Room,Others                         1
4 Bedrooms , 5 Bathrooms, No Balcony with Pooja Room,Store Room                                               1
6 Bedrooms , 5 Bathrooms, 3+ Balconies with Pooja Room,Study Room,Servant Room,Others                         1
2 Bedrooms , 2 Bathrooms, No Balcony with Pooja Room,Others                                                   1
2 Bedrooms , 1 Bathroom, 1 Balcony with Pooja Room,Study Room,Servant Room,Others                             1
10 Bedrooms , 5 Bathrooms, 2 Balconies                                                                        1
4 Bedrooms , 4 Bathrooms, 1 Balcony with Pooja Room,Study Room,Servant Room                                   1
4 Bedrooms , 1 Bathroom, No Balcony with Others                                                               1
8 Bedrooms , 6 Bathrooms, No Balcony                                                                          1
4 Bedrooms , 3 Bathrooms, 2 Balconies with Servant Room                                                       1
5 Bedrooms , 4 Bathrooms, 1 Balcony\nView Floor Plan                                                          1
5 Bedrooms , 4 Bathrooms, 3+ Balconies with Pooja Room,Study Room,Servant Room,Others                         1
5 Bedrooms , 6 Bathrooms, 3+ Balconies                                                                        1
6 Bedrooms , 4 Bathrooms, 2 Balconies                                                                         1
9 Bedrooms , 8 Bathrooms, 3 Balconies                                                                         1
5 Bedrooms , 4 Bathrooms, 2 Balconies with Study Room,Pooja Room,Others                                       1
5 Bedrooms , 3 Bathrooms, 1 Balcony with Pooja Room                                                           1
4 Bedrooms , 4 Bathrooms, 2 Balconies with Study Room,Pooja Room,Others                                       1
4 Bedrooms , 3 Bathrooms, 2 Balconies with Pooja Room,Study Room,Store Room                                   1
10 Bedrooms , 4 Bathrooms, 3 Balconies with Others                                                            1
4 Bedrooms , 5 Bathrooms, 3 Balconies with Pooja Room,Study Room,Others                                       1
5 Bedrooms , 7 Bathrooms, 3 Balconies                                                                         1
10 Bedrooms , 6 Bathrooms, 3+ Balconies                                                                       1
6 Bedrooms , 5 Bathrooms, 2 Balconies with Study Room                                                         1
6 Bedrooms , 6 Bathrooms, 1 Balcony                                                                           1
2 Bedrooms , 3 Bathrooms, 2 Balconies                                                                         1
5 Bedrooms , 5 Bathrooms, 2 Balconies with Others                                                             1
3 Bedrooms , 3 Bathrooms, 2 Balconies with Pooja Room,Servant Room                                            1
6 Bedrooms , 10 Bathrooms, No Balcony                                                                         1
5 Bedrooms , 4 Bathrooms, 2 Balconies with Pooja Room,Study Room                                              1
6 Bedrooms , 7 Bathrooms, 3+ Balconies                                                                        1
9 Bedrooms , 7 Bathrooms, No Balcony                                                                          1
5 Bedrooms , 5 Bathrooms, 3+ Balconies with Pooja Room,Servant Room,Store Room,Study Room                     1
3 Bedrooms , 3 Bathrooms, 2 Balconies with Pooja Room,Others                                                  1
6 Bedrooms , 3 Bathrooms, 3 Balconies                                                                         1
4 Bedrooms , 3 Bathrooms, 2 Balconies with Pooja Room,Study Room                                              1
6 Bedrooms , 5 Bathrooms, No Balcony                                                                          1
3 Bedrooms , 2 Bathrooms, No Balcony with Pooja Room,Study Room                                               1
4 Bedrooms , 4 Bathrooms, 3 Balconies with Others,Servant Room,Pooja Room,Study Room                          1
4 Bedrooms , 3 Bathrooms, 2 Balconies with Pooja Room,Store Room,Study Room,Servant Room                      1
4 Bedrooms , 4 Bathrooms, 3 Balconies with Servant Room                                                       1
8 Bedrooms , 6 Bathrooms, 2 Balconies with Study Room,Pooja Room,Others                                       1
5 Bedrooms , 4 Bathrooms, 2 Balconies with Study Room                                                         1
10 Bedrooms , 6 Bathrooms, 3 Balconies with Servant Room                                                      1
4 Bedrooms , 2 Bathrooms, 1 Balcony with Others                                                               1
2 Bedrooms , 2 Bathrooms, No Balcony\nView Floor Plan                                                         1
2 Bedrooms , 4 Bathrooms, No Balcony                                                                          1
3 Bedrooms , 4 Bathrooms, 3+ Balconies with Pooja Room,Servant Room                                           1
7 Bedrooms , 5 Bathrooms, No Balcony                                                                          1
6 Bedrooms , 6 Bathrooms, 2 Balconies with Pooja Room,Study Room,Servant Room,Others                          1
4 Bedrooms , 5 Bathrooms, No Balcony                                                                          1
7 Bedrooms , 3 Bathrooms, 2 Balconies                                                                         1
5 Bedrooms , 2 Bathrooms, 2 Balconies                                                                         1
10 Bedrooms , 4 Bathrooms, 3+ Balconies                                                                       1
2 Bedrooms , 2 Bathrooms, 1 Balcony with Study Room,Others                                                    1
9 Bedrooms , 6 Bathrooms, 2 Balconies with Pooja Room,Study Room,Servant Room                                 1
4 Bedrooms , 5 Bathrooms, 2 Balconies with Study Room                                                         1
4 Bedrooms , 3 Bathrooms, 2 Balconies with Pooja Room,Servant Room                                            1
4 Bedrooms , 7 Bathrooms, No Balcony                                                                          1
8 Bedrooms , 5 Bathrooms, 2 Balconies                                                                         1
7 Bedrooms , 5 Bathrooms, 1 Balcony with Others                                                               1
5 Bedrooms , 5 Bathrooms, 3+ Balconies                                                                        1
8 Bedrooms , 8 Bathrooms, 3 Balconies with Pooja Room,Study Room,Servant Room,Others                          1
5 Bedrooms , 5 Bathrooms, 2 Balconies with Pooja Room,Study Room,Store Room                                   1
5 Bedrooms , 4 Bathrooms, 3 Balconies with Servant Room                                                       1
2 Bedrooms , 1 Bathroom, No Balcony with Pooja Room,Store Room                                                1
11 Bedrooms , 11 Bathrooms, 2 Balconies                                                                       1
8 Bedrooms , 6 Bathrooms, 1 Balcony                                                                           1
4 Bedrooms , 5 Bathrooms, 1 Balcony                                                                           1
13 Bedrooms , 12 Bathrooms, 2 Balconies with Pooja Room,Study Room,Servant Room,Others                        1
2 Bedrooms , 1 Bathroom, No Balcony with Others\nView Floor Plan                                              1
6 Bedrooms , 3 Bathrooms, 2 Balconies with Servant Room,Study Room,Others                                     1
7 Bedrooms , 6 Bathrooms, 3 Balconies                                                                         1
3 Bedrooms , 4 Bathrooms, 1 Balcony with Pooja Room,Study Room,Servant Room,Store Room                        1

In [284]:
config_split = t['Configuration'].str.split('with',n=1,expand=True)
rooms = config_split[0].str.split(",",expand=True)

In [285]:
t[['bedrooms','bathrooms','balconies']] = rooms.rename(columns={0:"bedrooms",1:"bathrooms",2:"balconies"})

In [286]:
t.head()

,pname,society,price_outer,price_per_sqft,possesion,description,Area,Configuration,Price,Address,Total Floors,Facing,Property Age,furnishing,features,ratings,Overlooking,Possession in,bedrooms,bathrooms,balconies
0,"3 Bedroom House for sale in Kolar Road, Bhopal",ultimate english villa,60.0,8534,Ready To Move,Na....................................,Plot area 703\n(65.31 sq.m.) \nsq.ft.,"3 Bedrooms , 3 Bathrooms, 1 Balcony","₹ 60 Lac+ Govt Charges & Tax\n@ 8,534 per sq.f...","Ultimate English Villa\nKolar Road, Bhopal",2 Floors,West,5 to 10 Year Old,"['2 Wardrobe', '1 Light', '1 Modular Kitchen',...","['Maintenance Staff', 'Water Storage', 'Park',...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]",NaN,NaN,3 Bedrooms,3 Bathrooms,1 Balcony
1,"4 Bedroom House for sale in Lalghati, Bhopal",globus greens,225.0,15000,Ready To Move,It's very spacious bunglow ..It's prime locati...,Plot area 1500\n(139.35 sq.m.)\nBuilt Up area:...,"4 Bedrooms , 3 Bathrooms, 1 Balcony with Pooja...","₹ 2.25 Crore\n@ 15,000 per sq.ft. (Negotiable)","Globus Greens\nLalghati, Bhopal",2 Floors,West,5 to 10 Year Old,"['4 Bed', '8 Wardrobe', '6 Fan', '1 Sofa', '1 ...","['Private Garden / Terrace', 'Park', 'Visitor ...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]","Park/Garden,Club",NaN,4 Bedrooms,3 Bathrooms,1 Balcony
2,"6 Bedroom House for sale in Barkhera Pathani, ...",basant vihar colony,48.0,2400,Ready To Move,As you can see in the photos the ground floor ...,Plot area 625\n(58.06 sq.m.)\nBuilt Up area: 2...,"6 Bedrooms , 2 Bathrooms, 2 Balconies","₹ 48 Lac\n@ 2,400 per sq.ft. (Negotiable)","BASANT VIHAR COLONY\nBarkhera Pathani, Bhopal",3 Floors,North,1 to 5 Year Old,NaN,"['Water Storage', 'Park']",[],Park/Garden,NaN,6 Bedrooms,2 Bathrooms,2 Balconies
3,"9 Bedroom House for sale in Manak Vihar, Bhopal",manak vihar,150.0,5000,Ready To Move,Ground floor bedrooms two with common washroom...,Plot area 3000\n(278.71 sq.m.) \nsq.ft.,"9 Bedrooms , 7 Bathrooms, 1 Balcony with Pooja...","₹ 1.5 Crore\n@ 5,000 per sq.ft. (All inclusive...","Manak Vihar, Bhopal",2 Floors,NaN,10+ Year Old,NaN,"['Private Garden / Terrace', 'High Ceiling Hei...",[],NaN,NaN,9 Bedrooms,7 Bathrooms,1 Balcony
4,"5 Bedroom House for sale in Hoshangabad Road, ...",hoshangabad road,138.0,3484,Ready To Move,"East facing bunglow ,prime location at narmada...",Plot area 2135\n(198.35 sq.m.)\nBuilt Up area:...,"5 Bedrooms , 4 Bathrooms, 3 Balconies with Poo...","₹ 1.38 Crore+ Govt Charges & Tax\n@ 3,484 per ...","Hoshangabad Road, Bhopal",2 Floors,East,1 to 5 Year Old,"['4 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]","Park/Garden,Main Road",NaN,5 Bedrooms,4 Bathrooms,3 Balconies

In [287]:
t['additional_room'] = config_split[1]

In [288]:
t.head()

,pname,society,price_outer,price_per_sqft,possesion,description,Area,Configuration,Price,Address,Total Floors,Facing,Property Age,furnishing,features,ratings,Overlooking,Possession in,bedrooms,bathrooms,balconies,additional_room
0,"3 Bedroom House for sale in Kolar Road, Bhopal",ultimate english villa,60.0,8534,Ready To Move,Na....................................,Plot area 703\n(65.31 sq.m.) \nsq.ft.,"3 Bedrooms , 3 Bathrooms, 1 Balcony","₹ 60 Lac+ Govt Charges & Tax\n@ 8,534 per sq.f...","Ultimate English Villa\nKolar Road, Bhopal",2 Floors,West,5 to 10 Year Old,"['2 Wardrobe', '1 Light', '1 Modular Kitchen',...","['Maintenance Staff', 'Water Storage', 'Park',...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]",NaN,NaN,3 Bedrooms,3 Bathrooms,1 Balcony,None
1,"4 Bedroom House for sale in Lalghati, Bhopal",globus greens,225.0,15000,Ready To Move,It's very spacious bunglow ..It's prime locati...,Plot area 1500\n(139.35 sq.m.)\nBuilt Up area:...,"4 Bedrooms , 3 Bathrooms, 1 Balcony with Pooja...","₹ 2.25 Crore\n@ 15,000 per sq.ft. (Negotiable)","Globus Greens\nLalghati, Bhopal",2 Floors,West,5 to 10 Year Old,"['4 Bed', '8 Wardrobe', '6 Fan', '1 Sofa', '1 ...","['Private Garden / Terrace', 'Park', 'Visitor ...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]","Park/Garden,Club",NaN,4 Bedrooms,3 Bathrooms,1 Balcony,Pooja Room
2,"6 Bedroom House for sale in Barkhera Pathani, ...",basant vihar colony,48.0,2400,Ready To Move,As you can see in the photos the ground floor ...,Plot area 625\n(58.06 sq.m.)\nBuilt Up area: 2...,"6 Bedrooms , 2 Bathrooms, 2 Balconies","₹ 48 Lac\n@ 2,400 per sq.ft. (Negotiable)","BASANT VIHAR COLONY\nBarkhera Pathani, Bhopal",3 Floors,North,1 to 5 Year Old,NaN,"['Water Storage', 'Park']",[],Park/Garden,NaN,6 Bedrooms,2 Bathrooms,2 Balconies,None
3,"9 Bedroom House for sale in Manak Vihar, Bhopal",manak vihar,150.0,5000,Ready To Move,Ground floor bedrooms two with common washroom...,Plot area 3000\n(278.71 sq.m.) \nsq.ft.,"9 Bedrooms , 7 Bathrooms, 1 Balcony with Pooja...","₹ 1.5 Crore\n@ 5,000 per sq.ft. (All inclusive...","Manak Vihar, Bhopal",2 Floors,NaN,10+ Year Old,NaN,"['Private Garden / Terrace', 'High Ceiling Hei...",[],NaN,NaN,9 Bedrooms,7 Bathrooms,1 Balcony,Pooja Room
4,"5 Bedroom House for sale in Hoshangabad Road, ...",hoshangabad road,138.0,3484,Ready To Move,"East facing bunglow ,prime location at narmada...",Plot area 2135\n(198.35 sq.m.)\nBuilt Up area:...,"5 Bedrooms , 4 Bathrooms, 3 Balconies with Poo...","₹ 1.38 Crore+ Govt Charges & Tax\n@ 3,484 per ...","Hoshangabad Road, Bhopal",2 Floors,East,1 to 5 Year Old,"['4 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]","Park/Garden,Main Road",NaN,5 Bedrooms,4 Bathrooms,3 Balconies,"Pooja Room,Study Room,Servant Room,Others"

# bedrooms

In [289]:
t = t[~t['bedrooms'].str.contains('Bathroom')]

In [290]:
t['bedrooms'].value_counts()

bedrooms
3 Bedrooms      263
4 Bedrooms      220
2 Bedrooms      100
5 Bedrooms       92
6 Bedrooms       45
1 Bedroom        20
7 Bedrooms       19
8 Bedrooms       15
10 Bedrooms      15
9 Bedrooms        7
11 Bedrooms       1
13 Bedrooms       1
Name: count, dtype: int64

In [291]:
t['bedrooms'] = t['bedrooms'].str.replace('Bedrooms',"").str.replace('Bedroom',"").astype('int')

In [292]:
t.head()

,pname,society,price_outer,price_per_sqft,possesion,description,Area,Configuration,Price,Address,Total Floors,Facing,Property Age,furnishing,features,ratings,Overlooking,Possession in,bedrooms,bathrooms,balconies,additional_room
0,"3 Bedroom House for sale in Kolar Road, Bhopal",ultimate english villa,60.0,8534,Ready To Move,Na....................................,Plot area 703\n(65.31 sq.m.) \nsq.ft.,"3 Bedrooms , 3 Bathrooms, 1 Balcony","₹ 60 Lac+ Govt Charges & Tax\n@ 8,534 per sq.f...","Ultimate English Villa\nKolar Road, Bhopal",2 Floors,West,5 to 10 Year Old,"['2 Wardrobe', '1 Light', '1 Modular Kitchen',...","['Maintenance Staff', 'Water Storage', 'Park',...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]",NaN,NaN,3,3 Bathrooms,1 Balcony,None
1,"4 Bedroom House for sale in Lalghati, Bhopal",globus greens,225.0,15000,Ready To Move,It's very spacious bunglow ..It's prime locati...,Plot area 1500\n(139.35 sq.m.)\nBuilt Up area:...,"4 Bedrooms , 3 Bathrooms, 1 Balcony with Pooja...","₹ 2.25 Crore\n@ 15,000 per sq.ft. (Negotiable)","Globus Greens\nLalghati, Bhopal",2 Floors,West,5 to 10 Year Old,"['4 Bed', '8 Wardrobe', '6 Fan', '1 Sofa', '1 ...","['Private Garden / Terrace', 'Park', 'Visitor ...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]","Park/Garden,Club",NaN,4,3 Bathrooms,1 Balcony,Pooja Room
2,"6 Bedroom House for sale in Barkhera Pathani, ...",basant vihar colony,48.0,2400,Ready To Move,As you can see in the photos the ground floor ...,Plot area 625\n(58.06 sq.m.)\nBuilt Up area: 2...,"6 Bedrooms , 2 Bathrooms, 2 Balconies","₹ 48 Lac\n@ 2,400 per sq.ft. (Negotiable)","BASANT VIHAR COLONY\nBarkhera Pathani, Bhopal",3 Floors,North,1 to 5 Year Old,NaN,"['Water Storage', 'Park']",[],Park/Garden,NaN,6,2 Bathrooms,2 Balconies,None
3,"9 Bedroom House for sale in Manak Vihar, Bhopal",manak vihar,150.0,5000,Ready To Move,Ground floor bedrooms two with common washroom...,Plot area 3000\n(278.71 sq.m.) \nsq.ft.,"9 Bedrooms , 7 Bathrooms, 1 Balcony with Pooja...","₹ 1.5 Crore\n@ 5,000 per sq.ft. (All inclusive...","Manak Vihar, Bhopal",2 Floors,NaN,10+ Year Old,NaN,"['Private Garden / Terrace', 'High Ceiling Hei...",[],NaN,NaN,9,7 Bathrooms,1 Balcony,Pooja Room
4,"5 Bedroom House for sale in Hoshangabad Road, ...",hoshangabad road,138.0,3484,Ready To Move,"East facing bunglow ,prime location at narmada...",Plot area 2135\n(198.35 sq.m.)\nBuilt Up area:...,"5 Bedrooms , 4 Bathrooms, 3 Balconies with Poo...","₹ 1.38 Crore+ Govt Charges & Tax\n@ 3,484 per ...","Hoshangabad Road, Bhopal",2 Floors,East,1 to 5 Year Old,"['4 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]","Park/Garden,Main Road",NaN,5,4 Bathrooms,3 Balconies,"Pooja Room,Study Room,Servant Room,Others"

# bathrooms

In [293]:
t['bathrooms'].value_counts()

bathrooms
 3 Bathrooms     258
 2 Bathrooms     188
 4 Bathrooms     176
 5 Bathrooms      64
 1 Bathroom       46
 6 Bathrooms      35
 7 Bathrooms      16
 8 Bathrooms       8
 10 Bathrooms      3
 9 Bathrooms       2
 11 Bathrooms      1
 12 Bathrooms      1
Name: count, dtype: int64

In [294]:
t['bathrooms'] = t['bathrooms'].str.replace('Bathrooms',"").str.replace("Bathroom","").astype('int')

# balconies

In [295]:
t['balconies'].value_counts()

balconies
 1 Balcony                       185
 2 Balconies                     167
 2 Balconies                     124
 No Balcony                      102
 1 Balcony                        73
 3 Balconies                      59
 3 Balconies                      33
 3+ Balconies                     18
 3+ Balconies                     15
 No Balcony                       12
 2 Balconies\nView Floor Plan      6
 1 Balcony\nView Floor Plan        3
 No Balcony\nView Floor Plan       1
Name: count, dtype: int64

In [296]:
t['balconies'] = t['balconies'].str.replace('Balcony',"").str.replace('Balconies',"").str.strip().str.replace('\nView Floor Plan',"").str.replace("No","0").str.replace("3+","3").astype('int')

In [297]:
t.head()

,pname,society,price_outer,price_per_sqft,possesion,description,Area,Configuration,Price,Address,Total Floors,Facing,Property Age,furnishing,features,ratings,Overlooking,Possession in,bedrooms,bathrooms,balconies,additional_room
0,"3 Bedroom House for sale in Kolar Road, Bhopal",ultimate english villa,60.0,8534,Ready To Move,Na....................................,Plot area 703\n(65.31 sq.m.) \nsq.ft.,"3 Bedrooms , 3 Bathrooms, 1 Balcony","₹ 60 Lac+ Govt Charges & Tax\n@ 8,534 per sq.f...","Ultimate English Villa\nKolar Road, Bhopal",2 Floors,West,5 to 10 Year Old,"['2 Wardrobe', '1 Light', '1 Modular Kitchen',...","['Maintenance Staff', 'Water Storage', 'Park',...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]",NaN,NaN,3,3,1,None
1,"4 Bedroom House for sale in Lalghati, Bhopal",globus greens,225.0,15000,Ready To Move,It's very spacious bunglow ..It's prime locati...,Plot area 1500\n(139.35 sq.m.)\nBuilt Up area:...,"4 Bedrooms , 3 Bathrooms, 1 Balcony with Pooja...","₹ 2.25 Crore\n@ 15,000 per sq.ft. (Negotiable)","Globus Greens\nLalghati, Bhopal",2 Floors,West,5 to 10 Year Old,"['4 Bed', '8 Wardrobe', '6 Fan', '1 Sofa', '1 ...","['Private Garden / Terrace', 'Park', 'Visitor ...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]","Park/Garden,Club",NaN,4,3,1,Pooja Room
2,"6 Bedroom House for sale in Barkhera Pathani, ...",basant vihar colony,48.0,2400,Ready To Move,As you can see in the photos the ground floor ...,Plot area 625\n(58.06 sq.m.)\nBuilt Up area: 2...,"6 Bedrooms , 2 Bathrooms, 2 Balconies","₹ 48 Lac\n@ 2,400 per sq.ft. (Negotiable)","BASANT VIHAR COLONY\nBarkhera Pathani, Bhopal",3 Floors,North,1 to 5 Year Old,NaN,"['Water Storage', 'Park']",[],Park/Garden,NaN,6,2,2,None
3,"9 Bedroom House for sale in Manak Vihar, Bhopal",manak vihar,150.0,5000,Ready To Move,Ground floor bedrooms two with common washroom...,Plot area 3000\n(278.71 sq.m.) \nsq.ft.,"9 Bedrooms , 7 Bathrooms, 1 Balcony with Pooja...","₹ 1.5 Crore\n@ 5,000 per sq.ft. (All inclusive...","Manak Vihar, Bhopal",2 Floors,NaN,10+ Year Old,NaN,"['Private Garden / Terrace', 'High Ceiling Hei...",[],NaN,NaN,9,7,1,Pooja Room
4,"5 Bedroom House for sale in Hoshangabad Road, ...",hoshangabad road,138.0,3484,Ready To Move,"East facing bunglow ,prime location at narmada...",Plot area 2135\n(198.35 sq.m.)\nBuilt Up area:...,"5 Bedrooms , 4 Bathrooms, 3 Balconies with Poo...","₹ 1.38 Crore+ Govt Charges & Tax\n@ 3,484 per ...","Hoshangabad Road, Bhopal",2 Floors,East,1 to 5 Year Old,"['4 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]","Park/Garden,Main Road",NaN,5,4,3,"Pooja Room,Study Room,Servant Room,Others"

# additional rooms

In [298]:
t['additional_room'].value_counts()

additional_room
 Pooja Room                                                        57
 Others                                                            41
 Pooja Room,Study Room                                             26
 Pooja Room,Study Room,Servant Room,Store Room                     12
 Pooja Room,Study Room,Servant Room,Others                         11
 Servant Room                                                       9
 Study Room,Others                                                  9
 Study Room,Pooja Room,Others                                       9
 Pooja Room,Others                                                  8
 Pooja Room,Study Room,Others                                       8
 Pooja Room,Study Room,Store Room                                   7
 Pooja Room,Study Room,Servant Room                                 7
 Pooja Room,Store Room                                              7
 Study Room                                                         6
 Pooja Room,Servant Room                                            6
 Study Room,Servant Room                                            5
 Store Room                                                         5
 Study Room,Others,Pooja Room                                       4
 Pooja Room,Store Room,Study Room,Servant Room                      4
 Study Room,Pooja Room                                              3
 Study Room,Others,Servant Room                                     3
 Pooja Room,Others,Study Room                                       2
 Pooja Room,Store Room,Study Room,Servant Room\nView Floor Plan     2
 Servant Room,Store Room                                            2
 Pooja Room,Servant Room,Store Room                                 2
 Pooja Room,Servant Room,Others                                     2
 Store Room,Servant Room                                            2
 Others,Study Room                                                  2
 Others\nView Floor Plan                                            2
 Study Room,Others,Servant Room,Pooja Room                          1
 Pooja Room,Servant Room,Store Room,Study Room                      1
 Others,Servant Room,Pooja Room,Study Room                          1
 Servant Room,Pooja Room,Others                                     1
 Study Room,Pooja Room,Store Room,Servant Room\nView Floor Plan     1
 Study Room,Others,Pooja Room,Servant Room                          1
 Pooja Room,Study Room,Servant Room,Others\nView Floor Plan         1
 Servant Room,Others                                                1
 Study Room,Store Room                                              1
 Study Room,Servant Room,Store Room                                 1
 Others,Study Room,Pooja Room,Servant Room                          1
 Study Room,Pooja Room,Servant Room                                 1
 Pooja Room,Others,Servant Room                                     1
 Servant Room,Study Room,Pooja Room,Store Room                      1
 Study Room,Servant Room,Pooja Room                                 1
 Servant Room,Pooja Room                                            1
 Pooja Room,Study Room,Others,Servant Room                          1
 Others,Pooja Room,Study Room                                       1
 Pooja Room,Servant Room,Study Room                                 1
 Study Room,Pooja Room,Store Room,Servant Room                      1
 Servant Room,Study Room,Pooja Room,Others                          1
 Study Room,Store Room,Pooja Room                                   1
 Servant Room,Study Room,Others                                     1
Name: count, dtype: int64

In [306]:
t['additional_room'] = t['additional_room'].str.replace('\nView Floor Plan',"").str.lower().fillna('Not Available')

In [307]:
t.head()

,pname,society,price_outer,price_per_sqft,possesion,description,Area,Configuration,Price,Address,Total Floors,Facing,Property Age,furnishing,features,ratings,Overlooking,Possession in,bedrooms,bathrooms,balconies,additional_room
0,"3 Bedroom House for sale in Kolar Road, Bhopal",ultimate english villa,60.0,8534,Ready To Move,Na....................................,Plot area 703\n(65.31 sq.m.) \nsq.ft.,"3 Bedrooms , 3 Bathrooms, 1 Balcony","₹ 60 Lac+ Govt Charges & Tax\n@ 8,534 per sq.f...","Ultimate English Villa\nKolar Road, Bhopal",2 Floors,West,5 to 10 Year Old,"['2 Wardrobe', '1 Light', '1 Modular Kitchen',...","['Maintenance Staff', 'Water Storage', 'Park',...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]",NaN,NaN,3,3,1,Not Available
1,"4 Bedroom House for sale in Lalghati, Bhopal",globus greens,225.0,15000,Ready To Move,It's very spacious bunglow ..It's prime locati...,Plot area 1500\n(139.35 sq.m.)\nBuilt Up area:...,"4 Bedrooms , 3 Bathrooms, 1 Balcony with Pooja...","₹ 2.25 Crore\n@ 15,000 per sq.ft. (Negotiable)","Globus Greens\nLalghati, Bhopal",2 Floors,West,5 to 10 Year Old,"['4 Bed', '8 Wardrobe', '6 Fan', '1 Sofa', '1 ...","['Private Garden / Terrace', 'Park', 'Visitor ...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]","Park/Garden,Club",NaN,4,3,1,pooja room
2,"6 Bedroom House for sale in Barkhera Pathani, ...",basant vihar colony,48.0,2400,Ready To Move,As you can see in the photos the ground floor ...,Plot area 625\n(58.06 sq.m.)\nBuilt Up area: 2...,"6 Bedrooms , 2 Bathrooms, 2 Balconies","₹ 48 Lac\n@ 2,400 per sq.ft. (Negotiable)","BASANT VIHAR COLONY\nBarkhera Pathani, Bhopal",3 Floors,North,1 to 5 Year Old,NaN,"['Water Storage', 'Park']",[],Park/Garden,NaN,6,2,2,Not Available
3,"9 Bedroom House for sale in Manak Vihar, Bhopal",manak vihar,150.0,5000,Ready To Move,Ground floor bedrooms two with common washroom...,Plot area 3000\n(278.71 sq.m.) \nsq.ft.,"9 Bedrooms , 7 Bathrooms, 1 Balcony with Pooja...","₹ 1.5 Crore\n@ 5,000 per sq.ft. (All inclusive...","Manak Vihar, Bhopal",2 Floors,NaN,10+ Year Old,NaN,"['Private Garden / Terrace', 'High Ceiling Hei...",[],NaN,NaN,9,7,1,pooja room
4,"5 Bedroom House for sale in Hoshangabad Road, ...",hoshangabad road,138.0,3484,Ready To Move,"East facing bunglow ,prime location at narmada...",Plot area 2135\n(198.35 sq.m.)\nBuilt Up area:...,"5 Bedrooms , 4 Bathrooms, 3 Balconies with Poo...","₹ 1.38 Crore+ Govt Charges & Tax\n@ 3,484 per ...","Hoshangabad Road, Bhopal",2 Floors,East,1 to 5 Year Old,"['4 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]","Park/Garden,Main Road",NaN,5,4,3,"pooja room,study room,servant room,others"

# Total Floors

In [312]:
t['Total Floors'].isnull().sum()

34

In [308]:
t['Total Floors'].value_counts()

Total Floors
2 Floors     465
1 Floors     170
3 Floors     114
0 Floors       6
4 Floors       6
5 Floors       2
17 Floors      1
Name: count, dtype: int64

In [314]:
t['Total Floors'] = t['Total Floors'].str.replace('Floors',"").str.strip()

In [315]:
t['Total Floors'].value_counts()

Total Floors
2     465
1     170
3     114
0       6
4       6
5       2
17      1
Name: count, dtype: int64

# Facing

In [320]:
t['Facing'].value_counts()

Facing
NA            313
East          197
West          115
North          82
North-East     29
South          26
North-West     13
South-West     12
South-East     11
Name: count, dtype: int64

In [317]:
t['Facing'].isnull().sum()

313

In [319]:
t['Facing'] = t['Facing'].fillna('NA')

In [321]:
t.head()

,pname,society,price_outer,price_per_sqft,possesion,description,Area,Configuration,Price,Address,Total Floors,Facing,Property Age,furnishing,features,ratings,Overlooking,Possession in,bedrooms,bathrooms,balconies,additional_room
0,"3 Bedroom House for sale in Kolar Road, Bhopal",ultimate english villa,60.0,8534,Ready To Move,Na....................................,Plot area 703\n(65.31 sq.m.) \nsq.ft.,"3 Bedrooms , 3 Bathrooms, 1 Balcony","₹ 60 Lac+ Govt Charges & Tax\n@ 8,534 per sq.f...","Ultimate English Villa\nKolar Road, Bhopal",2,West,5 to 10 Year Old,"['2 Wardrobe', '1 Light', '1 Modular Kitchen',...","['Maintenance Staff', 'Water Storage', 'Park',...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]",NaN,NaN,3,3,1,Not Available
1,"4 Bedroom House for sale in Lalghati, Bhopal",globus greens,225.0,15000,Ready To Move,It's very spacious bunglow ..It's prime locati...,Plot area 1500\n(139.35 sq.m.)\nBuilt Up area:...,"4 Bedrooms , 3 Bathrooms, 1 Balcony with Pooja...","₹ 2.25 Crore\n@ 15,000 per sq.ft. (Negotiable)","Globus Greens\nLalghati, Bhopal",2,West,5 to 10 Year Old,"['4 Bed', '8 Wardrobe', '6 Fan', '1 Sofa', '1 ...","['Private Garden / Terrace', 'Park', 'Visitor ...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]","Park/Garden,Club",NaN,4,3,1,pooja room
2,"6 Bedroom House for sale in Barkhera Pathani, ...",basant vihar colony,48.0,2400,Ready To Move,As you can see in the photos the ground floor ...,Plot area 625\n(58.06 sq.m.)\nBuilt Up area: 2...,"6 Bedrooms , 2 Bathrooms, 2 Balconies","₹ 48 Lac\n@ 2,400 per sq.ft. (Negotiable)","BASANT VIHAR COLONY\nBarkhera Pathani, Bhopal",3,North,1 to 5 Year Old,NaN,"['Water Storage', 'Park']",[],Park/Garden,NaN,6,2,2,Not Available
3,"9 Bedroom House for sale in Manak Vihar, Bhopal",manak vihar,150.0,5000,Ready To Move,Ground floor bedrooms two with common washroom...,Plot area 3000\n(278.71 sq.m.) \nsq.ft.,"9 Bedrooms , 7 Bathrooms, 1 Balcony with Pooja...","₹ 1.5 Crore\n@ 5,000 per sq.ft. (All inclusive...","Manak Vihar, Bhopal",2,NA,10+ Year Old,NaN,"['Private Garden / Terrace', 'High Ceiling Hei...",[],NaN,NaN,9,7,1,pooja room
4,"5 Bedroom House for sale in Hoshangabad Road, ...",hoshangabad road,138.0,3484,Ready To Move,"East facing bunglow ,prime location at narmada...",Plot area 2135\n(198.35 sq.m.)\nBuilt Up area:...,"5 Bedrooms , 4 Bathrooms, 3 Balconies with Poo...","₹ 1.38 Crore+ Govt Charges & Tax\n@ 3,484 per ...","Hoshangabad Road, Bhopal",2,East,1 to 5 Year Old,"['4 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]","Park/Garden,Main Road",NaN,5,4,3,"pooja room,study room,servant room,others"

In [325]:
t['area'] = round(t['price_outer']*100000/t['price_per_sqft'],2)

In [326]:
t.head(2)

,pname,society,price_outer,price_per_sqft,possesion,description,Area,Configuration,Price,Address,Total Floors,Facing,Property Age,furnishing,features,ratings,Overlooking,Possession in,bedrooms,bathrooms,balconies,additional_room,area
0,"3 Bedroom House for sale in Kolar Road, Bhopal",ultimate english villa,60.0,8534,Ready To Move,Na....................................,Plot area 703\n(65.31 sq.m.) \nsq.ft.,"3 Bedrooms , 3 Bathrooms, 1 Balcony","₹ 60 Lac+ Govt Charges & Tax\n@ 8,534 per sq.f...","Ultimate English Villa\nKolar Road, Bhopal",2,West,5 to 10 Year Old,"['2 Wardrobe', '1 Light', '1 Modular Kitchen',...","['Maintenance Staff', 'Water Storage', 'Park',...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]",NaN,NaN,3,3,1,Not Available,703.07
1,"4 Bedroom House for sale in Lalghati, Bhopal",globus greens,225.0,15000,Ready To Move,It's very spacious bunglow ..It's prime locati...,Plot area 1500\n(139.35 sq.m.)\nBuilt Up area:...,"4 Bedrooms , 3 Bathrooms, 1 Balcony with Pooja...","₹ 2.25 Crore\n@ 15,000 per sq.ft. (Negotiable)","Globus Greens\nLalghati, Bhopal",2,West,5 to 10 Year Old,"['4 Bed', '8 Wardrobe', '6 Fan', '1 Sofa', '1 ...","['Private Garden / Terrace', 'Park', 'Visitor ...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]","Park/Garden,Club",NaN,4,3,1,pooja room,1500.00

In [329]:
t = t.drop(columns=['Configuration','Possession in','Price','Address','ratings'])

In [330]:
t.info()

<class 'pandas.core.frame.DataFrame'>
Index: 798 entries, 0 to 74
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pname            798 non-null    object
 1   society          798 non-null    object
 2   price_outer      798 non-null    float64
 3   price_per_sqft   798 non-null    int32
 4   possesion        798 non-null    object
 5   description      798 non-null    object
 6   Area             798 non-null    object
 7   Total Floors     764 non-null    object
 8   Facing           798 non-null    object
 9   Property Age     715 non-null    object
 10  furnishing       302 non-null    object
 11  features         447 non-null    object
 12  Overlooking      378 non-null    object
 13  bedrooms         798 non-null    int32
 14  bathrooms        798 non-null    int32
 15  balconies        798 non-null    int32
 16  additional_room  798 non-null    object
 17  area             798 non-null    float64
dtypes: float64(2), int32(4), object(12)
memory usage: 106.0+ KB

In [331]:
t.to_csv('bpl_house_cleaned_l1.csv',index=False)
t.to_excel('bpl_house_cleaned_l1.xlsx',index=False)