In [111]:
import pandas as pd 
import numpy as np 
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [112]:
t1 = pd.read_csv("bhopal_flats1.csv")
t2 = pd.read_csv("bhopal_flats2.csv")
t3 = pd.read_csv("bhopal_flats3.csv")
t4 = pd.read_csv("bhopal_flats4.csv")
t5 = pd.read_csv("bhopal_flats5.csv")
t6 = pd.read_csv("bhopal_flats6.csv")
t8 = pd.read_csv("bhopal_flats8.csv")
t9 = pd.read_csv("bhopal_flats9.csv")
t10 = pd.read_csv("bhopal_flats10.csv")
t11 = pd.read_csv("bhopal_flats11.csv")

In [113]:
t = pd.concat([t1,t2,t3,t4,t5,t6,t8,t9,t10,t11])
print('shape',t1.shape[0]+t2.shape[0]+t3.shape[0]+t4.shape[0]+t5.shape[0]+t6.shape[0]+t8.shape[0]+t9.shape[0]+t10.shape[0]+t11.shape[0])
print("t",t.shape)

shape 992
t (992, 18)

In [114]:
t.head()

,pname,society,price_outer,price_per_sqft,possesion,description,Area,Configuration,Price,Address,Floor Number,Facing,Property Age,furnishing,features,ratings,Overlooking,Possession in
0,"3 BHK Flat in Shahpura, Bhopal",Green Heights,₹75 Lac,"₹6,000 /sqft",Ready To Move,"Situated in shahpura, bhopal, green heights is...",Carpet area: 1250\n(116.13 sq.m.) \nsq.ft.,"3 Bedrooms , 3 Bathrooms, 2 Balconies","₹ 75 Lac\n@ 6,000 per sq.ft. (Negotiable) View...","Green Heights\nShahpura, Bhopal",1st of 6 Floors,East,5 to 10 Year Old,"['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '3 Ge...","['Feng Shui / Vaastu Compliant', 'Security / F...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]",NaN,NaN
1,"3 BHK Flat in MP Nagar, Bhopal",Keelandev Apartments,₹1.85 Cr,"₹10,481 /sqft",Ready To Move,For sale 3.5 bhk flat kilandev tower shivaji n...,Super Built up area 1765\n(163.97 sq.m.) \nsq...,"3 Bedrooms , 3 Bathrooms, 2 Balconies with Ser...","₹ 1.85 Crore+ Govt Charges & Tax\n@ 10,481 per...","Keelandev Apartments\nMP Nagar, Bhopal",5th of 10 Floors,North-West,1 to 5 Year Old,"['2 Wardrobe', '3 Fan', '1 Exhaust Fan', '2 Ge...","['Intercom Facility', 'Lift(s)', 'Maintenance ...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]",Main Road,NaN
2,"2 BHK Flat in New Central Jail, Bhopal",Satya Prakash Nice Space,₹35 Lac,"₹2,788 /sqft",Ready To Move,Luxurious 2 bhk apartment with all the modern ...,Super Built up area 1255\n(116.59 sq.m.)\nBuil...,"2 Bedrooms , 2 Bathrooms, 3 Balconies","₹ 35 Lac+ Govt Charges & Tax\n@ 2,788 per sq.f...","Satya Prakash Nice Space\n, Bhopal",3rd of 8 Floors,West,1 to 5 Year Old,[],"['Security / Fire Alarm', 'Power Back-up', 'Fe...",[],"Park/Garden,Club,Pool,Main Road",NaN
3,"3 BHK Flat in Hoshangabad Road, Bhopal",Lakhumal Nikhil Nestles,₹48 Lac,"₹2,953 /sqft",Ready To Move,"Situated in hoshangabad road, bhopal, lakhumal...",Super Built up area 1625\n(150.97 sq.m.)\nBuil...,"3 Bedrooms , 3 Bathrooms, 3 Balconies with Poo...","₹ 48 Lac+ Govt Charges & Tax\n@ 2,953 per sq.f...","Lakhumal Nikhil Nestles\nHoshangabad Road, Bhopal",1st of 6 Floors,South-West,1 to 5 Year Old,"['1 Water Purifier', '1 Fridge', '6 Fan', '1 E...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}, {'': ...","Park/Garden,Club,Main Road,Others,Sea facing",NaN
4,"2 BHK Flat in Sanjeev Nagar, Bhopal",RIPL Maple Tree,₹33 Lac,"₹3,038 /sqft",Ready To Move,Luxurious 2 bhk apartment with all the modern ...,Super Built up area 1086\n(100.89 sq.m.) \nsq...,"2 Bedrooms , 2 Bathrooms, 1 Balcony","₹ 33 Lac+ Govt Charges & Tax\n@ 3,038 per sq.f...","RIPL Maple Tree\nSanjeev Nagar, Bhopal",5th of 7 Floors,East,5 to 10 Year Old,"['2 Wardrobe', '2 Bed', '1 Water Purifier', '4...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]","Park/Garden,Club,Main Road",NaN

In [115]:
# shape
t.shape

(992, 18)

In [116]:
t.info()

<class 'pandas.core.frame.DataFrame'>
Index: 992 entries, 0 to 123
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   pname           992 non-null    object
 1   society         988 non-null    object
 2   price_outer     992 non-null    object
 3   price_per_sqft  992 non-null    object
 4   possesion       992 non-null    object
 5   description     992 non-null    object
 6   Area            990 non-null    object
 7   Configuration   990 non-null    object
 8   Price           990 non-null    object
 9   Address         990 non-null    object
 10  Floor Number    990 non-null    object
 11  Facing          466 non-null    object
 12  Property Age    930 non-null    object
 13  furnishing      992 non-null    object
 14  features        992 non-null    object
 15  ratings         992 non-null    object
 16  Overlooking     490 non-null    object
 17  Possession in   60 non-null     object
dtypes: object(18)
memory usage: 147.2+ KB

In [117]:
# check for duplicates
t.duplicated().sum()

208

In [118]:
# drop duplicates
t = t.drop_duplicates()

In [119]:
t.shape

(784, 18)

In [120]:
t['furnishing'] = t['furnishing'].replace({"[]":np.nan})

In [121]:
t['features'] = t['features'].replace({"[]":np.nan})

In [122]:
# check for missing values
t.isnull().sum()

pname               0
society             3
price_outer         0
price_per_sqft      0
possesion           0
description         0
Area                2
Configuration       2
Price               2
Address             2
Floor Number        2
Facing            393
Property Age       56
furnishing        413
features          216
ratings             0
Overlooking       370
Possession in     730
dtype: int64

In [123]:
t[t.isnull().sum(axis=1)>10].shape

(2, 18)

In [124]:
t = t[t.isnull().sum(axis=1)<10]

In [125]:
t.shape

(782, 18)

In [126]:
t.head()

,pname,society,price_outer,price_per_sqft,possesion,description,Area,Configuration,Price,Address,Floor Number,Facing,Property Age,furnishing,features,ratings,Overlooking,Possession in
0,"3 BHK Flat in Shahpura, Bhopal",Green Heights,₹75 Lac,"₹6,000 /sqft",Ready To Move,"Situated in shahpura, bhopal, green heights is...",Carpet area: 1250\n(116.13 sq.m.) \nsq.ft.,"3 Bedrooms , 3 Bathrooms, 2 Balconies","₹ 75 Lac\n@ 6,000 per sq.ft. (Negotiable) View...","Green Heights\nShahpura, Bhopal",1st of 6 Floors,East,5 to 10 Year Old,"['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '3 Ge...","['Feng Shui / Vaastu Compliant', 'Security / F...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]",NaN,NaN
1,"3 BHK Flat in MP Nagar, Bhopal",Keelandev Apartments,₹1.85 Cr,"₹10,481 /sqft",Ready To Move,For sale 3.5 bhk flat kilandev tower shivaji n...,Super Built up area 1765\n(163.97 sq.m.) \nsq...,"3 Bedrooms , 3 Bathrooms, 2 Balconies with Ser...","₹ 1.85 Crore+ Govt Charges & Tax\n@ 10,481 per...","Keelandev Apartments\nMP Nagar, Bhopal",5th of 10 Floors,North-West,1 to 5 Year Old,"['2 Wardrobe', '3 Fan', '1 Exhaust Fan', '2 Ge...","['Intercom Facility', 'Lift(s)', 'Maintenance ...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]",Main Road,NaN
2,"2 BHK Flat in New Central Jail, Bhopal",Satya Prakash Nice Space,₹35 Lac,"₹2,788 /sqft",Ready To Move,Luxurious 2 bhk apartment with all the modern ...,Super Built up area 1255\n(116.59 sq.m.)\nBuil...,"2 Bedrooms , 2 Bathrooms, 3 Balconies","₹ 35 Lac+ Govt Charges & Tax\n@ 2,788 per sq.f...","Satya Prakash Nice Space\n, Bhopal",3rd of 8 Floors,West,1 to 5 Year Old,NaN,"['Security / Fire Alarm', 'Power Back-up', 'Fe...",[],"Park/Garden,Club,Pool,Main Road",NaN
3,"3 BHK Flat in Hoshangabad Road, Bhopal",Lakhumal Nikhil Nestles,₹48 Lac,"₹2,953 /sqft",Ready To Move,"Situated in hoshangabad road, bhopal, lakhumal...",Super Built up area 1625\n(150.97 sq.m.)\nBuil...,"3 Bedrooms , 3 Bathrooms, 3 Balconies with Poo...","₹ 48 Lac+ Govt Charges & Tax\n@ 2,953 per sq.f...","Lakhumal Nikhil Nestles\nHoshangabad Road, Bhopal",1st of 6 Floors,South-West,1 to 5 Year Old,"['1 Water Purifier', '1 Fridge', '6 Fan', '1 E...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}, {'': ...","Park/Garden,Club,Main Road,Others,Sea facing",NaN
4,"2 BHK Flat in Sanjeev Nagar, Bhopal",RIPL Maple Tree,₹33 Lac,"₹3,038 /sqft",Ready To Move,Luxurious 2 bhk apartment with all the modern ...,Super Built up area 1086\n(100.89 sq.m.) \nsq...,"2 Bedrooms , 2 Bathrooms, 1 Balcony","₹ 33 Lac+ Govt Charges & Tax\n@ 3,038 per sq.f...","RIPL Maple Tree\nSanjeev Nagar, Bhopal",5th of 7 Floors,East,5 to 10 Year Old,"['2 Wardrobe', '2 Bed', '1 Water Purifier', '4...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]","Park/Garden,Club,Main Road",NaN

# Society

In [127]:
t['society'].value_counts()

society
Globus Coral Woods                                18
IBD Hallmark Citii                                14
Fortune Soumya Heritage                           13
Agrawal Sagar Golden Palm                         12
Nirupam Royal Palms                               11
Sarvadharm Colony                                 11
Agrawal Sagar Lakeview Homes                      11
Fortune Kasturi                                   10
Danish Hills View                                 10
Lakhumal Nikhil Nestles                            9
SARC Pacific Blue                                  8
Shiva Whispering Woods                             8
Asnani Spring Valley Dew                           7
Signature 360                                      7
Agrawal Sagar Green Hills                          7
Aakar Canal Kinship                                6
Agrawal Sagar Premium Towers                       6
Paras Heights                                      6
Archana Balaji Towers                              6
Rudraksh Kasturi                                   5
Keelandev Apartments                               5
Sagar Royal Villas                                 5
Samriddhi Apartment                                5
Raksha Eden Park                                   5
RIPL Maple Tree                                    5
Amaltas Ambreen Homes                              4
Regal Town                                         4
Gammon Shrishti CBD                                4
Fortune Soumya Atlantis                            4
Girnar Hills                                       4
Centurion Sky                                      4
Navaakar Parke Serene                              4
Macker Silver Estate Vertica                       4
Satya Prakash Nice Space                           4
Aadhhaar Symphony                                  4
Chinarr Dream CT                                   4
Unitech Unihomes                                   4
Amaltas Westminster                                4
Aryavrat British Park                              4
Shrinath Sheetal Heights                           3
Ultimate Campus                                    3
Landmark The Prospera                              3
Kartik Kasturi Heights                             3
Raj Minal Residency                                3
Rishikesh Nirmaan The Bellaire Mint                3
Aakriti Greens                                     3
Fortune Signature                                  3
Signature Residency                                3
LIG Flats                                          3
Mahendra Square                                    3
Shaligram Rudraksh Park phase 2                    3
Bhojpal Shree Krishna Heights                      3
Shri Balaji Swastik Grand                          3
Western Courtyard                                  3
Lila Atulyam                                       3
BDA Swami Vivekanand Parisar                       3
Vishnu Hitech City                                 3
Ville Panache                                      3
Chinarr Dream City                                 3
Fortune Divine City                                3
Janki Apartments                                   3
Natraj Society                                     3
Agrawal Sagar Landmark                             3
Harshit Lifestyle                                  3
Sterling Globe Grand                               3
Anmol Maple Tree Phase 2                           3
Covered Campus                                     2
Gauri Shankar Parisar                              2
Fast Track Heavens Life                            2
Aakrati Olive                                      2
Faith Imperial Heights                             2
Ruchi Lifescapes                                   2
GMR Golden Palm                                    2
Shriram Traders Ganga Heights 1                    2
Virasha Heights                                    2
Citi Vistaar                                       2
Drishti Enclave                                    2
Agrawal Sagar Eden Garden                          2
Soumya Evergreen                                   2
Simran Residency                                   2
Windsor Aralia                                     2
Vijay Stambh                                       2
Nikhil Devalaya Pristine                           2
Govind Garden                                      2
Shiv Angan                                         2
Regal Treasure                                     2
RSR Opel Orris                                     2
Bhopal Mahalaxmi Awasiy Parisar                    2
Swastik Grand                                      2
MPHID Dwarika Parisar                              2
Drishti City                                       2
Century Heights                                    2
Mirchandani Shalimar Enclave                       2
covered campus society                             2
Sagar Pearl Phase 2                                2
Green Heights                                      2
Amaltas Prospera                                   2
Bda Apartment                                      2
Agrawal Sagar Campus                               2
Bima Kunj                                          2
Paras Emperor Phase 1                              2
Ikon Kanha Greens                                  2
Ankur Complex                                      2
BDA Flats                                          2
BM Coral Casa                                      2
Sudha Apartment                                    2
Soumya Parklands                                   2
Lala Lajpat Rai Society                            2
Girnar Valley                                      2
Aashima Royal City                                 2
Indra Vihar Residency                              2
Shiv Aangan                                        2
Jharneshwar Complex                                2
Imperial Heights                                   2
Prestine The Homes                                 2
Sheetal Dham Society                               2
Sagar Life Style Towers                            2
Mirchandani Shalimar Campus                        2
DK Bridge Tower                                    2
Chinarr Sapphire                                   2
Fast Track Heavens Height                          2
Sterling Pride City                                2
Vardhaman Enclave                                  2
AP Park Avenue                                     2
Bhagwan Enclave Phase 2                            2
IBD Kings Park                                     2
A and A Regalia Heights                            2
Unitech Unihomes 2                                 2
Siddhartha Enclave                                 1
Kamal Krishna Plaza Apartments                     1
tata amantra                                       1
City Tower                                         1
Coral Woods                                        1
Sai Dev Apartment                                  1
Tilak Society                                      1
BDA Gharonda Barrai                                1
fine homes                                         1
Omen Residency                                     1
Singh Gaurav Heights                               1
Welcome Apartments                                 1
Shiva Estate                                       1
am apartment                                       1
LIG FLAT                                           1
geet mohini flats                                  1
Sharda Apartment                                   1
ananda dhara apartments                            1
Airport City                                       1
Shiva Apartment                                    1
RSR Opel Regency                                   1
silver sand heights                                1
Fortune Soumya Tulip Heights                       1
Geet mohini flats                                  1
danish nagar d-1                                   1
fortune saumya                                     1
Shashi Hi Tech City                                1
AAkar avenue                                       1
12no. bus stop multi                               1
appartment                                         1
Ma Apartment                                       1
Swarn Kunj                                         1
Rachna kunj , 01/313                               1
Draupadi Shivlok Heights                           1
RSR Satyam Estate                                  1
Shivlok Phase III                                  1
Signature 99                                       1
luxe residences                                    1
Balaji tower kolar eoad                            1
Imperial Harmony                                   1
Garnet block                                       1
Asnani Pebble Bay Phase 2                          1
Mahendra Township                                  1
Nirman Sudhas Parn Kuti Parisar                    1
IBD Royal City                                     1
Globus Coral Casa                                  1
Malik apartment                                    1
Sage Golden Spring                                 1
Vivek Apartment                                    1
Baba Better Homes                                  1
Ivory-11                                           1
Ganesh Complex                                     1
Soumya Enclave                                     1
Gaurav Nagar, Bairagarh Chichli, Kolar Road        1
Appartment girdhari                                1
Chinar Woodlands                                   1
gurushishya prangan society khadi road beed        1
Narmada Prem Kesar                                 1
green heights                                      1
Faith Imperial Height                              1
Sai Homes                                          1
Bilal complex Apartments                           1
khushipra                                          1
Hari Siddhi                                        1
Kamal The Bellaire                                 1
Ramayan Indraprasth Heights                        1
mahindra green woods                               1
Soumya Tulip Heights                               1
SBD Cosmos City                                    1
ratnagiri                                          1
Fame Lalita Nagar                                  1
Unihomes Bhopal                                    1
Idgah hills                                        1
Danish Kunj jain mandir                            1
Fortune Tulip Heights                              1
C21 Corporate Park                                 1
Crystal H Singapore City                           1
Sagar Homes 3                                      1
Samara Gold                                        1
Vajra Towers                                       1
surbhi mohini homes                                1
Archana Parisar                                    1
afroz appartment                                   1
Ram Complex                                        1
Aakriti Aqua City                                  1
Keelandev Tower                                    1
Kamal Krishnanchal                                 1
Relaible Heritage                                  1
haidar manzil                                      1
Metro Gulmohar                                     1
Soumya Evergreen EWS                               1
Shakun Samriddhi                                   1
c-block                                            1
park serine apartment sunkhedi bhopal              1
Mangalam Apartment                                 1
The Prospera                                       1
Regal Nest                                         1
Parke Serene                                       1
Surbhi Tower                                       1
Sri Mitra Spring Valley                            1
AB Smart City Phase 1                              1
Sagar Residency                                    1
Jeevan Vihar                                       1
Goyal Flats                                        1
Sunrise Colony                                     1
Mirza apartment                                    1
multi Qureshi apartment                            1
Appartment                                         1
Center Point Jinsi Square                          1
shobharam Gaud Apartment                           1
Shri Krishna Campus                                1
Sagar Estate                                       1
Surabhi Nikunj, Surabhi Mohini Homes               1
Devki Nikunj Heights                               1
Abhi Homes                                         1
bhuvi madhurban phase1                             1
Raj Rishi Parisar                                  1
rahul                                              1
Ishita Paradise                                    1
Tirupati Abhinav Homes                             1
Sai vishal Apartment                               1
Gomantika parisar                                  1
zone 1 samta saket                                 1
Fortune Atlantis Phase II                          1
Maharshi Patanjali                                 1
Garcious Taj Residency                             1
bda complex salaiya kolar                          1
samiddhi sukriti Kaveri society                    1
metro heights mayadham                             1
New PM Awas Yojna                                  1
Aakriti Enclave                                    1
RRG Township                                       1
Shubh Shanti Tower                                 1
Ritu 11th Mile Garden City                         1
shanti enclave                                     1
Akshara City                                       1
Empire Hights idgah Hills                          1
Parshvdham Apartments                              1
apsara complex                                     1
Sagar Eden Garden                                  1
Abbas Ahmed nagar                                  1
Veer Apartment                                     1
Tulsi green tower shivaji nagar bhopal             1
EWS Sai Apartment                                  1
Amra Estate                                        1
Fortune Delight                                    1
Rosewood Enclave                                   1
Neeti apartment                                    1
Parshav Apartment                                  1
GL Mid City Complex                                1
Shree jee tower                                    1
Gharonda Heights                                   1
Shreeji Tower                                      1
IBD hallmark city                                  1
Aamir apprtment                                    1
Shri Krishna Guru Complex                          1
Unique Residency                                   1
BDA Complex                                        1
Shriram NIPS                                       1
Gaurav Nagar Bairagarh Chichli Kolar               1
harisiddhi apartment s2                            1
Madina Trade Center                                1
Radha apartment bhagat singh chowk                 1
Krishna Tower                                      1
Mansa Vaidyanath Dham                              1
Paras Urbane Park                                  1
ashoka palace apartment                            1
Ashirwad Apartment                                 1
Kanha Kunj An Apartment                            1
Raj harsh colony                                   1
MAHAVEER APARTMENT                                 1
kartika home's                                     1
Shri Shankar Residency                             1
golden valley heights                              1
Queens Regency                                     1
Raunak Apartment                                   1
Jeet                                               1
Essarjee The New Fort                              1
Vasundhara parisar, teela jamalpura                1
victoria appts.                                    1
Sagar royal villas                                 1
Chinar Dream CT                                    1
Garden Residency                                   1
Kidwai Manzil                                      1
Bhanpur Height                                     1
LIG-176                                            1
Essarjee Sampada                                   1
Shriram Sai Parisar                                1
Aliganj                                            1
Jeet Homes                                         1
Al-fiza tower                                      1
Globus Green Bay                                   1
Platinum Park                                      1
Geet Skyville                                      1
Silver Okh                                         1
Aastha Heights                                     1
RKN Nakshatra Enclave                              1
satya apartment                                    1
Sanjay Complex                                     1
Hoshangabad Road                                   1
Deep Apartment                                     1
app                                                1
saikripa apartment mandakini colony kolar road     1
Surya Plaza                                        1
Ganga Jamuna Apartments                            1
BABA Apartments E7 Arera Colony                    1
Ujjawala Aamra Valley                              1
husna apartment                                    1
Vaibhav apartment                                  1
bhuvi madhurban phase 1                            1
oceanic towers                                     1
Siddharth Tower                                    1
Siddharth Enclave                                  1
Aaren Bhagwan Parisar                              1
Sheena Apartments                                  1
Shri Parasnath Sheetal Tower                       1
Indrapuri Apartments                               1
Fortune Pride Extension                            1
Neeraj Nagar bawadia kalan                         1
Aura Mall                                          1
Silver Sand Heights, Bhopal                        1
Surabhi Smart City                                 1
Yashoda Apartment                                  1
transport                                          1
Mahalaxmi Awasiya parisar                          1
Sheetal Dham                                       1
Udhyogpuri Apartment                               1
Madhuban Heights                                   1
somya park land                                    1
aryan heights                                      1
Ganga nagar apartment                              1
Baghmugaliya                                       1
Landmark Square                                    1
KUNDAN NAGAR                                       1
chuna bhati                                        1
Aakriti The Nest                                   1
Ultimate Sky Villas                                1
IBD Royal Citii                                    1
Amaltas Avenue                                     1
On Request                                         1
YASHODA DISIRE                                     1
Mirchandani Shalimar Regency                       1
Kalpataru Galaxy Towers                            1
MP Rachna Towers                                   1
Shaligram Rudraksh Park                            1
Tirupati Nand Vihar                                1
Fame Kingdom Palace                                1
Vardhaman city plaza                               1
Prakrati Eden and Elite                            1

In [128]:
t['society'].value_counts().shape

(436,)

In [129]:
t['society'] = t['society'].str.strip().str.lower().str.replace(",","").str.replace('bhopal','').str.strip()

In [130]:
t['society'].value_counts().shape

(430,)

In [131]:
t = t[t['price_outer']!='Price on Request']

In [132]:
t['price_outer'].value_counts()

price_outer
₹25 Lac       55
₹35 Lac       49
₹30 Lac       43
₹45 Lac       34
₹55 Lac       33
₹40 Lac       30
₹20 Lac       22
₹32 Lac       21
₹50 Lac       19
₹22 Lac       17
₹42 Lac       16
₹26 Lac       15
₹60 Lac       14
₹65 Lac       14
₹38 Lac       14
₹16 Lac       11
₹23 Lac       11
₹75 Lac       11
₹36 Lac       10
₹15 Lac       10
₹70 Lac       10
₹33 Lac       10
₹27 Lac       10
₹17 Lac        9
₹18 Lac        9
₹28 Lac        9
₹48 Lac        7
₹21 Lac        7
₹95 Lac        7
₹31 Lac        6
₹2 Cr          6
₹24 Lac        6
₹85 Lac        6
₹58 Lac        6
₹19 Lac        6
₹12 Lac        5
₹37 Lac        5
₹44 Lac        5
₹22.5 Lac      5
₹10 Lac        5
₹43 Lac        5
₹51 Lac        5
₹62 Lac        5
₹14 Lac        4
₹16.5 Lac      4
₹52 Lac        4
₹2.5 Cr        4
₹41 Lac        4
₹14.5 Lac      4
₹57 Lac        4
₹34 Lac        4
₹56 Lac        4
₹90 Lac        4
₹13.5 Lac      3
₹47 Lac        3
₹72 Lac        3
₹69 Lac        3
₹39 Lac        3
₹8 Lac         3
₹23.9 Lac      3
₹80 Lac        3
₹46 Lac        3
₹1 Cr          3
₹1.5 Cr        2
₹31.5 Lac      2
₹63 Lac        2
₹19.5 Lac      2
₹29 Lac        2
₹10.5 Lac      2
₹1.65 Cr       2
₹1.25 Cr       2
₹1.75 Cr       2
₹68 Lac        2
₹87 Lac        2
₹9.5 Lac       2
₹93 Lac        2
₹25.5 Lac      2
₹32.5 Lac      2
₹20.5 Lac      2
₹7 Lac         2
₹11.5 Lac      2
₹29.5 Lac      2
₹3 Cr          2
₹2.4 Cr        2
₹21.5 Lac      2
₹18.5 Lac      2
₹8.5 Lac       2
₹6.1 Lac       1
₹62.5 Lac      1
₹5.8 Lac       1
₹33.99 Lac     1
₹12.9 Lac      1
₹25.9 Lac      1
₹30.9 Lac      1
₹27.25 Lac     1
₹24.5 Lac      1
₹27.5 Lac      1
₹51.5 Lac      1
₹22.75 Lac     1
₹21.9 Lac      1
₹29.85 Lac     1
₹30.5 Lac      1
₹51.25 Lac     1
₹1.3 Cr        1
₹16.75 Lac     1
₹27.8 Lac      1
₹35.5 Lac      1
₹11 Lac        1
₹18.3 Lac      1
₹17.5 Lac      1
₹1.18 Cr       1
₹9 Lac         1
₹54.9 Lac      1
₹2.25 Cr       1
₹6.5 Cr        1
₹4.5 Cr        1
₹1.05 Cr       1
₹1.1 Cr        1
₹1.85 Cr       1
₹34.95 Lac     1
₹26.5 Lac      1
₹36.75 Lac     1
₹50.64 Lac     1
₹82 Lac        1
₹53 Lac        1
₹37.8 Lac      1
₹78 Lac        1
₹16.53 Lac     1
₹13 Lac        1
₹64 Lac        1
₹1.15 Cr       1
₹36.9 Lac      1
₹2.1 Cr        1
₹49.9 Lac      1
₹1.7 Cr        1
₹3.15 Cr       1
₹2.45 Cr       1
₹49.99 Lac     1
₹44.9 Lac      1
₹74.99 Lac     1
₹22.99 Lac     1
₹1.2 Cr        1
₹1.41 Cr       1
₹4.8 Cr        1
₹24.99 Lac     1
₹1.4 Cr        1
₹67 Lac        1
₹50.88 Lac     1
Name: count, dtype: int64

In [133]:
def price_treatment(text):
    t = text.replace('₹',"").strip()
    if "Cr" in t:
        return float(t.replace("Cr","").strip())*100
    else:
        return float(t.replace("Lac","").strip())
        
        
t['price_outer'] = t['price_outer'].apply(price_treatment)

In [134]:
t.head()

,pname,society,price_outer,price_per_sqft,possesion,description,Area,Configuration,Price,Address,Floor Number,Facing,Property Age,furnishing,features,ratings,Overlooking,Possession in
0,"3 BHK Flat in Shahpura, Bhopal",green heights,75.0,"₹6,000 /sqft",Ready To Move,"Situated in shahpura, bhopal, green heights is...",Carpet area: 1250\n(116.13 sq.m.) \nsq.ft.,"3 Bedrooms , 3 Bathrooms, 2 Balconies","₹ 75 Lac\n@ 6,000 per sq.ft. (Negotiable) View...","Green Heights\nShahpura, Bhopal",1st of 6 Floors,East,5 to 10 Year Old,"['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '3 Ge...","['Feng Shui / Vaastu Compliant', 'Security / F...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]",NaN,NaN
1,"3 BHK Flat in MP Nagar, Bhopal",keelandev apartments,185.0,"₹10,481 /sqft",Ready To Move,For sale 3.5 bhk flat kilandev tower shivaji n...,Super Built up area 1765\n(163.97 sq.m.) \nsq...,"3 Bedrooms , 3 Bathrooms, 2 Balconies with Ser...","₹ 1.85 Crore+ Govt Charges & Tax\n@ 10,481 per...","Keelandev Apartments\nMP Nagar, Bhopal",5th of 10 Floors,North-West,1 to 5 Year Old,"['2 Wardrobe', '3 Fan', '1 Exhaust Fan', '2 Ge...","['Intercom Facility', 'Lift(s)', 'Maintenance ...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]",Main Road,NaN
2,"2 BHK Flat in New Central Jail, Bhopal",satya prakash nice space,35.0,"₹2,788 /sqft",Ready To Move,Luxurious 2 bhk apartment with all the modern ...,Super Built up area 1255\n(116.59 sq.m.)\nBuil...,"2 Bedrooms , 2 Bathrooms, 3 Balconies","₹ 35 Lac+ Govt Charges & Tax\n@ 2,788 per sq.f...","Satya Prakash Nice Space\n, Bhopal",3rd of 8 Floors,West,1 to 5 Year Old,NaN,"['Security / Fire Alarm', 'Power Back-up', 'Fe...",[],"Park/Garden,Club,Pool,Main Road",NaN
3,"3 BHK Flat in Hoshangabad Road, Bhopal",lakhumal nikhil nestles,48.0,"₹2,953 /sqft",Ready To Move,"Situated in hoshangabad road, bhopal, lakhumal...",Super Built up area 1625\n(150.97 sq.m.)\nBuil...,"3 Bedrooms , 3 Bathrooms, 3 Balconies with Poo...","₹ 48 Lac+ Govt Charges & Tax\n@ 2,953 per sq.f...","Lakhumal Nikhil Nestles\nHoshangabad Road, Bhopal",1st of 6 Floors,South-West,1 to 5 Year Old,"['1 Water Purifier', '1 Fridge', '6 Fan', '1 E...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}, {'': ...","Park/Garden,Club,Main Road,Others,Sea facing",NaN
4,"2 BHK Flat in Sanjeev Nagar, Bhopal",ripl maple tree,33.0,"₹3,038 /sqft",Ready To Move,Luxurious 2 bhk apartment with all the modern ...,Super Built up area 1086\n(100.89 sq.m.) \nsq...,"2 Bedrooms , 2 Bathrooms, 1 Balcony","₹ 33 Lac+ Govt Charges & Tax\n@ 3,038 per sq.f...","RIPL Maple Tree\nSanjeev Nagar, Bhopal",5th of 7 Floors,East,5 to 10 Year Old,"['2 Wardrobe', '2 Bed', '1 Water Purifier', '4...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]","Park/Garden,Club,Main Road",NaN

# price_per_sqft

In [135]:
t['price_per_sqft'].value_counts()

price_per_sqft
₹3,333 /sqft       22
₹3,000 /sqft       16
₹4,000 /sqft       12
₹3,500 /sqft       11
₹5,000 /sqft       11
₹2,000 /sqft       10
₹2,500 /sqft        9
₹3,666 /sqft        7
₹4,285 /sqft        7
₹2,666 /sqft        7
₹3,750 /sqft        6
₹6,000 /sqft        5
₹3,600 /sqft        5
₹3,125 /sqft        5
₹5,833 /sqft        5
₹4,166 /sqft        5
₹2,857 /sqft        4
₹2,916 /sqft        4
₹4,500 /sqft        4
₹3,846 /sqft        4
₹3,214 /sqft        4
₹2,333 /sqft        4
₹4,545 /sqft        4
₹3,571 /sqft        4
₹2,461 /sqft        3
₹3,200 /sqft        3
₹4,117 /sqft        3
₹4,666 /sqft        3
₹2,769 /sqft        3
₹2,750 /sqft        3
₹2,539 /sqft        3
₹5,384 /sqft        3
₹3,076 /sqft        3
₹2,314 /sqft        3
₹4,823 /sqft        3
₹2,250 /sqft        3
₹2,300 /sqft        3
₹11,331 /sqft       3
₹3,250 /sqft        3
₹2,727 /sqft        3
₹3,703 /sqft        3
₹3,428 /sqft        3
₹6,666 /sqft        3
₹4,074 /sqft        2
₹2,962 /sqft        2
₹3,271 /sqft        2
₹3,230 /sqft        2
₹4,636 /sqft        2
₹5,714 /sqft        2
₹11,532 /sqft       2
₹3,142 /sqft        2
₹3,103 /sqft        2
₹4,015 /sqft        2
₹4,347 /sqft        2
₹2,696 /sqft        2
₹2,562 /sqft        2
₹2,875 /sqft        2
₹3,466 /sqft        2
₹3,400 /sqft        2
₹2,235 /sqft        2
₹4,700 /sqft        2
₹3,222 /sqft        2
₹2,400 /sqft        2
₹2,558 /sqft        2
₹3,928 /sqft        2
₹3,833 /sqft        2
₹2,588 /sqft        2
₹2,755 /sqft        2
₹6,153 /sqft        2
₹2,928 /sqft        2
₹2,533 /sqft        2
₹3,409 /sqft        2
₹4,687 /sqft        2
₹5,066 /sqft        2
₹6,500 /sqft        2
₹4,615 /sqft        2
₹3,111 /sqft        2
₹5,319 /sqft        2
₹3,555 /sqft        2
₹2,931 /sqft        2
₹4,189 /sqft        2
₹3,071 /sqft        2
₹2,424 /sqft        2
₹2,800 /sqft        2
₹3,488 /sqft        2
₹3,692 /sqft        2
₹4,375 /sqft        2
₹3,52,941 /sqft     2
₹2,850 /sqft        2
₹3,454 /sqft        2
₹3,424 /sqft        2
₹2,777 /sqft        2
₹2,173 /sqft        2
₹3,238 /sqft        2
₹2,162 /sqft        2
₹4,181 /sqft        2
₹3,714 /sqft        2
₹2,921 /sqft        2
₹3,089 /sqft        2
₹4,583 /sqft        2
₹2,985 /sqft        2
₹5,555 /sqft        2
₹10,000 /sqft       2
₹3,818 /sqft        2
₹2,812 /sqft        2
₹4,333 /sqft        2
₹2,325 /sqft        2
₹2,543 /sqft        2
₹3,733 /sqft        2
₹3,043 /sqft        2
₹3,134 /sqft        2
₹2,640 /sqft        2
₹5,067 /sqft        1
₹2,291 /sqft        1
₹13,888 /sqft       1
₹2,429 /sqft        1
₹2,463 /sqft        1
₹9,285 /sqft        1
₹2,191 /sqft        1
₹3,433 /sqft        1
₹4,200 /sqft        1
₹4,300 /sqft        1
₹3,762 /sqft        1
₹6,600 /sqft        1
₹5,937 /sqft        1
₹4,245 /sqft        1
₹3,468 /sqft        1
₹6,875 /sqft        1
₹2,222 /sqft        1
₹2,047 /sqft        1
₹6,437 /sqft        1
₹2,984 /sqft        1
₹11,333 /sqft       1
₹10,804 /sqft       1
₹7,659 /sqft        1
₹4,860 /sqft        1
₹5,185 /sqft        1
₹2,270 /sqft        1
₹6,201 /sqft        1
₹2,230 /sqft        1
₹2,150 /sqft        1
₹2,712 /sqft        1
₹2,242 /sqft        1
₹12,500 /sqft       1
₹2,883 /sqft        1
₹5,467 /sqft        1
₹2,125 /sqft        1
₹3,410 /sqft        1
₹3,453 /sqft        1
₹3,888 /sqft        1
₹7,200 /sqft        1
₹3,834 /sqft        1
₹9,090 /sqft        1
₹4,031 /sqft        1
₹2,428 /sqft        1
₹2,285 /sqft        1
₹2,171 /sqft        1
₹2,290 /sqft        1
₹4,268 /sqft        1
₹3,037 /sqft        1
₹4,990 /sqft        1
₹2,116 /sqft        1
₹2,600 /sqft        1
₹4,909 /sqft        1
₹4,183 /sqft        1
₹2,485 /sqft        1
₹3,066 /sqft        1
₹4,132 /sqft        1
₹5,841 /sqft        1
₹2,479 /sqft        1
₹4,867 /sqft        1
₹4,938 /sqft        1
₹3,020 /sqft        1
₹6,119 /sqft        1
₹2,925 /sqft        1
₹8,208 /sqft        1
₹2,046 /sqft        1
₹3,328 /sqft        1
₹3,024 /sqft        1
₹1,846 /sqft        1
₹5,875 /sqft        1
₹5,068 /sqft        1
₹2,643 /sqft        1
₹2,933 /sqft        1
₹1,770 /sqft        1
₹3,795 /sqft        1
₹3,080 /sqft        1
₹3,157 /sqft        1
₹1,969 /sqft        1
₹3,811 /sqft        1
₹2,989 /sqft        1
₹2,711 /sqft        1
₹3,544 /sqft        1
₹1,718 /sqft        1
₹2,212 /sqft        1
₹2,888 /sqft        1
₹2,272 /sqft        1
₹2,587 /sqft        1
₹6,724 /sqft        1
₹2,865 /sqft        1
₹2,553 /sqft        1
₹4,167 /sqft        1
₹2,744 /sqft        1
₹3,777 /sqft        1
₹3,588 /sqft        1
₹2,523 /sqft        1
₹2,133 /sqft        1
₹3,896 /sqft        1
₹3,650 /sqft        1
₹3,853 /sqft        1
₹4,144 /sqft        1
₹2,547 /sqft        1
₹3,045 /sqft        1
₹2,606 /sqft        1
₹4,113 /sqft        1
₹724 /sqft          1
₹2,406 /sqft        1
₹2,892 /sqft        1
₹2,724 /sqft        1
₹2,460 /sqft        1
₹3,245 /sqft        1
₹2,370 /sqft        1
₹3,300 /sqft        1
₹3,851 /sqft        1
₹2,700 /sqft        1
₹2,997 /sqft        1
₹2,774 /sqft        1
₹5,027 /sqft        1
₹2,142 /sqft        1
₹3,749 /sqft        1
₹3,823 /sqft        1
₹2,802 /sqft        1
₹5,800 /sqft        1
₹7,123 /sqft        1
₹3,168 /sqft        1
₹2,368 /sqft        1
₹2,269 /sqft        1
₹9,291 /sqft        1
₹5,479 /sqft        1
₹1,702 /sqft        1
₹4,125 /sqft        1
₹2,990 /sqft        1
₹3,275 /sqft        1
₹1,914 /sqft        1
₹5,045 /sqft        1
₹3,797 /sqft        1
₹2,880 /sqft        1
₹1,066 /sqft        1
₹2,439 /sqft        1
₹1,498 /sqft        1
₹3,194 /sqft        1
₹2,362 /sqft        1
₹2,839 /sqft        1
₹2,444 /sqft        1
₹4,915 /sqft        1
₹2,355 /sqft        1
₹2,650 /sqft        1
₹2,388 /sqft        1
₹3,614 /sqft        1
₹2,958 /sqft        1
₹8,922 /sqft        1
₹5,428 /sqft        1
₹5,223 /sqft        1
₹3,113 /sqft        1
₹3,252 /sqft        1
₹3,736 /sqft        1
₹4,235 /sqft        1
₹2,380 /sqft        1
₹3,310 /sqft        1
₹2,909 /sqft        1
₹6,428 /sqft        1
₹4,400 /sqft        1
₹3,369 /sqft        1
₹3,033 /sqft        1
₹6,054 /sqft        1
₹3,260 /sqft        1
₹4,270 /sqft        1
₹3,082 /sqft        1
₹2,636 /sqft        1
₹5,448 /sqft        1
₹7,142 /sqft        1
₹2,167 /sqft        1
₹1,936 /sqft        1
₹2,820 /sqft        1
₹2,723 /sqft        1
₹2,100 /sqft        1
₹2,471 /sqft        1
₹2,267 /sqft        1
₹2,882 /sqft        1
₹2,390 /sqft        1
₹5,667 /sqft        1
₹3,554 /sqft        1
₹2,397 /sqft        1
₹4,705 /sqft        1
₹2,976 /sqft        1
₹3,655 /sqft        1
₹1,272 /sqft        1
₹1,416 /sqft        1
₹4,385 /sqft        1
₹944 /sqft          1
₹2,209 /sqft        1
₹4,444 /sqft        1
₹7,812 /sqft        1
₹3,881 /sqft        1
₹4,428 /sqft        1
₹3,611 /sqft        1
₹2,814 /sqft        1
₹6,472 /sqft        1
₹2,965 /sqft        1
₹4,900 /sqft        1
₹5,909 /sqft        1
₹3,081 /sqft        1
₹5,905 /sqft        1
₹2,720 /sqft        1
₹19,817 /sqft       1
₹3,520 /sqft        1
₹5,633 /sqft        1
₹3,683 /sqft        1
₹1,833 /sqft        1
₹5,399 /sqft        1
₹2,617 /sqft        1
₹10,909 /sqft       1
₹1,953 /sqft        1
₹2,214 /sqft        1
₹2,592 /sqft        1
₹4,608 /sqft        1
₹5,454 /sqft        1
₹2,978 /sqft        1
₹2,903 /sqft        1
₹7,448 /sqft        1
₹2,480 /sqft        1
₹3,636 /sqft        1
₹3,267 /sqft        1
₹5,095 /sqft        1
₹2,751 /sqft        1
₹4,891 /sqft        1
₹2,807 /sqft        1
₹3,208 /sqft        1
₹5,692 /sqft        1
₹5,605 /sqft        1
₹3,396 /sqft        1
₹4,691 /sqft        1
₹3,635 /sqft        1
₹3,286 /sqft        1
₹3,292 /sqft        1
₹1,428 /sqft        1
₹4,505 /sqft        1
₹223 /sqft          1
₹3,543 /sqft        1
₹2,625 /sqft        1
₹4,861 /sqft        1
₹2,228 /sqft        1
₹4,362 /sqft        1
₹2,166 /sqft        1
₹4,162 /sqft        1
₹4,411 /sqft        1
₹2,938 /sqft        1
₹4,515 /sqft        1
₹4,631 /sqft        1
₹2,960 /sqft        1
₹2,609 /sqft        1
₹4,395 /sqft        1
₹2,844 /sqft        1
₹2,346 /sqft        1
₹2,869 /sqft        1
₹2,015 /sqft        1
₹10,521 /sqft       1
₹3,058 /sqft        1
₹2,503 /sqft        1
₹3,120 /sqft        1
₹2,661 /sqft        1
₹3,012 /sqft        1
₹5,142 /sqft        1
₹4,814 /sqft        1
₹2,705 /sqft        1
₹2,090 /sqft        1
₹3,684 /sqft        1
₹3,181 /sqft        1
₹5,701 /sqft        1
₹5,769 /sqft        1
₹3,608 /sqft        1
₹2,682 /sqft        1
₹4,310 /sqft        1
₹3,830 /sqft        1
₹2,830 /sqft        1
₹3,038 /sqft        1
₹2,953 /sqft        1
₹2,788 /sqft        1
₹4,266 /sqft        1
₹3,512 /sqft        1
₹2,695 /sqft        1
₹4,482 /sqft        1
₹3,933 /sqft        1
₹6,250 /sqft        1
₹1,955 /sqft        1
₹4,077 /sqft        1
₹4,475 /sqft        1
₹2,266 /sqft        1
₹5,796 /sqft        1
₹2,796 /sqft        1
₹3,273 /sqft        1
₹3,294 /sqft        1
₹4,857 /sqft        1
₹2,667 /sqft        1
₹5,225 /sqft        1
₹4,769 /sqft        1
₹352 /sqft          1
₹5,750 /sqft        1
₹3,515 /sqft        1
₹4,153 /sqft        1
₹2,593 /sqft        1
₹8,095 /sqft        1
₹7,133 /sqft        1
₹2,200 /sqft        1
₹6,369 /sqft        1
₹4,358 /sqft        1
₹4,689 /sqft        1
₹3,885 /sqft        1
₹2,275 /sqft        1
₹3,530 /sqft        1
₹4,109 /sqft        1
₹11,166 /sqft       1
₹3,771 /sqft        1
₹12,013 /sqft       1
₹2,186 /sqft        1
₹2,713 /sqft        1
₹10,481 /sqft       1
₹2,564 /sqft        1
₹2,941 /sqft        1
₹6,130 /sqft        1
₹3,622 /sqft        1
₹6,309 /sqft        1
₹3,800 /sqft        1
₹3,090 /sqft        1
₹2,966 /sqft        1
₹3,478 /sqft        1
₹5,200 /sqft        1
₹3,757 /sqft        1
₹7,000 /sqft        1
₹7,624 /sqft        1
₹3,892 /sqft        1
₹5,777 /sqft        1
₹5,861 /sqft        1
₹2,571 /sqft        1
₹4,683 /sqft        1
₹2,555 /sqft        1
₹3,166 /sqft        1
₹2,067 /sqft        1
₹2,654 /sqft        1
₹5,970 /sqft        1
₹3,144 /sqft        1
₹3,706 /sqft        1
₹4,090 /sqft        1
₹3,384 /sqft        1
₹5,111 /sqft        1
₹6,315 /sqft        1
₹12,692 /sqft       1
₹2,923 /sqft        1
₹2,051 /sqft        1
₹4,157 /sqft        1
₹3,539 /sqft        1
₹2,470 /sqft        1
₹4,777 /sqft        1
₹3,131 /sqft        1
₹4,460 /sqft        1
₹9,259 /sqft        1
₹3,838 /sqft        1
₹4,255 /sqft        1
₹4,115 /sqft        1
₹6,976 /sqft        1
₹9,742 /sqft        1
₹10,566 /sqft       1
₹6,508 /sqft        1
₹5,308 /sqft        1
₹3,502 /sqft        1
₹4,391 /sqft        1
₹3,028 /sqft        1
₹2,343 /sqft        1
₹11,627 /sqft       1
₹6,571 /sqft        1
₹3,373 /sqft        1
₹10,555 /sqft       1
₹6,470 /sqft        1
₹6,743 /sqft        1
₹2,140 /sqft        1
₹6,578 /sqft        1
₹5,670 /sqft        1
₹4,593 /sqft        1
₹2,851 /sqft        1
₹3,631 /sqft        1
₹5,818 /sqft        1
₹2,663 /sqft        1
₹16,363 /sqft       1
₹4,212 /sqft        1
₹4,126 /sqft        1
₹11,363 /sqft       1
₹5,468 /sqft        1
₹3,609 /sqft        1
₹5,760 /sqft        1
₹3,717 /sqft        1
₹12,475 /sqft       1
₹9,800 /sqft        1
₹4,782 /sqft        1
₹3,423 /sqft        1
₹2,806 /sqft        1
₹5,975 /sqft        1
₹5,600 /sqft        1
₹3,287 /sqft        1
₹2,519 /sqft        1
₹4,318 /sqft        1
₹5,753 /sqft        1
₹5,748 /sqft        1
₹5,730 /sqft        1
₹6,165 /sqft        1
₹5,785 /sqft        1
₹10,057 /sqft       1
₹13,872 /sqft       1
₹4,187 /sqft        1
₹3,708 /sqft        1
₹2,687 /sqft        1
₹9,237 /sqft        1
₹3,883 /sqft        1
₹10,434 /sqft       1
₹3,527 /sqft        1
Name: count, dtype: int64

In [136]:
t["price_per_sqft"] = t["price_per_sqft"].str.replace("₹","").str.replace(",","").str.replace("/sqft","").astype('int')

In [137]:
t.head()

,pname,society,price_outer,price_per_sqft,possesion,description,Area,Configuration,Price,Address,Floor Number,Facing,Property Age,furnishing,features,ratings,Overlooking,Possession in
0,"3 BHK Flat in Shahpura, Bhopal",green heights,75.0,6000,Ready To Move,"Situated in shahpura, bhopal, green heights is...",Carpet area: 1250\n(116.13 sq.m.) \nsq.ft.,"3 Bedrooms , 3 Bathrooms, 2 Balconies","₹ 75 Lac\n@ 6,000 per sq.ft. (Negotiable) View...","Green Heights\nShahpura, Bhopal",1st of 6 Floors,East,5 to 10 Year Old,"['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '3 Ge...","['Feng Shui / Vaastu Compliant', 'Security / F...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]",NaN,NaN
1,"3 BHK Flat in MP Nagar, Bhopal",keelandev apartments,185.0,10481,Ready To Move,For sale 3.5 bhk flat kilandev tower shivaji n...,Super Built up area 1765\n(163.97 sq.m.) \nsq...,"3 Bedrooms , 3 Bathrooms, 2 Balconies with Ser...","₹ 1.85 Crore+ Govt Charges & Tax\n@ 10,481 per...","Keelandev Apartments\nMP Nagar, Bhopal",5th of 10 Floors,North-West,1 to 5 Year Old,"['2 Wardrobe', '3 Fan', '1 Exhaust Fan', '2 Ge...","['Intercom Facility', 'Lift(s)', 'Maintenance ...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]",Main Road,NaN
2,"2 BHK Flat in New Central Jail, Bhopal",satya prakash nice space,35.0,2788,Ready To Move,Luxurious 2 bhk apartment with all the modern ...,Super Built up area 1255\n(116.59 sq.m.)\nBuil...,"2 Bedrooms , 2 Bathrooms, 3 Balconies","₹ 35 Lac+ Govt Charges & Tax\n@ 2,788 per sq.f...","Satya Prakash Nice Space\n, Bhopal",3rd of 8 Floors,West,1 to 5 Year Old,NaN,"['Security / Fire Alarm', 'Power Back-up', 'Fe...",[],"Park/Garden,Club,Pool,Main Road",NaN
3,"3 BHK Flat in Hoshangabad Road, Bhopal",lakhumal nikhil nestles,48.0,2953,Ready To Move,"Situated in hoshangabad road, bhopal, lakhumal...",Super Built up area 1625\n(150.97 sq.m.)\nBuil...,"3 Bedrooms , 3 Bathrooms, 3 Balconies with Poo...","₹ 48 Lac+ Govt Charges & Tax\n@ 2,953 per sq.f...","Lakhumal Nikhil Nestles\nHoshangabad Road, Bhopal",1st of 6 Floors,South-West,1 to 5 Year Old,"['1 Water Purifier', '1 Fridge', '6 Fan', '1 E...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}, {'': ...","Park/Garden,Club,Main Road,Others,Sea facing",NaN
4,"2 BHK Flat in Sanjeev Nagar, Bhopal",ripl maple tree,33.0,3038,Ready To Move,Luxurious 2 bhk apartment with all the modern ...,Super Built up area 1086\n(100.89 sq.m.) \nsq...,"2 Bedrooms , 2 Bathrooms, 1 Balcony","₹ 33 Lac+ Govt Charges & Tax\n@ 3,038 per sq.f...","RIPL Maple Tree\nSanjeev Nagar, Bhopal",5th of 7 Floors,East,5 to 10 Year Old,"['2 Wardrobe', '2 Bed', '1 Water Purifier', '4...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]","Park/Garden,Club,Main Road",NaN

# Possesion

In [138]:
t['possesion'].value_counts()

possesion
Ready To Move         758
Under Construction     24
Name: count, dtype: int64

# Configuration

In [139]:
t['Configuration'].value_counts()

Configuration
2 Bedrooms , 2 Bathrooms, 1 Balcony                                                                      119
2 Bedrooms , 2 Bathrooms, 2 Balconies                                                                     89
3 Bedrooms , 2 Bathrooms, 2 Balconies                                                                     66
3 Bedrooms , 2 Bathrooms, 1 Balcony                                                                       61
3 Bedrooms , 3 Bathrooms, 2 Balconies                                                                     47
2 Bedrooms , 1 Bathroom, 1 Balcony                                                                        30
3 Bedrooms , 2 Bathrooms, 3 Balconies                                                                     29
1 Bedroom , 1 Bathroom, 1 Balcony                                                                         27
3 Bedrooms , 3 Bathrooms, 3 Balconies                                                                     26
2 Bedrooms , 2 Bathrooms, No Balcony                                                                      26
2 Bedrooms , 2 Bathrooms, 3 Balconies                                                                     16
1 Bedroom , 1 Bathroom, No Balcony                                                                        13
3 Bedrooms , 2 Bathrooms, No Balcony                                                                      11
3 Bedrooms , 3 Bathrooms, 1 Balcony                                                                        8
2 Bedrooms , 2 Bathrooms, 2 Balconies\nView Floor Plan                                                     7
4 Bedrooms , 3 Bathrooms, 3 Balconies                                                                      6
2 Bedrooms , 1 Bathroom, 2 Balconies                                                                       6
3 Bedrooms , 3 Bathrooms, No Balcony                                                                       6
3 Bedrooms , 2 Bathrooms, 2 Balconies with Others                                                          5
1 Bedroom , 1 Bathroom, 2 Balconies                                                                        5
2 Bedrooms , 1 Bathroom, No Balcony                                                                        5
3 Bedrooms , 2 Bathrooms, 1 Balcony\nView Floor Plan                                                       4
3 Bedrooms , 2 Bathrooms, 1 Balcony with Others                                                            4
2 Bedrooms , 2 Bathrooms, 2 Balconies with Others                                                          4
3 Bedrooms , 2 Bathrooms, 2 Balconies\nView Floor Plan                                                     4
3 Bedrooms , 3 Bathrooms, 2 Balconies with Others                                                          4
4 Bedrooms , 3 Bathrooms, 1 Balcony                                                                        4
4 Bedrooms , 4 Bathrooms, 3 Balconies                                                                      4
1 Bedroom , 1 Bathroom, 1 Balcony with Others                                                              3
3 Bedrooms , 2 Bathrooms, 2 Balconies with Pooja Room                                                      3
3 Bedrooms , 3 Bathrooms, 3+ Balconies                                                                     3
4 Bedrooms , 3 Bathrooms, 2 Balconies                                                                      3
2 Bedrooms , 2 Bathrooms, 1 Balcony with Others                                                            3
4 Bedrooms , 4 Bathrooms, 2 Balconies with Servant Room                                                    3
3 Bedrooms , 3 Bathrooms, 2 Balconies\nView Floor Plan                                                     3
3 Bedrooms , 3 Bathrooms, 2 Balconies with Servant Room                                                    3
4 Bedrooms , 3 Bathrooms, No Balcony                                                                       2
5 Bedrooms , 4 Bathrooms, 3 Balconies                                                                      2
3 Bedrooms , 3 Bathrooms, 3 Balconies with Store Room                                                      2
3 Bedrooms , 3 Bathrooms, 3+ Balconies with Pooja Room                                                     2
3 Bedrooms , 2 Bathrooms, 2 Balconies with Store Room                                                      2
4 Bedrooms , 4 Bathrooms, 3+ Balconies                                                                     2
1 Bedroom , 1 Bathroom, 1 Balcony with Pooja Room                                                          2
3 Bedrooms , 2 Bathrooms, 1 Balcony with Study Room                                                        2
3 Bedrooms , 3 Bathrooms, 3 Balconies with Others                                                          2
3 Bedrooms , 1 Bathroom, No Balcony                                                                        2
3 Bedrooms , 3 Bathrooms, 2 Balconies with Pooja Room,Store Room,Study Room,Servant Room                   2
3 Bedrooms , 3 Bathrooms, 2 Balconies with Study Room                                                      2
2 Bedrooms , 2 Bathrooms, 1 Balcony\nView Floor Plan                                                       2
2 Bedrooms , 3 Bathrooms, 2 Balconies with Pooja Room                                                      2
4 Bedrooms , 4 Bathrooms, No Balcony                                                                       2
4 Bedrooms , 4 Bathrooms, 2 Balconies                                                                      2
3 Bedrooms , 3 Bathrooms, 2 Balconies with Pooja Room                                                      2
3 Bedrooms , 2 Bathrooms, 2 Balconies with Pooja Room,Study Room                                           2
2 Bedrooms , 2 Bathrooms, 2 Balconies with Pooja Room                                                      2
2 Bedrooms , 2 Bathrooms, 1 Balcony with Study Room                                                        2
3 Bedrooms , 3 Bathrooms, 3 Balconies with Pooja Room,Study Room                                           2
2 Bedrooms , 1 Bathroom, 1 Balcony\nView Floor Plan                                                        2
4 Bedrooms , 4 Bathrooms, 1 Balcony                                                                        2
2 Bedrooms , 2 Bathrooms, 2 Balconies with Pooja Room,Others                                               2
2 Bedrooms , 2 Bathrooms, 3 Balconies\nView Floor Plan                                                     2
3 Bedrooms , 2 Bathrooms, 3 Balconies with Others                                                          1
3 Bedrooms , 3 Bathrooms, 1 Balcony with Study Room                                                        1
3 Bedrooms , 3 Bathrooms, 2 Balconies with Study Room,Pooja Room                                           1
2 Bedrooms , 1 Bathroom, 3 Balconies                                                                       1
3 Bedrooms , 4 Bathrooms, 3 Balconies with Servant Room                                                    1
3 Bedrooms , 3 Bathrooms, 3 Balconies\nView Floor Plan                                                     1
4 Bedrooms , 4 Bathrooms, 2 Balconies with Pooja Room,Servant Room                                         1
3 Bedrooms , 2 Bathrooms, 3+ Balconies                                                                     1
4 Bedrooms , 2 Bathrooms, 1 Balcony                                                                        1
3 Bedrooms , 4 Bathrooms, 3+ Balconies with Servant Room                                                   1
3 Bedrooms , 4 Bathrooms, 3+ Balconies with Servant Room\nView Floor Plan                                  1
2 Bedrooms , 2 Bathrooms, 2 Balconies with Pooja Room,Study Room,Others\nView Floor Plan                   1
3 Bedrooms , 2 Bathrooms, 2 Balconies with Study Room                                                      1
13 Bedrooms , 14 Bathrooms, 2 Balconies with Servant Room                                                  1
4 Bedrooms , 4 Bathrooms, 2 Balconies with Pooja Room,Others\nView Floor Plan                              1
4 Bedrooms , 4 Bathrooms, 3 Balconies\nView Floor Plan                                                     1
3 Bedrooms , 1 Bathroom, 1 Balcony                                                                         1
3 Bedrooms , 2 Bathrooms, 3 Balconies with Pooja Room                                                      1
3 Bedrooms , 3 Bathrooms, 2 Balconies with Store Room\nView Floor Plan                                     1
2 Bedrooms , 2 Bathrooms, 1 Balcony with Pooja Room                                                        1
1 Bedroom , 2 Bathrooms, 2 Balconies                                                                       1
4 Bedrooms , 4 Bathrooms, 2 Balconies\nView Floor Plan                                                     1
4 Bedrooms , 3 Bathrooms, 3+ Balconies                                                                     1
3 Bedrooms , 3 Bathrooms, 3 Balconies with Pooja Room,Servant Room,Study Room,Others                       1
4 Bedrooms , 5 Bathrooms, 3+ Balconies with Servant Room                                                   1
1 Bedroom , 2 Bathrooms, 2 Balconies with Pooja Room                                                       1
4 Bedrooms , 2 Bathrooms, 2 Balconies                                                                      1
3 Bedrooms , 4 Bathrooms, 2 Balconies                                                                      1
3 Bedrooms , 3 Bathrooms, 1 Balcony\nView Floor Plan                                                       1
5 Bedrooms , 4 Bathrooms, 2 Balconies                                                                      1
3 Bedrooms , 2 Bathrooms, 1 Balcony with Pooja Room                                                        1
4 Bedrooms , 3 Bathrooms, 1 Balcony with Pooja Room,Study Room,Others\nView Floor Plan                     1
4 Bedrooms , 5 Bathrooms, 3+ Balconies with Study Room,Servant Room                                        1
2 Bedrooms , 3 Bathrooms, 2 Balconies                                                                      1
4 Bedrooms , 4 Bathrooms, 3+ Balconies with Pooja Room,Servant Room,Study Room,Others                      1
5 Bedrooms , 5 Bathrooms, 2 Balconies                                                                      1
2 Bedrooms , 2 Bathrooms, 1 Balcony with Servant Room                                                      1
3 Bedrooms , 3 Bathrooms, 3 Balconies with Servant Room                                                    1
3 Bedrooms , 4 Bathrooms, 1 Balcony with Servant Room                                                      1
2 Bedrooms , 2 Bathrooms, 3 Balconies with Others,Pooja Room                                               1
3 Bedrooms , 4 Bathrooms, 2 Balconies with Servant Room                                                    1
3 Bedrooms , 3 Bathrooms, 2 Balconies with Pooja Room,Study Room,Others,Servant Room\nView Floor Plan      1
3 Bedrooms , 3 Bathrooms, 2 Balconies with Pooja Room,Study Room,Servant Room,Others                       1
4 Bedrooms , 4 Bathrooms, 2 Balconies with Study Room                                                      1
3 Bedrooms , 1 Bathroom, 3 Balconies with Pooja Room,Others                                                1
3 Bedrooms , 3 Bathrooms, 2 Balconies with Pooja Room,Others                                               1
2 Bedrooms , 2 Bathrooms, 2 Balconies with Pooja Room,Study Room,Others,Servant Room                       1
4 Bedrooms , 5 Bathrooms, 3 Balconies with Servant Room                                                    1
2 Bedrooms , 2 Bathrooms, 1 Balcony with Pooja Room,Study Room                                             1
4 Bedrooms , 3 Bathrooms, 2 Balconies with Pooja Room,Servant Room                                         1
3 Bedrooms , 2 Bathrooms, 3 Balconies\nView Floor Plan                                                     1
4 Bedrooms , 4 Bathrooms, 1 Balcony with Others                                                            1
5 Bedrooms , 5 Bathrooms, 3+ Balconies with Pooja Room,Study Room,Servant Room                             1
3 Bedrooms , 3 Bathrooms, 1 Balcony with Pooja Room\nView Floor Plan                                       1
3 Bedrooms , 3 Bathrooms, 2 Balconies with Pooja Room,Servant Room,Study Room,Others                       1
4 Bedrooms , 4 Bathrooms, 3+ Balconies with Study Room,Others,Pooja Room                                   1
2 Bedrooms , 1 Bathroom, 1 Balcony with Others                                                             1
4 Bedrooms , 4 Bathrooms, 3+ Balconies with Pooja Room,Servant Room                                        1
4 Bedrooms , 3 Bathrooms, 3 Balconies with Others                                                          1
3 Bedrooms , 2 Bathrooms, 2 Balconies with Pooja Room,Study Room,Servant Room,Others                       1
3 Bedrooms , 3 Bathrooms, 3+ Balconies\nView Floor Plan                                                    1
3 Bedrooms , 4 Bathrooms, 2 Balconies with Others                                                          1
3 Bedrooms , 2 Bathrooms, 2 Balconies with Pooja Room,Study Room,Store Room                                1
3 Bedrooms , 3 Bathrooms, 2 Balconies with Store Room                                                      1
5 Bedrooms , 5 Bathrooms, 2 Balconies with Pooja Room                                                      1
6 Bedrooms , 8 Bathrooms, 3+ Balconies with Pooja Room,Servant Room,Study Room,Others                      1
3 Bedrooms , 4 Bathrooms, 2 Balconies with Servant Room,Store Room                                         1
3 Bedrooms , 3 Bathrooms, 2 Balconies with Study Room,Pooja Room,Servant Room,Others                       1
2 Bedrooms , 2 Bathrooms, 1 Balcony with Pooja Room,Others                                                 1
4 Bedrooms , 4 Bathrooms, 3 Balconies with Pooja Room,Servant Room,Study Room,Others                       1
3 Bedrooms , 4 Bathrooms, 3 Balconies with Pooja Room,Servant Room,Study Room,Others                       1
1 Bedroom , 2 Bathrooms, 1 Balcony                                                                         1
Name: count, dtype: int64

In [140]:
t['Configuration'] = t['Configuration'].str.replace(
    r'\nView Floor Plan',
    ' with View Floor Plan',
    regex=True
)


config_split = t['Configuration'].str.split('with',n=1,expand=True)
rooms = config_split[0].str.split(",",expand=True)

In [141]:
t[['bedrooms','bathrooms','balconies']] = rooms.rename(columns={0:"bedrooms",1:"bathrooms",2:"balconies"})

In [142]:
t.head()

,pname,society,price_outer,price_per_sqft,possesion,description,Area,Configuration,Price,Address,Floor Number,Facing,Property Age,furnishing,features,ratings,Overlooking,Possession in,bedrooms,bathrooms,balconies
0,"3 BHK Flat in Shahpura, Bhopal",green heights,75.0,6000,Ready To Move,"Situated in shahpura, bhopal, green heights is...",Carpet area: 1250\n(116.13 sq.m.) \nsq.ft.,"3 Bedrooms , 3 Bathrooms, 2 Balconies","₹ 75 Lac\n@ 6,000 per sq.ft. (Negotiable) View...","Green Heights\nShahpura, Bhopal",1st of 6 Floors,East,5 to 10 Year Old,"['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '3 Ge...","['Feng Shui / Vaastu Compliant', 'Security / F...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]",NaN,NaN,3 Bedrooms,3 Bathrooms,2 Balconies
1,"3 BHK Flat in MP Nagar, Bhopal",keelandev apartments,185.0,10481,Ready To Move,For sale 3.5 bhk flat kilandev tower shivaji n...,Super Built up area 1765\n(163.97 sq.m.) \nsq...,"3 Bedrooms , 3 Bathrooms, 2 Balconies with Ser...","₹ 1.85 Crore+ Govt Charges & Tax\n@ 10,481 per...","Keelandev Apartments\nMP Nagar, Bhopal",5th of 10 Floors,North-West,1 to 5 Year Old,"['2 Wardrobe', '3 Fan', '1 Exhaust Fan', '2 Ge...","['Intercom Facility', 'Lift(s)', 'Maintenance ...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]",Main Road,NaN,3 Bedrooms,3 Bathrooms,2 Balconies
2,"2 BHK Flat in New Central Jail, Bhopal",satya prakash nice space,35.0,2788,Ready To Move,Luxurious 2 bhk apartment with all the modern ...,Super Built up area 1255\n(116.59 sq.m.)\nBuil...,"2 Bedrooms , 2 Bathrooms, 3 Balconies","₹ 35 Lac+ Govt Charges & Tax\n@ 2,788 per sq.f...","Satya Prakash Nice Space\n, Bhopal",3rd of 8 Floors,West,1 to 5 Year Old,NaN,"['Security / Fire Alarm', 'Power Back-up', 'Fe...",[],"Park/Garden,Club,Pool,Main Road",NaN,2 Bedrooms,2 Bathrooms,3 Balconies
3,"3 BHK Flat in Hoshangabad Road, Bhopal",lakhumal nikhil nestles,48.0,2953,Ready To Move,"Situated in hoshangabad road, bhopal, lakhumal...",Super Built up area 1625\n(150.97 sq.m.)\nBuil...,"3 Bedrooms , 3 Bathrooms, 3 Balconies with Poo...","₹ 48 Lac+ Govt Charges & Tax\n@ 2,953 per sq.f...","Lakhumal Nikhil Nestles\nHoshangabad Road, Bhopal",1st of 6 Floors,South-West,1 to 5 Year Old,"['1 Water Purifier', '1 Fridge', '6 Fan', '1 E...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}, {'': ...","Park/Garden,Club,Main Road,Others,Sea facing",NaN,3 Bedrooms,3 Bathrooms,3 Balconies
4,"2 BHK Flat in Sanjeev Nagar, Bhopal",ripl maple tree,33.0,3038,Ready To Move,Luxurious 2 bhk apartment with all the modern ...,Super Built up area 1086\n(100.89 sq.m.) \nsq...,"2 Bedrooms , 2 Bathrooms, 1 Balcony","₹ 33 Lac+ Govt Charges & Tax\n@ 3,038 per sq.f...","RIPL Maple Tree\nSanjeev Nagar, Bhopal",5th of 7 Floors,East,5 to 10 Year Old,"['2 Wardrobe', '2 Bed', '1 Water Purifier', '4...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]","Park/Garden,Club,Main Road",NaN,2 Bedrooms,2 Bathrooms,1 Balcony

In [143]:
t['additional_room'] = config_split[1]

In [144]:
t.head()

,pname,society,price_outer,price_per_sqft,possesion,description,Area,Configuration,Price,Address,Floor Number,Facing,Property Age,furnishing,features,ratings,Overlooking,Possession in,bedrooms,bathrooms,balconies,additional_room
0,"3 BHK Flat in Shahpura, Bhopal",green heights,75.0,6000,Ready To Move,"Situated in shahpura, bhopal, green heights is...",Carpet area: 1250\n(116.13 sq.m.) \nsq.ft.,"3 Bedrooms , 3 Bathrooms, 2 Balconies","₹ 75 Lac\n@ 6,000 per sq.ft. (Negotiable) View...","Green Heights\nShahpura, Bhopal",1st of 6 Floors,East,5 to 10 Year Old,"['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '3 Ge...","['Feng Shui / Vaastu Compliant', 'Security / F...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]",NaN,NaN,3 Bedrooms,3 Bathrooms,2 Balconies,None
1,"3 BHK Flat in MP Nagar, Bhopal",keelandev apartments,185.0,10481,Ready To Move,For sale 3.5 bhk flat kilandev tower shivaji n...,Super Built up area 1765\n(163.97 sq.m.) \nsq...,"3 Bedrooms , 3 Bathrooms, 2 Balconies with Ser...","₹ 1.85 Crore+ Govt Charges & Tax\n@ 10,481 per...","Keelandev Apartments\nMP Nagar, Bhopal",5th of 10 Floors,North-West,1 to 5 Year Old,"['2 Wardrobe', '3 Fan', '1 Exhaust Fan', '2 Ge...","['Intercom Facility', 'Lift(s)', 'Maintenance ...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]",Main Road,NaN,3 Bedrooms,3 Bathrooms,2 Balconies,Servant Room
2,"2 BHK Flat in New Central Jail, Bhopal",satya prakash nice space,35.0,2788,Ready To Move,Luxurious 2 bhk apartment with all the modern ...,Super Built up area 1255\n(116.59 sq.m.)\nBuil...,"2 Bedrooms , 2 Bathrooms, 3 Balconies","₹ 35 Lac+ Govt Charges & Tax\n@ 2,788 per sq.f...","Satya Prakash Nice Space\n, Bhopal",3rd of 8 Floors,West,1 to 5 Year Old,NaN,"['Security / Fire Alarm', 'Power Back-up', 'Fe...",[],"Park/Garden,Club,Pool,Main Road",NaN,2 Bedrooms,2 Bathrooms,3 Balconies,None
3,"3 BHK Flat in Hoshangabad Road, Bhopal",lakhumal nikhil nestles,48.0,2953,Ready To Move,"Situated in hoshangabad road, bhopal, lakhumal...",Super Built up area 1625\n(150.97 sq.m.)\nBuil...,"3 Bedrooms , 3 Bathrooms, 3 Balconies with Poo...","₹ 48 Lac+ Govt Charges & Tax\n@ 2,953 per sq.f...","Lakhumal Nikhil Nestles\nHoshangabad Road, Bhopal",1st of 6 Floors,South-West,1 to 5 Year Old,"['1 Water Purifier', '1 Fridge', '6 Fan', '1 E...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}, {'': ...","Park/Garden,Club,Main Road,Others,Sea facing",NaN,3 Bedrooms,3 Bathrooms,3 Balconies,"Pooja Room,Servant Room,Study Room,Others"
4,"2 BHK Flat in Sanjeev Nagar, Bhopal",ripl maple tree,33.0,3038,Ready To Move,Luxurious 2 bhk apartment with all the modern ...,Super Built up area 1086\n(100.89 sq.m.) \nsq...,"2 Bedrooms , 2 Bathrooms, 1 Balcony","₹ 33 Lac+ Govt Charges & Tax\n@ 3,038 per sq.f...","RIPL Maple Tree\nSanjeev Nagar, Bhopal",5th of 7 Floors,East,5 to 10 Year Old,"['2 Wardrobe', '2 Bed', '1 Water Purifier', '4...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]","Park/Garden,Club,Main Road",NaN,2 Bedrooms,2 Bathrooms,1 Balcony,None

# Bedrooms

In [145]:
t['bedrooms'].value_counts()

bedrooms
3 Bedrooms      343
2 Bedrooms      329
1 Bedroom        53
4 Bedrooms       49
5 Bedrooms        6
6 Bedrooms        1
13 Bedrooms       1
Name: count, dtype: int64

In [146]:
t['bedrooms'] = t['bedrooms'].str.replace('Bedrooms',"").str.replace('Bedroom',"").astype('int')

In [147]:
t['bedrooms'].value_counts()

bedrooms
3     343
2     329
1      53
4      49
5       6
6       1
13      1
Name: count, dtype: int64

# Bathrooms

In [148]:
t['bathrooms'].value_counts()

bathrooms
 2 Bathrooms     487
 3 Bathrooms     151
 1 Bathroom       99
 4 Bathrooms      37
 5 Bathrooms       6
 8 Bathrooms       1
 14 Bathrooms      1
Name: count, dtype: int64

In [149]:
t['bathrooms'] = t['bathrooms'].str.replace('Bathrooms',"").str.replace("Bathroom","").astype('int')

In [150]:
t['bathrooms'].value_counts()

bathrooms
2     487
3     151
1      99
4      37
5       6
8       1
14      1
Name: count, dtype: int64

# Balconies

In [151]:
t['balconies'].value_counts()

balconies
 1 Balcony        254
 2 Balconies      224
 3 Balconies       84
 2 Balconies       76
 No Balcony        67
 1 Balcony         36
 3 Balconies       22
 3+ Balconies      12
 3+ Balconies       7
Name: count, dtype: int64

In [152]:
t['balconies'] =  t['balconies'].str.replace('Balcony',"").str.replace('Balconies',"").str.strip().str.replace('\nView Floor Plan',"").str.replace("No","0").str.replace("3+","3").astype('int')

In [153]:
t['balconies'].value_counts()

balconies
2    300
1    290
3    125
0     67
Name: count, dtype: int64

# additional rooms

In [154]:
t['additional_room'].value_counts()

additional_room
 Others                                                            30
 View Floor Plan                                                   30
 Pooja Room                                                        18
 Servant Room                                                      15
 Study Room                                                         9
 Pooja Room,Servant Room,Study Room,Others                          6
 Pooja Room,Others                                                  5
 Store Room                                                         5
 Pooja Room,Study Room                                              5
 Pooja Room,Servant Room                                            3
 Pooja Room,Study Room,Servant Room,Others                          2
 Pooja Room,Study Room,Others with View Floor Plan                  2
 Pooja Room,Store Room,Study Room,Servant Room                      2
 Servant Room,Store Room                                            1
 Study Room,Others,Pooja Room                                       1
 Pooja Room,Others with View Floor Plan                             1
 Servant Room with View Floor Plan                                  1
 Study Room,Servant Room                                            1
 Study Room,Pooja Room,Servant Room,Others                          1
 Pooja Room,Study Room,Servant Room                                 1
 Pooja Room with View Floor Plan                                    1
 Pooja Room,Study Room,Store Room                                   1
 Others,Pooja Room                                                  1
 Pooja Room,Study Room,Others,Servant Room                          1
 Study Room,Pooja Room                                              1
 Pooja Room,Study Room,Others,Servant Room with View Floor Plan     1
 Store Room with View Floor Plan                                    1
Name: count, dtype: int64

In [155]:
t['additional_room'] = t['additional_room'].str.lower().fillna('Not Available')

In [156]:
t.head()

,pname,society,price_outer,price_per_sqft,possesion,description,Area,Configuration,Price,Address,Floor Number,Facing,Property Age,furnishing,features,ratings,Overlooking,Possession in,bedrooms,bathrooms,balconies,additional_room
0,"3 BHK Flat in Shahpura, Bhopal",green heights,75.0,6000,Ready To Move,"Situated in shahpura, bhopal, green heights is...",Carpet area: 1250\n(116.13 sq.m.) \nsq.ft.,"3 Bedrooms , 3 Bathrooms, 2 Balconies","₹ 75 Lac\n@ 6,000 per sq.ft. (Negotiable) View...","Green Heights\nShahpura, Bhopal",1st of 6 Floors,East,5 to 10 Year Old,"['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '3 Ge...","['Feng Shui / Vaastu Compliant', 'Security / F...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]",NaN,NaN,3,3,2,Not Available
1,"3 BHK Flat in MP Nagar, Bhopal",keelandev apartments,185.0,10481,Ready To Move,For sale 3.5 bhk flat kilandev tower shivaji n...,Super Built up area 1765\n(163.97 sq.m.) \nsq...,"3 Bedrooms , 3 Bathrooms, 2 Balconies with Ser...","₹ 1.85 Crore+ Govt Charges & Tax\n@ 10,481 per...","Keelandev Apartments\nMP Nagar, Bhopal",5th of 10 Floors,North-West,1 to 5 Year Old,"['2 Wardrobe', '3 Fan', '1 Exhaust Fan', '2 Ge...","['Intercom Facility', 'Lift(s)', 'Maintenance ...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]",Main Road,NaN,3,3,2,servant room
2,"2 BHK Flat in New Central Jail, Bhopal",satya prakash nice space,35.0,2788,Ready To Move,Luxurious 2 bhk apartment with all the modern ...,Super Built up area 1255\n(116.59 sq.m.)\nBuil...,"2 Bedrooms , 2 Bathrooms, 3 Balconies","₹ 35 Lac+ Govt Charges & Tax\n@ 2,788 per sq.f...","Satya Prakash Nice Space\n, Bhopal",3rd of 8 Floors,West,1 to 5 Year Old,NaN,"['Security / Fire Alarm', 'Power Back-up', 'Fe...",[],"Park/Garden,Club,Pool,Main Road",NaN,2,2,3,Not Available
3,"3 BHK Flat in Hoshangabad Road, Bhopal",lakhumal nikhil nestles,48.0,2953,Ready To Move,"Situated in hoshangabad road, bhopal, lakhumal...",Super Built up area 1625\n(150.97 sq.m.)\nBuil...,"3 Bedrooms , 3 Bathrooms, 3 Balconies with Poo...","₹ 48 Lac+ Govt Charges & Tax\n@ 2,953 per sq.f...","Lakhumal Nikhil Nestles\nHoshangabad Road, Bhopal",1st of 6 Floors,South-West,1 to 5 Year Old,"['1 Water Purifier', '1 Fridge', '6 Fan', '1 E...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}, {'': ...","Park/Garden,Club,Main Road,Others,Sea facing",NaN,3,3,3,"pooja room,servant room,study room,others"
4,"2 BHK Flat in Sanjeev Nagar, Bhopal",ripl maple tree,33.0,3038,Ready To Move,Luxurious 2 bhk apartment with all the modern ...,Super Built up area 1086\n(100.89 sq.m.) \nsq...,"2 Bedrooms , 2 Bathrooms, 1 Balcony","₹ 33 Lac+ Govt Charges & Tax\n@ 3,038 per sq.f...","RIPL Maple Tree\nSanjeev Nagar, Bhopal",5th of 7 Floors,East,5 to 10 Year Old,"['2 Wardrobe', '2 Bed', '1 Water Purifier', '4...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]","Park/Garden,Club,Main Road",NaN,2,2,1,Not Available

In [167]:
t['Floor Number'].value_counts()

Floor Number
4th   of 6 Floors           53
5th   of 6 Floors           52
2nd   of 6 Floors           51
6th   of 6 Floors           41
3rd   of 6 Floors           40
3rd   of 3 Floors           37
2nd   of 3 Floors           36
1st   of 6 Floors           35
1st   of 3 Floors           30
2nd   of 4 Floors           29
1st   of 4 Floors           28
3rd   of 4 Floors           24
4th   of 4 Floors           18
6th   of 7 Floors           17
2nd   of 2 Floors           15
2nd   of 7 Floors           15
4th   of 7 Floors           14
5th   of 5 Floors           14
1st   of 1 Floors           13
5th   of 7 Floors           13
Ground of 3 Floors          12
Ground of 1 Floors          11
3rd   of 7 Floors           10
1st   of 2 Floors           10
Ground of 2 Floors          10
3rd   of 5 Floors            9
Ground of 6 Floors           9
4th   of 5 Floors            8
Ground of 4 Floors           8
1st   of 5 Floors            8
5th   of 8 Floors            7
1st   of 7 Floors            6
4th   of 8 Floors            6
2nd   of 5 Floors            6
7th   of 12 Floors           5
5th   of 10 Floors           5
8th   of 8 Floors            4
6th   of 8 Floors            4
Ground of 5 Floors           4
1st   of 8 Floors            3
1st   of 10 Floors           3
4th   of 10 Floors           3
6th   of 9 Floors            3
3rd   of 10 Floors           3
7th   of 7 Floors            3
3rd   of 8 Floors            3
9th   of 9 Floors            2
10th   of 10 Floors          2
7th   of 9 Floors            2
2nd   of 9 Floors            2
Ground of 7 Floors           2
2nd   of 8 Floors            2
8th   of 22 Floors           2
7th   of 8 Floors            2
11st   of 16 Floors          1
5th   of 11 Floors           1
5th   of 14 Floors           1
3rd   of 9 Floors            1
33rd   of 34 Floors          1
5th   of 9 Floors            1
Basement of 3 Floors         1
2nd   of 11 Floors           1
9th   of 16 Floors           1
Lower Ground of 2 Floors     1
Ground of 10 Floors          1
Ground of 8 Floors           1
9th   of 12 Floors           1
10th   of 22 Floors          1
13rd   of 22 Floors          1
Lower Ground of 6 Floors     1
8th   of 11 Floors           1
9th   of 10 Floors           1
15th   of 22 Floors          1
Ground of 0 Floors           1
8th   of 9 Floors            1
2nd   of 10 Floors           1
10th   of 17 Floors          1
3rd   of 13 Floors           1
9th   of 15 Floors           1
9th   of 11 Floors           1
1st   of 9 Floors            1
Lower Ground of 1 Floors     1
Name: count, dtype: int64

In [165]:
t['Floor_On'] = t['Floor Number'].str.extract(r'(\d+)(?:st|nd|rd|th)', expand=False).fillna(0).astype('int')

In [166]:
t['Total_Floors'] = (
    t['Floor Number']
    .str.extract(r'of\s+(\d+)', expand=False)
    .astype(int)
)

In [169]:
t['Total_Floors'].value_counts()

Total_Floors
6     282
3     116
4     107
7      80
5      49
2      36
8      32
1      25
10     19
9      13
12      6
22      5
11      4
16      2
14      1
0       1
17      1
13      1
15      1
34      1
Name: count, dtype: int64

# Facing

In [171]:
t['Facing'].value_counts()

Facing
East          198
North          71
West           62
North-East     25
South-West     12
South-East     10
North-West      8
South           5
Name: count, dtype: int64

In [172]:
t['Facing'].isnull().sum()

391

In [173]:
t['Facing'] = t['Facing'].fillna('NA')

In [174]:
t.head()

,pname,society,price_outer,price_per_sqft,possesion,description,Area,Configuration,Price,Address,Floor Number,Facing,Property Age,furnishing,features,ratings,Overlooking,Possession in,bedrooms,bathrooms,balconies,additional_room,Floor_On,Total_Floors
0,"3 BHK Flat in Shahpura, Bhopal",green heights,75.0,6000,Ready To Move,"Situated in shahpura, bhopal, green heights is...",Carpet area: 1250\n(116.13 sq.m.) \nsq.ft.,"3 Bedrooms , 3 Bathrooms, 2 Balconies","₹ 75 Lac\n@ 6,000 per sq.ft. (Negotiable) View...","Green Heights\nShahpura, Bhopal",1st of 6 Floors,East,5 to 10 Year Old,"['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '3 Ge...","['Feng Shui / Vaastu Compliant', 'Security / F...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]",NaN,NaN,3,3,2,Not Available,1,6
1,"3 BHK Flat in MP Nagar, Bhopal",keelandev apartments,185.0,10481,Ready To Move,For sale 3.5 bhk flat kilandev tower shivaji n...,Super Built up area 1765\n(163.97 sq.m.) \nsq...,"3 Bedrooms , 3 Bathrooms, 2 Balconies with Ser...","₹ 1.85 Crore+ Govt Charges & Tax\n@ 10,481 per...","Keelandev Apartments\nMP Nagar, Bhopal",5th of 10 Floors,North-West,1 to 5 Year Old,"['2 Wardrobe', '3 Fan', '1 Exhaust Fan', '2 Ge...","['Intercom Facility', 'Lift(s)', 'Maintenance ...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]",Main Road,NaN,3,3,2,servant room,5,10
2,"2 BHK Flat in New Central Jail, Bhopal",satya prakash nice space,35.0,2788,Ready To Move,Luxurious 2 bhk apartment with all the modern ...,Super Built up area 1255\n(116.59 sq.m.)\nBuil...,"2 Bedrooms , 2 Bathrooms, 3 Balconies","₹ 35 Lac+ Govt Charges & Tax\n@ 2,788 per sq.f...","Satya Prakash Nice Space\n, Bhopal",3rd of 8 Floors,West,1 to 5 Year Old,NaN,"['Security / Fire Alarm', 'Power Back-up', 'Fe...",[],"Park/Garden,Club,Pool,Main Road",NaN,2,2,3,Not Available,3,8
3,"3 BHK Flat in Hoshangabad Road, Bhopal",lakhumal nikhil nestles,48.0,2953,Ready To Move,"Situated in hoshangabad road, bhopal, lakhumal...",Super Built up area 1625\n(150.97 sq.m.)\nBuil...,"3 Bedrooms , 3 Bathrooms, 3 Balconies with Poo...","₹ 48 Lac+ Govt Charges & Tax\n@ 2,953 per sq.f...","Lakhumal Nikhil Nestles\nHoshangabad Road, Bhopal",1st of 6 Floors,South-West,1 to 5 Year Old,"['1 Water Purifier', '1 Fridge', '6 Fan', '1 E...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}, {'': ...","Park/Garden,Club,Main Road,Others,Sea facing",NaN,3,3,3,"pooja room,servant room,study room,others",1,6
4,"2 BHK Flat in Sanjeev Nagar, Bhopal",ripl maple tree,33.0,3038,Ready To Move,Luxurious 2 bhk apartment with all the modern ...,Super Built up area 1086\n(100.89 sq.m.) \nsq...,"2 Bedrooms , 2 Bathrooms, 1 Balcony","₹ 33 Lac+ Govt Charges & Tax\n@ 3,038 per sq.f...","RIPL Maple Tree\nSanjeev Nagar, Bhopal",5th of 7 Floors,East,5 to 10 Year Old,"['2 Wardrobe', '2 Bed', '1 Water Purifier', '4...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]","Park/Garden,Club,Main Road",NaN,2,2,1,Not Available,5,7

In [175]:
t['area'] = round(t['price_outer']*100000/t['price_per_sqft'],2)

In [176]:
t.head(2)

,pname,society,price_outer,price_per_sqft,possesion,description,Area,Configuration,Price,Address,Floor Number,Facing,Property Age,furnishing,features,ratings,Overlooking,Possession in,bedrooms,bathrooms,balconies,additional_room,Floor_On,Total_Floors,area
0,"3 BHK Flat in Shahpura, Bhopal",green heights,75.0,6000,Ready To Move,"Situated in shahpura, bhopal, green heights is...",Carpet area: 1250\n(116.13 sq.m.) \nsq.ft.,"3 Bedrooms , 3 Bathrooms, 2 Balconies","₹ 75 Lac\n@ 6,000 per sq.ft. (Negotiable) View...","Green Heights\nShahpura, Bhopal",1st of 6 Floors,East,5 to 10 Year Old,"['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '3 Ge...","['Feng Shui / Vaastu Compliant', 'Security / F...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]",NaN,NaN,3,3,2,Not Available,1,6,1250.0
1,"3 BHK Flat in MP Nagar, Bhopal",keelandev apartments,185.0,10481,Ready To Move,For sale 3.5 bhk flat kilandev tower shivaji n...,Super Built up area 1765\n(163.97 sq.m.) \nsq...,"3 Bedrooms , 3 Bathrooms, 2 Balconies with Ser...","₹ 1.85 Crore+ Govt Charges & Tax\n@ 10,481 per...","Keelandev Apartments\nMP Nagar, Bhopal",5th of 10 Floors,North-West,1 to 5 Year Old,"['2 Wardrobe', '3 Fan', '1 Exhaust Fan', '2 Ge...","['Intercom Facility', 'Lift(s)', 'Maintenance ...","[{'': ''}, {'': ''}, {'': ''}, {'': ''}]",Main Road,NaN,3,3,2,servant room,5,10,1765.1

In [177]:
t = t.drop(columns=['Configuration','Possession in','Price','Address','ratings'])

In [178]:
t.info()

<class 'pandas.core.frame.DataFrame'>
Index: 782 entries, 0 to 123
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pname            782 non-null    object
 1   society          779 non-null    object
 2   price_outer      782 non-null    float64
 3   price_per_sqft   782 non-null    int32
 4   possesion        782 non-null    object
 5   description      782 non-null    object
 6   Area             782 non-null    object
 7   Floor Number     782 non-null    object
 8   Facing           782 non-null    object
 9   Property Age     728 non-null    object
 10  furnishing       371 non-null    object
 11  features         568 non-null    object
 12  Overlooking      414 non-null    object
 13  bedrooms         782 non-null    int32
 14  bathrooms        782 non-null    int32
 15  balconies        782 non-null    int32
 16  additional_room  782 non-null    object
 17  Floor_On         782 non-null    int32
 18  Total_Floors     782 non-null    int32
 19  area             782 non-null    float64
dtypes: float64(2), int32(6), object(12)
memory usage: 110.0+ KB

In [179]:
t.head()

,pname,society,price_outer,price_per_sqft,possesion,description,Area,Floor Number,Facing,Property Age,furnishing,features,Overlooking,bedrooms,bathrooms,balconies,additional_room,Floor_On,Total_Floors,area
0,"3 BHK Flat in Shahpura, Bhopal",green heights,75.0,6000,Ready To Move,"Situated in shahpura, bhopal, green heights is...",Carpet area: 1250\n(116.13 sq.m.) \nsq.ft.,1st of 6 Floors,East,5 to 10 Year Old,"['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '3 Ge...","['Feng Shui / Vaastu Compliant', 'Security / F...",NaN,3,3,2,Not Available,1,6,1250.00
1,"3 BHK Flat in MP Nagar, Bhopal",keelandev apartments,185.0,10481,Ready To Move,For sale 3.5 bhk flat kilandev tower shivaji n...,Super Built up area 1765\n(163.97 sq.m.) \nsq...,5th of 10 Floors,North-West,1 to 5 Year Old,"['2 Wardrobe', '3 Fan', '1 Exhaust Fan', '2 Ge...","['Intercom Facility', 'Lift(s)', 'Maintenance ...",Main Road,3,3,2,servant room,5,10,1765.10
2,"2 BHK Flat in New Central Jail, Bhopal",satya prakash nice space,35.0,2788,Ready To Move,Luxurious 2 bhk apartment with all the modern ...,Super Built up area 1255\n(116.59 sq.m.)\nBuil...,3rd of 8 Floors,West,1 to 5 Year Old,NaN,"['Security / Fire Alarm', 'Power Back-up', 'Fe...","Park/Garden,Club,Pool,Main Road",2,2,3,Not Available,3,8,1255.38
3,"3 BHK Flat in Hoshangabad Road, Bhopal",lakhumal nikhil nestles,48.0,2953,Ready To Move,"Situated in hoshangabad road, bhopal, lakhumal...",Super Built up area 1625\n(150.97 sq.m.)\nBuil...,1st of 6 Floors,South-West,1 to 5 Year Old,"['1 Water Purifier', '1 Fridge', '6 Fan', '1 E...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","Park/Garden,Club,Main Road,Others,Sea facing",3,3,3,"pooja room,servant room,study room,others",1,6,1625.47
4,"2 BHK Flat in Sanjeev Nagar, Bhopal",ripl maple tree,33.0,3038,Ready To Move,Luxurious 2 bhk apartment with all the modern ...,Super Built up area 1086\n(100.89 sq.m.) \nsq...,5th of 7 Floors,East,5 to 10 Year Old,"['2 Wardrobe', '2 Bed', '1 Water Purifier', '4...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","Park/Garden,Club,Main Road",2,2,1,Not Available,5,7,1086.24

In [180]:
t.to_csv('bpl_flats_cleaned_l1.csv',index=False)
t.to_excel('bpl_flats_cleaned_l1.xlsx',index=False)