In [1182]:
import numpy as np
import pandas as pd
import re

In [1183]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [1184]:
df = pd.read_csv('BPL_merged_cleaned_l2.csv')

In [1185]:
df.sample(5)

,pname,society,property_type,price_outer,price_per_sqft,possesion,description,Area,Total Floors,Facing,Property Age,furnishing,features,Overlooking,bedrooms,bathrooms,balconies,additional_room,area
273,"2 BHK Flat in Vijay Nagar, Bhopal",mangalam apartment,Flat,23.0,3833,Ready To Move,Prime location in vijay nagar lalghati main ro...,Carpet area: 600\n(55.74 sq.m.) \nsq.ft.,1.0,NaN,10+ Year Old,"['3 Fan', '2 Geyser', '6 Light', '1 Modular Ki...",NaN,NaN,2,2,1,pooja room,600.05
1550,"4 Bedroom House for sale in Salaiya, Bhopal",salaiya,House,125.0,10416,Ready To Move,Interested to sell independent house/villa.Pla...,Plot area 1200\n(111.48 sq.m.) \nsq.ft.,2.0,NaN,1 to 5 Year Old,"['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN,NaN,4,3,2,Not Available,1200.08
372,"4 Bedroom House for sale in Nariyalkheda, Bhopal",nariyalkheda,House,35.0,4666,Ready To Move,This property is in ganesh nagar colony,Plot area 750\n(69.68 sq.m.) \nsq.ft.,2.0,NaN,5 to 10 Year Old,NaN,NaN,NaN,4,3,2,Not Available,750.11
892,"2 BHK Flat in Patel Nagar, Bhopal",archana balaji towers,Flat,25.0,2500,Ready To Move,We are the proud owners of this 2 bhk apartmen...,Super Built up area 1000\n(92.9 sq.m.) \nsq.ft.,2.0,NaN,5 to 10 Year Old,NaN,NaN,NaN,2,2,2,Not Available,1000.00
1449,"2 BHK Flat in Hoshangabad Road, Bhopal",fortune kasturi,Flat,35.0,2696,Ready To Move,This 2 bhk apartment is available for sale in ...,Super Built up area 1298\n(120.59 sq.m.) \nsq...,4.0,East,0 to 1 Year Old View Construction Status,"['1 Wardrobe', '1 Modular Kitchen', '1 Chimney...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","Pool,Club,Park/Garden,Main Road,Others,Sea facing",2,2,2,Not Available,1298.22

In [1186]:
df.shape

(1580, 19)

In [1187]:
df.duplicated().sum()

0

In [1188]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1580 entries, 0 to 1579
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pname            1580 non-null   object
 1   society          1576 non-null   object
 2   property_type    1580 non-null   object
 3   price_outer      1580 non-null   float64
 4   price_per_sqft   1580 non-null   int64
 5   possesion        1580 non-null   object
 6   description      1580 non-null   object
 7   Area             1580 non-null   object
 8   Total Floors     1546 non-null   float64
 9   Facing           876 non-null    object
 10  Property Age     1443 non-null   object
 11  furnishing       673 non-null    object
 12  features         1015 non-null   object
 13  Overlooking      792 non-null    object
 14  bedrooms         1580 non-null   int64
 15  bathrooms        1580 non-null   int64
 16  balconies        1580 non-null   int64
 17  additional_room  1580 non-null   object
 18  area             1580 non-null   float64
dtypes: float64(3), int64(4), object(12)
memory usage: 234.7+ KB

In [1189]:
df.isnull().sum()/df.shape[0]

pname              0.000000
society            0.002532
property_type      0.000000
price_outer        0.000000
price_per_sqft     0.000000
possesion          0.000000
description        0.000000
Area               0.000000
Total Floors       0.021519
Facing             0.445570
Property Age       0.086709
furnishing         0.574051
features           0.357595
Overlooking        0.498734
bedrooms           0.000000
bathrooms          0.000000
balconies          0.000000
additional_room    0.000000
area               0.000000
dtype: float64

In [1190]:
df['pname'].value_counts().shape

(681,)

In [1191]:
df['pname'].str.split('in').str.get(1)

0                        Jhagariya Khurd, Bhopal
1                             Kolar Road, Bhopal
2                           Katara Hills, Bhopal
3                         Gurunanak Pura, Bhopal
4                           Chuna Bhatti, Bhopal
5                             Kolar Road, Bhopal
6                              Bairagarh, Bhopal
7                               Jatkhedi, Bhopal
8                             Kolar Road, Bhopal
9                          Sukhi Sewania, Bhopal
10                           Semri Kalan, Bhopal
11                      Hoshangabad Road, Bhopal
12                           Bypass Road, Bhopal
13                          Katara Hills, Bhopal
14                      Hoshangabad Road, Bhopal
15                               Piplani, Bhopal
16                       Ayodhya Bypass , Bhopal
17                               Salaiya, Bhopal
18                             Awadhpuri, Bhopal
19                                 Semra, Bhopal
20                          Naveen nagar, Bhopal
21                          Chanakyapuri, Bhopal
22                      Hoshangabad Road, Bhopal
23                           Bagsewaniya, Bhopal
24                             Bairagarh, Bhopal
25                              Trilanga, Bhopal
26                           Bagsewaniya, Bhopal
27                                         Gandh
28                           Gulmohar G3, Bhopal
29                         Narayan Nagar, Bhopal
30                      Hoshangabad Road, Bhopal
31                                         Gandh
32                          Katara Hills, Bhopal
33                              Kalapani, Bhopal
34                       Ayodhya Bypass , Bhopal
35                          Katara Hills, Bhopal
36                              Laharpur, Bhopal
37                          Katara Hills, Bhopal
38                           Shirdipuram, Bhopal
39                          Lalita Nagar, Bhopal
40                   F-Sector,Kolar Road, Bhopal
41                         Kalpana Nagar, Bhopal
42                         Coach Factory, Bhopal
43                           Shirdipuram, Bhopal
44                       Ayodhya Bypass , Bhopal
45                            Kolar Road, Bhopal
46                               Neelbad, Bhopal
47                      Hoshangabad Road, Bhopal
48                             Indrapuri, Bhopal
49                      Hoshangabad Road, Bhopal
50                         Sanjeev Nagar, Bhopal
51                          Gomti Colony, Bhopal
52                     Sector C Shahpura, Bhopal
53                       Teela Jamalpura, Bhopal
54                       Teela Jamalpura, Bhopal
55                          Nehru Nagar , Bhopal
56                               JK Road, Bhopal
57                       Ayodhya Bypass , Bhopal
58                         Sanjeev Nagar, Bhopal
59                       Bharati Niketan, Bhopal
60                         Rajved Colony, Bhopal
61                              Jatkhedi, Bhopal
62                          Katara Hills, Bhopal
63                              Kohefiza, Bhopal
64                    Patel Nagar Colony, Bhopal
65                   Parthsarthy Enclave, Bhopal
66                                             F
67                           Gopal Nagar, Bhopal
68                           Saket Nagar, Bhopal
69                       Ayodhya Bypass , Bhopal
70                                Karond, Bhopal
71                               Khajuri, Bhopal
72                         Bawadia Kalan, Bhopal
73                             Awadhpuri, Bhopal
74                           Saket Nagar, Bhopal
75                         Ayodhya Nagar, Bhopal
76                   Parthsarthy Enclave, Bhopal
77                                 Kolar, Bhopal
78                                 Karod, Bhopal
79                                Misrod, Bhopal
80                          Arera Colony, Bhopal
81                             Awadhpuri, Bhopal
82                         Bawadia Kalan, Bhopal
83                      Hoshangabad Road, Bhopal
84                                         Gandh
85                             Awadhpuri, Bhopal
86                          Nehru Nagar , Bhopal
87                                Misrod, Bhopal
88                              Shahpura, Bhopal
89                               Bhanpur, Bhopal
90              Narela jod Ayodhya bypass bhopal
91               noor mahal ashok colony, Bhopal
92                         Malviya Nagar, Bhopal
93                             Dam Kheda, Bhopal
94                            Lambakheda, Bhopal
95                               Ratibad, Bhopal
96                      Shri Rameshwaram, Bhopal
97                              Laharpur, Bhopal
98                         Ayodhya Nagar, Bhopal
99                          Katara Hills, Bhopal
100                         Danish Nagar, Bhopal
101                        Ashoka Garden, Bhopal
102               K-Sector Ayodhya Nagar, Bhopal
103                      Ayodhya Bypass , Bhopal
104                                       Mandak
105                              Salaiya, Bhopal
106                      Karamveer Nagar, Bhopal
107                             MP Nagar, Bhopal
108                          Bagmugaliya, Bhopal
109                           Lambakheda, Bhopal
110                            Awadhpuri, Bhopal
111                                          Gov
112                                Huzur, Bhopal
113                               Misrod, Bhopal
114                      Ayodhya Bypass , Bhopal
115                              Salaiya, Bhopal
116                      Rajharsh Colony, Bhopal
117                         Katara Hills, Bhopal
118                     Hoshangabad Road, Bhopal
119                     Hoshangabad Road, Bhopal
120                         Katara Hills, Bhopal
121                           Kolar Road, Bhopal
122                           Mahawadiya, Bhopal
123                     Hoshangabad Road, Bhopal
124                          Bagmugaliya, Bhopal
125                            Indrapuri, Bhopal
126                        Kalpana Nagar, Bhopal
127                         Airport Road, Bhopal
128                          Shirdipuram, Bhopal
129                          Bypass Road, Bhopal
130                            Bangrasia, Bhopal
131                            Awadhpuri, Bhopal
132                               Karond, Bhopal
133                           Kolar Road, Bhopal
134                            Mandideep, Bhopal
135                                Bagli, Bhopal
136                         Arera Colony, Bhopal
137                    Sagar Eden Garden, Bhopal
138                           Regal Town, Bhopal
139                         Nariyalkheda, Bhopal
140                             Trilanga, Bhopal
141                              Neelbad, Bhopal
142                         Pushpa Nagar, Bhopal
143                     Hoshangabad Road, Bhopal
144                   Sector C Indrapuri, Bhopal
145                                        Gandh
146                      Ayodhya Bypass , Bhopal
147                            Awadhpuri, Bhopal
148                          Shirdipuram, Bhopal
149                            Bairagarh, Bhopal
150                                Bagli, Bhopal
151                                Borda, Bhopal
152                            Awadhpuri, Bhopal
153                              Salaiya, Bhopal
154                          Idgah Hills, Bhopal
155                           Kolar Road, Bhopal
156                             TT Nagar, Bhopal
157                   Bairagarh Chichali, Bhopal
158                           Kolar Road, Bhopal
159                     Hoshangabad Road, Bhopal
160                      Ayodhya Bypass , Bhopal
161                     Panchvati Market, Bhopal
162                     Hoshangabad Road, Bhopal
163                     Hoshangabad Road, Bhopal
164                     Hoshangabad Road, Bhopal
165                               Misrod, Bhopal
166                          Data Colony, Bhopal
167                     New Central Jail, Bhopal
168                          Vijay Nagar, Bhopal
169                             Jatkhedi, Bhopal
170                              Salaiya, Bhopal
171                    Shiv Sangam Nagar, Bhopal
172                         Rachna Nagar, Bhopal
173                          Janki Nagar, Bhopal
174                       Sourabh Colony, Bhopal
175                          Bagmugaliya, Bhopal
176                          Gulmohar G3, Bhopal
177                          Patel Nagar, Bhopal
178                        Bawadia Kalan, Bhopal
179                        Bawadia Kalan, Bhopal
180                             Kalapani, Bhopal
181                            Mandideep, Bhopal
182                     Shri Rameshwaram, Bhopal
183                        Ayodhya Nagar, Bhopal
184                    Professors Colony, Bhopal
185                      E8 Arera Colony, Bhopal
186                     Hoshangabad Road, Bhopal
187                        Krishna Nagar, Bhopal
188                            Awadhpuri, Bhopal
189                        Tilak Society, Bhopal
190                           Kolar Road, Bhopal
191                    Akashganga Colony, Bhopal
192                         Airport Road, Bhopal
193                             Lalghati, Bhopal
194                         Nariyalkheda, Bhopal
195                         Airport Road, Bhopal
196                          Saket Nagar, Bhopal
197                     Hoshangabad Road, Bhopal
198                          Gopal Nagar, Bhopal
199                                Kolar, Bhopal
200                             Aishbagh, Bhopal
201                          Janki Nagar, Bhopal
202                         Danish Nagar, Bhopal
203                               Misrod, Bhopal
204                     Hoshangabad Road, Bhopal
205                                           Ch
206                          Shirdipuram, Bhopal
207                           Kolar Road, Bhopal
208                       Khajuri Kalan , Bhopal
209                               Misrod, Bhopal
210                               Misrod, Bhopal
211                          Bypass Road, Bhopal
212                         Lalita Nagar, Bhopal
213                        Bawadia Kalan, Bhopal
214                         Arera Colony, Bhopal
215          ratnagiri jaswant apartment, Bhopal
216                         Danish Nagar, Bhopal
217                         Chuna Bhatti, Bhopal
218                               Karond, Bhopal
219                          Danish Kunj, Bhopal
220                     Hoshangabad Road, Bhopal
221                      Ayodhya Bypass , Bhopal
222                          Rohit Nagar, Bhopal
223                           Kolar Road, Bhopal
224                          Bagmugaliya, Bhopal
225                             MP Nagar, Bhopal
226                     Hoshangabad Road, Bhopal
227                             Samardha, Bhopal
228                     Hoshangabad Road, Bhopal
229                             Laharpur, Bhopal
230                              Neelbad, Bhopal
231                         Arera Colony, Bhopal
232                         Katara Hills, Bhopal
233                     Hoshangabad Road, Bhopal
234                     Hoshangabad Road, Bhopal
235                             Trilanga, Bhopal
236                      Ayodhya Bypass , Bhopal
237                         Katara Hills, Bhopal
238                      Rajharsh Colony, Bhopal
239                        Ashoka Garden, Bhopal
240                            Awadhpuri, Bhopal
241                     Hoshangabad Road, Bhopal
242                           Kolar Road, Bhopal
243                          Chobdarpura, Bhopal
244                           Kolar Road, Bhopal
245                     New Central Jail, Bhopal
246                            Awadhpuri, Bhopal
247                          Anand Nagar, Bhopal
248                         Chuna Bhatti, Bhopal
249                         Katara Hills, Bhopal
250                     Hoshangabad Road, Bhopal
251                    Sector C Shahpura, Bhopal
252                          Janki Nagar, Bhopal
253                             Trilanga, Bhopal
254                     Hoshangabad Road, Bhopal
255                           Kolar Road, Bhopal
256                           Kolar Road, Bhopal
257                               Karond, Bhopal
258                          Saket Nagar, Bhopal
259                       Congress Nagar, Bhopal
260                                        Gandh
261                     Hoshangabad Road, Bhopal
262                      Ayodhya Bypass , Bhopal
263                             Kohefiza, Bhopal
264                             Sonagiri, Bhopal
265                         Katara Hills, Bhopal
266                         Katara Hills, Bhopal
267                        Bawadia Kalan, Bhopal
268                        Bawadia Kalan, Bhopal
269               Raja Bhoj Airport Area, Bhopal
270                         Airport Road, Bhopal
271                          Bagmugaliya, Bhopal
272                         Punjabi Bagh, Bhopal
273                          Vijay Nagar, Bhopal
274                         Arera Colony, Bhopal
275                            Fatehgarh, Bhopal
276                         Ghora Nakkas, Bhopal
277                     E 7 Arera colony, Bhopal
278                           Habib Ganj, Bhopal
279                     Hoshangabad Road, Bhopal
280                                        Gandh
281                          Bypass Road, Bhopal
282                      Ayodhya Bypass , Bhopal
283                         Danish Nagar, Bhopal
284                          Rohit Nagar, Bhopal
285                      Ayodhya Bypass , Bhopal
286                             Arwaliya, Bhopal
287                          Bypass Road, Bhopal
288                           Kolar Road, Bhopal
289                             TT Nagar, Bhopal
290                        Kalpana Nagar, Bhopal
291                         Airport Road, Bhopal
292                           Kolar Road, Bhopal
293                      Gulmohar Colony, Bhopal
294                      Ayodhya Bypass , Bhopal
295                              Salaiya, Bhopal
296                     Hoshangabad Road, Bhopal
297                     Barkhera Pathani, Bhopal
298                             Kohefiza, Bhopal
299                                        New M
300                         Arera Colony, Bhopal
301                         Katara Hills, Bhopal
302                              Salaiya, Bhopal
303                             Kohefiza, Bhopal
304                          Janki Nagar, Bhopal
305                         Katara Hills, Bhopal
306                                Bagli, Bhopal
307                          Idgah Hills, Bhopal
308                             Shahpura, Bhopal
309                          Suraj Nagar, Bhopal
310                      Teela Jamalpura, Bhopal
311                          Patel Nagar, Bhopal
312                          Ibrahimpura, Bhopal
313                           Mahawadiya, Bhopal
314                       Khajuri Kalan , Bhopal
315                         Vidisha Road, Bhopal
316                           Mahawadiya, Bhopal
317                     Hoshangabad Road, Bhopal
318                          Idgah Hills, Bhopal
319                           Kolar Road, Bhopal
320                                          Gov
321                                Bagli, Bhopal
322                         Arera Colony, Bhopal
323                         Arera Colony, Bhopal
324                               Misrod, Bhopal
325                                        Gandh
326                         Nehru Nagar , Bhopal
327                           Mahawadiya, Bhopal
328                                Borda, Bhopal
329                        Bawadia Kalan, Bhopal
330                                            H
331                             Aishbagh, Bhopal
332                     Hoshangabad Road, Bhopal
333                     Hoshangabad Road, Bhopal
334                         Katara Hills, Bhopal
335                                Bagli, Bhopal
336                         Katara Hills, Bhopal
337                     Hoshangabad Road, Bhopal
338                         Katara Hills, Bhopal
339                             Jumerati, Bhopal
340                       Rasipuram road, Bhopal
341                             Trilanga, Bhopal
342                             Jatkhedi, Bhopal
343                        Bawadia Kalan, Bhopal
344                       Peoples Campus, Bhopal
345                     Aashirwad Colony, Bhopal
346                         Katara Hills, Bhopal
347                              Neelbad, Bhopal
348                      Ayodhya Bypass , Bhopal
349                             MP Nagar, Bhopal
350                            Awadhpuri, Bhopal
351                         Arera Colony, Bhopal
352                             Aishbagh, Bhopal
353                 Kunjan nagar phase 1, Bhopal
354                                Bagli, Bhopal
355                      Ayodhya Bypass , Bhopal
356                         Katara Hills, Bhopal
357                          Bypass Road, Bhopal
358                            Peepalner, Bhopal
359                             Jatkhedi, Bhopal
360                           Mahawadiya, Bhopal
361                             Samardha, Bhopal
362                   Bairagarh Chichali, Bhopal
363                     Hoshangabad Road, Bhopal
364                              Neelbad, Bhopal
365                          Saket Nagar, Bhopal
366                         Nehru Nagar , Bhopal
367                             Lalghati, Bhopal
368                   Indra Vihar Colony, Bhopal
369                        Shivaji Nagar, Bhopal
370                         Jahangirabad, Bhopal
371                      Ayodhya Bypass , Bhopal
372                         Nariyalkheda, Bhopal
373                   Bairagarh Chichali, Bhopal
374                         Katara Hills, Bhopal
375                           Kolar Road, Bhopal
376                      Ayodhya Bypass , Bhopal
377                               Karond, Bhopal
378                           Kolar Road, Bhopal
379                           Kolar Road, Bhopal
380                          Gehun Kheda, Bhopal
381                     Hoshangabad Road, Bhopal
382                           Kolar Road, Bhopal
383                            Navi Bagh, Bhopal
384                              Salaiya, Bhopal
385                              Ratibad, Bhopal
386                          Golden City, Bhopal
387                     Hoshangabad Road, Bhopal
388                          Shirdipuram, Bhopal
389                     Hoshangabad Road, Bhopal
390                         Airport Road, Bhopal
391                           Kolar Road, Bhopal
392                           Kolar Road, Bhopal
393                                        Gandh
394                            Mandideep, Bhopal
395                             Shahpura, Bhopal
396                     Hoshangabad Road, Bhopal
397                         Airport Road, Bhopal
398                      Ayodhya Bypass , Bhopal
399                            Awadhpuri, Bhopal
400                     Hoshangabad Road, Bhopal
401                         Katara Hills, Bhopal
402                        Sukhi Sewania, Bhopal
403                          Phanda Kala, Bhopal
404                                        New M
405                             Lalghati, Bhopal
406                           Kolar Road, Bhopal
407                     Hoshangabad Road, Bhopal

In [1192]:
df.insert(
    2,
    'colony',
    df['pname']
    .str.extract(r'in\s+(.+?)(?:,?\s*bhopal)?$', flags=re.IGNORECASE, expand=False)
    .str.strip()
    .str.lower()
)

In [1193]:
df['colony'].isnull().sum()

0

In [1194]:
df.head()

,pname,society,colony,property_type,price_outer,price_per_sqft,possesion,description,Area,Total Floors,Facing,Property Age,furnishing,features,Overlooking,bedrooms,bathrooms,balconies,additional_room,area
0,"7 Bedroom House for sale in Jhagariya Khurd, B...",sage suncity,jhagariya khurd,House,105.0,3750,Ready To Move,Planning to buy an individual house in bhopal....,Built Up area: 2800\n(260.13 sq.m.) \nsq.ft.,1.0,NaN,NaN,NaN,NaN,NaN,7,5,0,Not Available,2800.00
1,"3 BHK Flat in Kolar Road, Bhopal",danish hills view,kolar road,Flat,85.0,6508,Ready To Move,3bhk spacious flat available for sale at kolar...,Carpet area: 1306\n(121.33 sq.m.) \nsq.ft.,2.0,North,0 to 1 Year Old,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...",Park/Garden,3,3,1,pooja room with view floor plan,1306.08
2,"2 BHK Flat in Katara Hills, Bhopal",narmada prem kesar,katara hills,Flat,25.0,2173,Ready To Move,This location is very attractive and near main...,Super Built up area 1150\n(106.84 sq.m.)\nCarp...,3.0,West,1 to 5 Year Old View Construction Status,NaN,"['Feng Shui / Vaastu Compliant', 'Lift(s)', 'M...","Park/Garden,Main Road",2,2,3,Not Available,1150.48
3,"8 Bedroom House for sale in Gurunanak Pura, Bh...",gurunanak pura independent house,gurunanak pura,House,65.0,5909,Ready To Move,Central bhopal location near by all facilities...,Plot area 1100\n(102.19 sq.m.)\nBuilt Up area:...,2.0,West,10+ Year Old,"['1 Water Purifier', '12 Fan', '1 Geyser', '22...","['Feng Shui / Vaastu Compliant', 'Private Gard...",Main Road,8,5,1,pooja room,1100.02
4,"6 Bedroom House for sale in Chuna Bhatti, Bhopal",chuna bhatti,chuna bhatti,House,650.0,16250,Ready To Move,Check out this 6 bhk house for sale in chuna b...,Plot area 4000\n(371.61 sq.m.) \nsq.ft.,3.0,NaN,1 to 5 Year Old,"['1 Water Purifier', '1 Fan', '1 Exhaust Fan',...",NaN,NaN,6,6,2,"pooja room,study room,servant room,store room",4000.00

In [1195]:
df['colony'].value_counts().shape

(300,)

In [1196]:
df['colony'].value_counts()

colony
hoshangabad road                   125
kolar road                         120
katara hills                        99
bawadia kalan                       75
ayodhya bypass                      63
awadhpuri                           51
misrod                              50
salaiya                             34
bagmugaliya                         34
arera colony                        26
airport road                        22
chuna bhatti                        21
bypass road                         21
karond                              17
jatkhedi                            17
shirdipuram                         16
saket nagar                         16
kohefiza                            15
janki nagar                         14
mahawadiya                          14
trilanga                            14
ashoka garden                       13
khajuri kalan                       13
danish kunj                         13
sanjeev nagar                       12
tt nagar                            12
ayodhya nagar                       12
indus towne                         12
mandideep                           12
shahpura                            11
mp nagar                            11
patel nagar                         11
gandhinagar                         11
lambakheda                          10
rajharsh colony                      9
idgah hills                          9
bagli                                8
bairagarh chichali                   8
danish nagar                         8
neelbad                              8
gulmohar colony                      8
new minal residency                  7
rohit nagar                          7
sonagiri                             7
nehru nagar                          7
kotra sultanabad                     6
nayapura                             6
govindpura                           6
samardha                             6
bairagarh                            6
lalghati                             6
shivaji nagar                        6
indrapuri                            6
gopal nagar                          6
jahangirabad                         6
b sector shahpura                    5
bhanpur                              5
vijay nagar                          5
e 7 arera colony                     5
kolar                                5
shakti nagar                         5
shahjahanabad                        5
laharpur                             5
lalita nagar                         5
mahabali nagar                       5
karamveer nagar                      5
karond chouraha                      5
nariyalkheda                         4
kalpana nagar                        4
teela jamalpura                      4
barkhera pathani                     4
aishbagh                             4
panchwati colony                     4
punjabi bagh                         4
ruchi lifescape                      3
vidya nagar                          3
peer gate area                       3
fatehgarh                            3
rasla khedi                          3
lakherapura                          3
e 3 arera colony                     3
phanda kala                          3
rajat bihar colony                   3
harshavardhan nagar                  3
e 5 arera colony                     3
old subhash nagar colony             3
gehun kheda                          3
vidisha road                         3
hinotiya alam                        3
katara                               3
indra vihar colony                   3
ibrahimpura                          3
barkhedi                             3
rachna nagar                         3
sukhi sewania                        3
ratibad                              3
shri rameshwaram                     3
kalapani                             3
narayan nagar                        3
bagsewaniya                          3
regal town                           3
borda                                3
parthsarthy enclave                  3
new central jail                     3
shiv sangam nagar                    3
gurunanak pura                       3
new choksey nagar                    2
aradhana nagar                       2
rajved colony                        2
bhel sangam colony                   2
arvind vihar                         2
bharati niketan                      2
gautam nagar                         2
jk road                              2
sector c shahpura                    2
sector b indrapuri                   2
shankracharya nagar                  2
amrawad khurd                        2
talaiya                              2
sivoy                                2
gulmohar g3                          2
bharat nagar, indrapuri              2
chanakyapuri                         2
navi bagh                            2
priyanka nagar                       2
karariya sajidabad                   2
housing board colony                 2
semri kalan                          2
pallavi nagar                        2
zone 1                               2
singarcholi                          2
bda colony                           2
sehore road                          2
aashirwad colony                     2
k-sector ayodhya nagar               2
sector c indrapuri                   2
sankhedi                             2
peoples campus                       2
tilak society                        2
habib ganj                           2
mandakini colony                     2
anand nagar                          2
kunjan nagar phase 1                 2
raja bhoj airport area               2
e8 arera colony                      2
1100 quarters arera colony           1
vineet kunj                          1
kalyan bhiwandi                      1
hoshangabad                          1
morga                                1
crystal campus                       1
arera hills                          1
transport nagar                      1
9b saket nagar                       1
bagh umrao dulha                     1
berkheda                             1
bagh dilkusha                        1
jayshree apartment                   1
naya pura, kolar road                1
khushipura                           1
sant asharam nagar phase 3           1
sarvadharam c sector                 1
shahid nagar colony                  1
berkhedi kalan                       1
chitragupt nagar                     1
malikhedi                            1
raghunath nagar                      1
kadambini                            1
hazrat nizamuddin colony             1
crystal                              1
empire hights                        1
prabhu nagar                         1
sant asharam nagar phase 2           1
abbas nagar                          1
kamla nagar                          1
badwai                               1
sargam cinema                        1
phase 2, misrod                      1
ahmedpur kalan                       1
mendua                               1
firdous nagar                        1
e 6 arera colony                     1
budhwara                             1
dwarka nagar                         1
10 no stop arera colony              1
rajendra nagar                       1
chandan nagar                        1
raisen road                          1
bhojpur road                         1
chouksey nagar                       1
rasuliya pathar                      1
good shepherd colony                 1
paraspar colony                      1
chowki talaiya                       1
adarsh colony                        1
mungalia kot                         1
isro colony                          1
vaishali nagar                       1
peace valley-1, narela shankari      1
tilak nagar                          1
sai vihar colony                     1
sajida nagar                         1
sarvdharm                            1
shymala hills                        1
siddharth enclave                    1
viswakarma nagar                     1
rusalli                              1
afkar colony                         1
chola naka                           1
akbarpur                             1
c sector shirdipuram                 1
sai ram colony sai mandir            1
aiims                                1
barrai                               1
jhagariya khurd                      1
panchwati                            1
arwaliya                             1
professors colony                    1
krishna nagar                        1
akashganga colony                    1
chinar fortune city                  1
ratnagiri jaswant apartment          1
chobdarpura                          1
congress nagar                       1
ghora nakkas                         1
suraj nagar                          1
shankar nagar                        1
jumerati                             1
rasipuram road                       1
peepalner                            1
golden city                          1
dr a s rao nagar colony              1
karond bye pass road                 1
chopra kalan, vidisha road           1
ahinsa vihar colony                  1
sourabh colony                       1
data colony                          1
panchvati market                     1
pushpa nagar                         1
piplani                              1
semra                                1
naveen nagar                         1
f-sector,kolar road                  1
coach factory                        1
gomti colony                         1
patel nagar colony                   1
fine avenue phase 2                  1
khajuri                              1
karod                                1
narela jod ayodhya bypass            1
noor mahal ashok colony              1
malviya nagar                        1
dam kheda                            1
huzur                                1
bangrasia                            1
sagar eden garden                    1
khejrabaramad                        1
kailash nagar                        1
e 4 arera colony                     1
sneh nagar                           1
rahul nagar mata mandir              1
eint khedi                           1
kamlesh nagar                        1
kolua kalan                          1
green city                           1
lumbini complex, mata mandir         1
sarvdharm colony                     1
ravidas nagar                        1
manak vihar                          1
new market                           1
tulsi nagar                          1
mubarakpur square                    1
mathai nagar cto bairagarh           1
basant kunj                          1
gulabi nagar                         1
12 no stop arera colony              1
radha krishna colony                 1
neerja nagar                         1
ambar apartment mp nagar             1
chhatrapati nagar                    1
ibrahimganj                          1
rent out residential                 1
indra nagar                          1
berasia                              1
minal residency                      1
jr lig colony                        1
old city                             1
industrial area                      1
lala lajpat rai colony               1
khajoori sadak                       1
sagar avenue                         1
nishatpura                           1
tilak nagar, bawadiya kalan          1
sector a rajeev nagar                1
laxmi nagar                          1
26 janakpuri ayodhya by pass         1
old subhash nagar                    1
chola rod                            1
nagarjun nagar                       1
jawahar chowk                        1
Name: count, dtype: int64

In [1197]:
df[df['colony'].str.contains('kolar')]

,pname,society,colony,property_type,price_outer,price_per_sqft,possesion,description,Area,Total Floors,Facing,Property Age,furnishing,features,Overlooking,bedrooms,bathrooms,balconies,additional_room,area
1,"3 BHK Flat in Kolar Road, Bhopal",danish hills view,kolar road,Flat,85.00,6508,Ready To Move,3bhk spacious flat available for sale at kolar...,Carpet area: 1306\n(121.33 sq.m.) \nsq.ft.,2.0,North,0 to 1 Year Old,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...",Park/Garden,3,3,1,pooja room with view floor plan,1306.08
5,"4 Bedroom House for sale in Kolar Road, Bhopal",ankit parisar nayapura,kolar road,House,75.00,4687,Ready To Move,Looking for buyer to purchase our housevilla a...,Plot area 1600\n(148.64 sq.m.)\nBuilt Up area:...,1.0,East,1 to 5 Year Old,"['8 Fan', '10 Light', 'No AC', 'No Bed', 'No C...","['Feng Shui / Vaastu Compliant', 'Private Gard...",NaN,4,6,2,"pooja room,study room,store room",1600.17
8,"4 Bedroom House for sale in Kolar Road, Bhopal",kolar road,kolar road,House,145.00,5370,Ready To Move,Wishing to settle down in an individual house ...,Built Up area: 2700\n(250.84 sq.m.) \nsq.ft.,1.0,NaN,NaN,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,NaN,4,4,1,Not Available,2700.19
40,"3 Bedroom House for sale in F-Sector,Kolar Roa...",f-sectorkolar road,"f-sector,kolar road",House,39.00,520,Ready To Move,Best budget in the house you visit and i am sh...,Plot area 7500\n(696.77 sq.m.) \nsq.ft.,2.0,North,5 to 10 Year Old,NaN,"['Water Storage', 'Visitor Parking']",Main Road,3,2,1,Not Available,7500.00
45,"3 Bedroom House for sale in Kolar Road, Bhopal",kolar road,kolar road,House,45.00,3333,Ready To Move,Are you planning to buy your dream home? You c...,Built Up area: 1350\n(125.42 sq.m.) \nsq.ft.,1.0,NaN,NaN,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,NaN,3,3,0,Not Available,1350.14
77,"3 Bedroom House for sale in Kolar, Bhopal",kolar,kolar,House,25.00,5555,Ready To Move,End of colony 24 hour water available,Plot area 450\n(41.81 sq.m.) \nsq.ft.,1.0,West,1 to 5 Year Old,NaN,['Private Garden / Terrace'],NaN,3,3,0,Not Available,450.05
121,"3 BHK Flat in Kolar Road, Bhopal",drishti city,kolar road,Flat,29.85,2388,Ready To Move,"3 bhk in dristi city, kolar road bhopal",Carpet area: 1250\n(116.13 sq.m.) \nsq.ft.,4.0,NaN,1 to 5 Year Old,NaN,"['Lift(s)', 'Swimming Pool', 'Park', 'Shopping...",NaN,3,2,2,Not Available,1250.00
133,"4 Bedroom House for sale in Kolar Road, Bhopal",kolar road,kolar road,House,80.00,5333,Ready To Move,Kolar road is one of bhopal's most sought afte...,Plot area 1500\n(139.35 sq.m.) \nsq.ft.,2.0,East,1 to 5 Year Old,NaN,NaN,Main Road,4,4,2,Not Available,1500.09
155,"1 BHK Flat in Kolar Road, Bhopal",sudha apartment,kolar road,Flat,20.00,6666,Ready To Move,We are the proud owners of this 1 bhk apartmen...,Super Built up area 300\n(27.87 sq.m.) \nsq.ft.,3.0,NaN,10+ Year Old,NaN,NaN,NaN,1,1,2,Not Available,300.03
158,"2 BHK Flat in Kolar Road, Bhopal",sarvadharm colony,kolar road,Flat,17.00,2125,Ready To Move,"2 bhk flat for sale , sharvdharam colony near ...",Super Built up area 800\n(74.32 sq.m.)\nCarpet...,2.0,North,5 to 10 Year Old,"['1 Bed', '1 Water Purifier', '1 Fan', '1 Geys...","['Water Storage', 'Visitor Parking']","Main Road,Others",2,2,2,others,800.00
190,"3 BHK Flat in Kolar Road, Bhopal",janki apartments,kolar road,Flat,37.00,2960,Ready To Move,Prime front facing property with a complete vi...,Built Up area: 1250\n(116.13 sq.m.)\nCarpet ar...,5.0,NaN,5 to 10 Year Old,"['2 Wardrobe', '5 Fan', '1 Exhaust Fan', '1 Li...",NaN,NaN,3,2,2,Not Available,1250.00
199,"2 Bedroom House for sale in Kolar, Bhopal",kolar,kolar,House,40.00,5000,Under Construction,2 bhk with good location in kolar road,Plot area 800\n(74.32 sq.m.) \nsq.ft.,NaN,NaN,NaN,NaN,NaN,NaN,2,2,2,Not Available,800.00
207,"1 BHK Flat in Kolar Road, Bhopal",soumya tulip heights,kolar road,Flat,16.50,3000,Ready To Move,Check out this 1 bhk apartment for sale in sou...,Built Up area: 550\n(51.1 sq.m.) \nsq.ft.,0.0,NaN,NaN,NaN,NaN,NaN,1,1,0,Not Available,550.00
223,"2 BHK Flat in Kolar Road, Bhopal",samriddhi apartment,kolar road,Flat,15.00,2727,Ready To Move,We are the proud owners of this 2 bhk apartmen...,Carpet area: 550\n(51.1 sq.m.) \nsq.ft.,1.0,NaN,5 to 10 Year Old,NaN,NaN,NaN,2,1,0,Not Available,550.06
242,"3 Bedroom House for sale in Kolar Road, Bhopal",lakshya serene wood,kolar road,House,40.00,3968,Under Construction,Check out this 3 bhk house for sale in kolar r...,Plot area 1008\n(93.65 sq.m.) \nsq.ft.,2.0,West,NaN,NaN,['Private Garden / Terrace'],NaN,3,3,1,Not Available,1008.06
244,"3 Bedroom House for sale in Kolar Road, Bhopal",kolar road,kolar road,House,65.00,7222,Ready To Move,We are proud owners of house/villa available f...,Plot area 900\n(83.61 sq.m.) \nsq.ft.,2.0,NaN,5 to 10 Year Old,NaN,NaN,NaN,3,2,1,Not Available,900.03
255,"3 BHK Flat in Kolar Road, Bhopal",ultimate campus,kolar road,Flat,35.00,2333,Ready To Move,Urgent sale corner flat in covered campus. Hos...,Carpet area: 1500\n(139.35 sq.m.) \nsq.ft.,4.0,East,5 to 10 Year Old,NaN,"['Security / Fire Alarm', 'Private Garden / Te...","Park/Garden,Main Road",3,2,2,Not Available,1500.21
256,"3 Bedroom House for sale in Kolar Road, Bhopal",windsor palms,kolar road,House,38.00,6333,Under Construction,Do you wish to buy an independent house in kol...,Plot area 600\n(55.74 sq.m.)\nBuilt Up area: 1...,1.0,West,Under Construction,NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard...","Park/Garden,Main Road",3,3,1,Not Available,600.03
288,"2 BHK Flat in Kolar Road, Bhopal",sai visal,kolar road,Flat,24.99,2687,Ready To Move,"2 bhk flat for sale near lotus hospital, kolar...",Super Built up area 930\n(86.4 sq.m.)\nCarpet ...,2.0,South-East,5 to 10 Year Old,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","Pool,Others,Park/Garden,Sea facing,Club,Main Road",2,2,1,"pooja room,others",930.03
292,"2 BHK Flat in Kolar Road, Bhopal",drishti city,kolar road,Flat,27.80,2865,Ready To Move,This 2 bhk apartment is available for sale in ...,Super Built up area 970\n(90.12 sq.m.)\nCarpet...,1.0,NaN,5 to 10 Year Old,"['1 Wardrobe', '1 Fan', '1 Fridge', '1 Exhaust...","['Feng Shui / Vaastu Compliant', 'Lift(s)', 'S...","Pool,Park/Garden,Club,Main Road",2,2,2,Not Available,970.33
319,"3 Bedroom House for sale in Kolar Road, Bhopal",ultimate english villa,kolar road,House,68.00,8500,Ready To Move,"Villa is east facing, garden facing, corner, t...",Plot area 800\n(74.32 sq.m.) \nsq.ft.,2.0,East,5 to 10 Year Old,"['5 Fan', '1 Geyser', '12 Light', 'No AC', 'No...","['Feng Shui / Vaastu Compliant', 'Private Gard...","Pool,Park/Garden,Club,Main Road",3,3,3,"pooja room,study room",800.00
375,"2 BHK Flat in Kolar Road, Bhopal",kartika home's,kolar road,Flat,22.00,3520,Ready To Move,We are the proud owners of this 2 bhk apartmen...,Super Built up area 625\n(58.06 sq.m.) \nsq.ft.,2.0,NaN,5 to 10 Year Old,NaN,NaN,NaN,2,2,0,Not Available,625.00
378,"2 BHK Flat in Kolar Road, Bhopal",bima kunj,kolar road,Flat,15.00,3409,Ready To Move,Heres a more attractive version of your message:,Carpet area: 440\n(40.88 sq.m.) \nsq.ft.,3.0,NaN,10+ Year Old,NaN,NaN,NaN,2,2,1,Not Available,440.01
379,"2 BHK Flat in Kolar Road, Bhopal",sarvadharm colony,kolar road,Flat,17.00,2931,Ready To Move,All the rooms are well maintained and furnishe...,Carpet area: 580\n(53.88 sq.m.) \nsq.ft.,2.0,East,10+ Year Old,"['2 Wardrobe', '4 Light', '1 Chimney', 'No AC'...","['Feng Shui / Vaastu Compliant', 'Water Storag...",NaN,2,2,1,Not Available,580.01
382,"4 Bedroom House for sale in Kolar Road, Bhopal",danish hills view,kolar road,House,225.00,18000,Ready To Move,We are proud owners of house/villa available f...,Plot area 1250\n(116.13 sq.m.) \nsq.ft.,3.0,North-East,0 to 1 Year Old,"['1 Water Purifier', '1 Exhaust Fan', '1 Dinin...",['Private Garden / Terrace'],NaN,4,4,2,Not Available,1250.00
391,"2 Bedroom House for sale in Kolar Road, Bhopal",kolar road,kolar road,House,30.00,3750,Ready To Move,Do you wish to buy an independent house in kol...,Plot area 800\n(74.32 sq.m.) \nsq.ft.,1.0,East,1 to 5 Year Old,"['2 Light', 'No AC', 'No Bed', 'No Chimney', '...","['Water Storage', 'Natural Light', 'Airy Rooms']",NaN,2,1,0,Not Available,800.00
392,"3 BHK Flat in Kolar Road, Bhopal",sarvadharm colony,kolar road,Flat,55.00,6875,Ready To Move,We are the proud owners of this 3 bhk apartmen...,Built Up area: 800\n(74.32 sq.m.) \nsq.ft.,0.0,NaN,5 to 10 Year Old,NaN,NaN,NaN,3,2,1,Not Available,800.00
406,"3 Bedroom House for sale in Kolar Road, Bhopal",ishaan vista,kolar road,House,75.00,6818,Ready To Move,3 bhk newly duplex for sale covered campus in ...,Plot area 1100\n(102.19 sq.m.) \nsq.ft.,2.0,East,0 to 1 Year Old,"['1 Modular Kitchen', 'No AC', 'No Bed', 'No C...","['Maintenance Staff', 'Park', 'Visitor Parking']","Club,Main Road,Park/Garden",3,3,2,Not Available,1100.03
408,"2 BHK Flat in Kolar Road, Bhopal",janki apartments,kolar road,Flat,24.00,3692,Ready To Move,"Prime location, shahpura, near by bansal hospi...",Carpet area: 650\n(60.39 sq.m.),1.0,East,10+ Year Old,NaN,"['Park', 'Visitor Parking']",Park/Garden,2,2,2,others,650.05
416,"2 Bedroom House for sale in Kolar Road, Bhopal",j k town kolar,kolar road,House,400.00,26666,Ready To Move,We are proud owners of house/villa available f...,Plot area 1500\n(139.35 sq.m.) \nsq.ft.,3.0,NaN,0 to 1 Year Old,"['20 Fan', 'No AC', 'No Bed', 'No Chimney', 'N...",NaN,NaN,2,1,0,Not Available,1500.04
420,"3 BHK Flat in Kolar Road, Bhopal",windsor aralia,kolar road,Flat,49.99,3423,Ready To Move,"3 bhk spacious flat for sale windsor arelia, k...",Super Built up area 1460\n(135.64 sq.m.) \nsq...,5.0,West,1 to 5 Year Old,NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","Pool,Others,Park/Garden,Sea facing,Club,Main Road",3,1,3,"pooja room,others",1460.41
427,"2 BHK Flat in Kolar Road, Bhopal",ujjawala aamra valley,kolar road,Flat,36.00,3512,Ready To Move,Its a garden facing big room size 2 bhk,Super Built up area 1025\n(95.23 sq.m.)\nCarpe...,2.0,South-West,1 to 5 Year Old,"['1 Bed', '2 Wardrobe', '1 Water Purifier', '1...","['Power Back-up', 'Lift(s)', 'Park', 'Shopping...","Pool,Park/Garden,Club,Main Road,Others",2,2,2,Not Available,1025.06
438,"3 Bedroom House for sale in Kolar Road, Bhopal",kolar road,kolar road,House,65.00,8125,Ready To Move,"3 bhk duplex for sale tulips green, kolar road...",Plot area 800\n(74.32 sq.m.)\nBuilt Up area: 1...,2.0,West,1 to 5 Year Old,NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard...","Pool,Club,Park/Garden,Main Road,Sea facing,Others",3,3,2,"others,pooja room,study room",800.00
456,"3 Bedroom House for sale in Kolar Road, Bhopal",windsor palms,kolar road,House,55.00,6875,Under Construction,Spacious design nice elevation 3bhk 3t on 6 la...,Plot area 800\n(74.32 sq.m.)\nBuilt Up area: 1...,2.0,West,NaN,NaN,"['Water Storage', 'Park', 'Airy Rooms']",Park/Garden,3,3,2,Not Available,800.00
457,"2 BHK Flat in Kolar Road, Bhopal",samriddhi apartment,kolar road,Flat,23.00,2875,Ready To Move,Small multi of 6-7 flats with lift nice locality,Carpet area: 800\n(74.32 sq.m.) \nsq.ft.,2.0,NaN,10+ Year Old,NaN,"['Lift(s)', 'Water Storage', 'Park']",NaN,2,2,1,Not Available,800.00
467,"4 Bedroom House for sale in Kolar Road, Bhopal",rajharsh colony kolar road,kolar road,House,40.00,6666,Ready To Move,Self constructed independent house inclusive 4...,Plot area 600\n(55.74 sq.m.) \nsq.ft.,1.0,NaN,10+ Year Old,NaN,['Water Storage'],NaN,4,4,1,store room,600.06
471,"3 BHK Flat in Kolar Road, Bhopal",faith imperial heights,kolar road,Flat,18.00,1969,Ready To Move,Clubhouse park and well maintained society,Super Built up area 914\n(84.91 sq.m.) \nsq.ft.,3.0,NaN,10+ Year Old View Construction Status,NaN,"['Lift(s)', 'Club house / Community Center', '...",NaN,3,2,3,Not Available,914.17
478,"3 Bedroom House for sale in Kolar Road, Bhopal",chitransh sai vihar semrikalan,kolar road,House,65.00,6280,Ready To Move,Property description:- Its a residential duple...,Plot area 1035\n(96.15 sq.m.) \nsq.ft.,2.0,East,1 to 5 Year Old,NaN,NaN,Park/Garden,3,2,1,Not Available,1035.03
480,"2 BHK Flat in Kolar Road, Bhopal",covered campus,kolar road,Flat,16.00,2051,Ready To Move,Looking for a 2 bhk property for sale in bhopa...,Carpet area: 780\n(72.46 sq.m.) \nsq.ft.,5.0,North-East,0 to 1 Year Old,"['1 Wardrobe', '1 Water Purifier', '2 Fan', '1...","['Feng Shui / Vaastu Compliant', 'Security / F...",Main Road,2,2,2,Not Available,780.11
515,"2 BHK Flat in Kolar Road, Bhopal",fortune soumya tulip heights,kolar road,Flat,14.50,2290,Ready To Move,We are the proud owners of this 2 bhk apartmen...,Carpet area: 633\n(58.81 sq.m.) \nsq.ft.,0.0,NaN,5 to 10 Year Old,NaN,NaN,NaN,2,1,1,Not Available,633.19
557,"3 BHK Flat in Kolar Road, Bhopal",madhuban heights,kolar road,Flat,45.00,3846,Ready To Move,This 3 bhk apartment is available for sale in ...,Carpet area: 1170\n(108.7 sq.m.) \nsq.ft.,4.0,East,5 to 10 Year Old View Construction Status,"['3 Bed', '1 Wardrobe', '4 Fan', '1 Sofa', '1 ...","['Security / Fire Alarm', 'Lift(s)', 'High Cei...",NaN,3,3,2,Not Available,1170.05
578,"5 BHK Flat in Kolar Road, Bhopal",danish hills view,kolar road,Flat,175.00,5468,Under Construction,5 bhk flat available for sale specialist and l...,Carpet area: 3200\n(297.29 sq.m.) \nsq.ft.,4.0,East,NaN,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...",Park/Garden,5,5,3,"pooja room,study room,servant room",3200.44
592,"3 BHK Flat in Kolar Road, Bhopal",windsor aralia,kolar road,Flat,50.00,2976,Ready To Move,Fully furnished flat at prime location,Super Built up area 1680\n(156.08 sq.m.)\nCarp...,2.0,NaN,5 to 10 Year Old,"['1 Bed', '1 Wardrobe', '1 Sofa', '1 AC', '1 M...","['Power Back-up', 'Lift(s)', 'Swimming Pool', ...",NaN,3,3,2,Not Available,1680.11
595,"3 Bedroom House for sale in Kolar Road, Bhopal",kolar road,kolar road,House,105.00,84000,Ready To Move,Property description:,Plot area 125\n(11.61 sq.m.)\nBuilt Up area: 1...,2.0,West,0 to 1 Year Old,NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard...","Others,Main Road",3,3,3,others,125.00
596,"1 BHK Flat in Kolar Road, Bhopal",sarvadharm colony,kolar road,Flat,25.00,2774,Ready To Move,We are the proud owners of this 1 bhk a pentho...,Built Up area: 900\n(83.61 sq.m.)\nCarpet area...,3.0,East,5 to 10 Year Old,NaN,"['Private Garden / Terrace', 'False Ceiling Li...",Park/Garden,1,2,1,Not Available,901.23
598,"3 Bedroom House for sale in Kolar Road, Bhopal",rajved colony,kolar road,House,39.50,3038,Under Construction,Tncp approved. 30x20/15x40 duplex available.,Plot area 600\n(55.74 sq.m.)\nBuilt Up area: 1...,2.0,East,NaN,"['28 Light', '1 Modular Kitchen', 'No AC', 'No...","['Feng Shui / Vaastu Compliant', 'Private Gard...","Main Road,Others",3,3,2,Not Available,1300.20
606,"2 BHK Flat in Kolar Road, Bhopal",siddharth tower,kolar road,Flat,20.00,3333,Ready To Move,Spacious design open green area with prime loc...,Super Built up area 800\n(74.32 sq.m.)\nCarpet...,5.0,West,1 to 5 Year Old,NaN,"['Security / Fire Alarm', 'Lift(s)', 'Water St...",Park/Garden,2,2,3,Not Available,600.06
617,"3 Bedroom House for sale in Kolar Road, Bhopal",kolar road,kolar road,House,45.00,5625,Ready To Move,"3 bhk duplex for sale rajharsh colony, kolar r...",Plot area 800\n(74.32 sq.m.)\nBuilt Up area: 1...,2.0,West,1 to 5 Year Old,NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard...","Park/Garden,Sea facing,Others,Main Road",3,3,1,others,800.00
619,"2 BHK Flat in Kolar Road, Bhopal",bilal complex apartments,kolar road,Flat,30.00,3588,Ready To Move,Property for sale fully furnished with all ame...,Carpet area: 836\n(77.67 sq.m.) \nsq.ft.,3.0,East,5 to 10 Year Old,"['1 Water Purifier', '3 Fan', '1 Fridge', '1 E...",['Water Storage'],NaN,2,2,1,study room,836.12
627,"3 BHK Flat in Kolar Road, Bhopal",agrawal sagar green hills,kolar road,Flat,62.00,4189,Ready To Move,A spacious 3 bhk flat is available for sale in...,Super Built up area 1480\n(137.5 sq.m.)\nBuilt...,1.0,East,5 to 10 Year Old,"['1 Bed', '1 Wardrobe', '1 Fan', '1 Exhaust Fa...","['Power Back-up', 'Security / Fire Alarm', 'Li...",Others,3,3,3,Not Available,1480.07
631,"2 BHK Flat in Kolar Road, Bhopal",balaji tower kolar eoad,kolar road,Flat,20.00,2928,Ready To Move,This 2 bhk apartment is available for sale in ...,Carpet area: 683\n(63.45 sq.m.) \nsq.ft.,3.0,NaN,1 to 5 Year Old,"['1 Fan', '2 Light', '1 Modular Kitchen', 'No ...","['Security / Fire Alarm', 'Maintenance Staff',...",NaN,2,2,2,Not Available,683.06
652,"3 Bedroom House for sale in Kolar Road, Bhopal",kwality paradise girdhar parasar,kolar road,House,95.00,6333,Ready To Move,I have a house/villa available for sale in kol...,Plot area 1500\n(139.35 sq.m.) \nsq.ft.,2.0,NaN,5 to 10 Year Old,NaN,NaN,NaN,3,4,1,Not Available,1500.08
668,"3 BHK Flat in Kolar Road, Bhopal",ultimate campus,kolar road,Flat,45.00,3103,Ready To Move,"3bhk spacious flat for sale @ ultimate campus,...",Carpet area: 1450\n(134.71 sq.m.) \nsq.ft.,1.0,NaN,5 to 10 Year Old,NaN,NaN,NaN,3,2,2,Not Available,1450.21
676,"4 BHK Flat in Kolar Road, Bhopal",agrawal sagar green hills,kolar road,Flat,75.00,4132,Ready To Move,This property is situated near top of the hill...,Super Built up area 1815\n(168.62 sq.m.)\nCarp...,0.0,East,1 to 5 Year Old,"['3 Bed', '3 Wardrobe', '3 Fan', '1 Sofa', '1 ...","['Security / Fire Alarm', 'Private Garden / Te...","Park/Garden,Club,Main Road",4,3,2,Not Available,1815.10
696,"2 BHK Flat in Kolar Road, Bhopal",sai deep apartment,kolar road,Flat,22.00,2625,Ready To Move,Urgent residential apartment for sell. (On ben...,Super Built up area 800\n(74.32 sq.m.)\nBuilt ...,3.0,North,1 to 5 Year Old,NaN,"['Feng Shui / Vaastu Compliant', 'Water Storag...","Park/Garden,Main Road",2,2,2,Not Available,838.10
708,"2 BHK Flat in Kolar Road, Bhopal",danish hills view,kolar road,Flat,40.00,4938,Under Construction,2 bhk spacious flat available for sale at kola...,Carpet area: 810\n(75.25 sq.m.) \nsq.ft.,4.0,North,NaN,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...",Park/Garden,2,2,1,view floor plan,810.04
725,"3 Bedroom House for sale in Kolar Road, Bhopal",girdhar heights,kolar road,House,85.00,5666,Ready To Move,I have a house/villa available for sale in kol...,Plot area 1500\n(139.35 sq.m.) \nsq.ft.,2.0,NaN,5 to 10 Year Old,NaN,NaN,NaN,3,4,1,Not Available,1500.18
729,"2 BHK Flat in Kolar Road, Bhopal",sarvadharm colony,kolar road,Flat,22.50,3214,Ready To Move,"Main road flat near all mall showroom , hospit...",Carpet area: 700\n(65.03 sq.m.) \nsq.ft.,1.0,East,10+ Year Old,NaN,"['Maintenance Staff', 'Water Storage']",Main Road,2,2,1,Not Available,700.06
776,"2 BHK Flat in Kolar Road, Bhopal",sarvadharm colony,kolar road,Flat,17.00,2428,Ready To Move,We are the proud owners of this 2 bhk apartmen...,Super Built up area 700\n(65.03 sq.m.) \nsq.ft.,2.0,NaN,10+ Year Old,NaN,NaN,NaN,2,2,1,Not Available,700.16
794,"2 BHK Flat in Kolar Road, Bhopal",sai vishal apartment,kolar road,Flat,20.00,2150,Ready To Move,"2bhk residential flat for sale,near lotas hosp...",Super Built up area 930\n(86.4 sq.m.)\nCarpet ...,2.0,South-East,5 to 10 Year Old,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...",Main Road,2,2,1,others,930.23
797,"3 Bedroom House for sale in Kolar Road, Bhopal",ultimate english villa,kolar road,House,60.00,8534,Ready To Move,Na....................................,Plot area 703\n(65.31 sq.m.) \nsq.ft.,2.0,West,5 to 10 Year Old,"['2 Wardrobe', '1 Light', '1 Modular Kitchen',...","['Maintenance Staff', 'Water Storage', 'Park',...",NaN,3,3,1,Not Available,703.07
798,"5 Bedroom House for sale in Kolar Road, Bhopal",agrawal sagar green hills,kolar road,House,180.00,13636,Ready To Move,Planning to buy an individual house in bhopal....,Plot area 1320\n(122.63 sq.m.) \nsq.ft.,3.0,North,1 to 5 Year Old,"['1 Water Purifier', '1 Fan', '1 Fridge', '1 E...",NaN,"Pool,Park/Garden,Club,Main Road",5,5,3,"pooja room,study room",1320.04

In [1198]:
idx = [40, 77, 199, 1313, 1350, 1353, 1546]

df.loc[idx, ['colony']] = 'kolar road'

In [1199]:
df[df['colony'].str.contains('arera')]

,pname,society,colony,property_type,price_outer,price_per_sqft,possesion,description,Area,Total Floors,Facing,Property Age,furnishing,features,Overlooking,bedrooms,bathrooms,balconies,additional_room,area
80,"1 BHK Flat in Arera Colony, Bhopal",sagar residency,arera colony,Flat,15.00,3000,Ready To Move,A 1bhk flat is available for sale at sagar res...,Carpet area: 500\n(46.45 sq.m.) \nsq.ft.,3.0,NaN,10+ Year Old,NaN,['Water Storage'],NaN,1,1,1,Not Available,500.00
136,"3 Bedroom House for sale in Arera Colony, Bhopal",dk devsthali,arera colony,House,135.00,10384,Ready To Move,Duplex for sale at prime location of bawadiya ...,Plot area 1300\n(120.77 sq.m.) \nsq.ft.,3.0,NaN,0 to 1 Year Old,"['1 Geyser', '1 Chimney', '1 Microwave', 'No A...","['Feng Shui / Vaastu Compliant', 'Park', 'Rain...",Park/Garden,3,3,2,"pooja room,servant room",1300.08
185,"6 Bedroom House for sale in E8 Arera Colony, B...",e8 arera colony,e8 arera colony,House,265.00,11736,Ready To Move,Looking to buy an independent house in bhopal?...,Plot area 2258\n(209.78 sq.m.) \nsq.ft.,2.0,North,5 to 10 Year Old,"['1 Water Purifier', '8 Fan', '1 Fridge', '1 E...","['Private Garden / Terrace', 'High Ceiling Hei...",Park/Garden,6,6,2,"pooja room,study room,servant room,store room",2258.01
214,"3 BHK Flat in Arera Colony, Bhopal",lala lajpat rai society,arera colony,Flat,44.00,3384,Ready To Move,We are the proud owners of this 3 bhk apartmen...,Super Built up area 1300\n(120.77 sq.m.) \nsq...,2.0,NaN,10+ Year Old,NaN,NaN,NaN,3,2,3,Not Available,1300.24
231,"2 BHK Flat in Arera Colony, Bhopal",vivek apartment,arera colony,Flat,30.00,3750,Ready To Move,Spacious 2 bhk apartment in prime arera colony,Super Built up area 800\n(74.32 sq.m.) \nsq.ft.,2.0,North,10+ Year Old,"['2 Bed', '1 Wardrobe', '4 Fan', '1 Sofa', '1 ...","['Maintenance Staff', 'Water Storage', 'Park',...","Park/Garden,Main Road",2,2,2,Not Available,800.00
274,"3 BHK Flat in Arera Colony, Bhopal",mirchandani shalimar enclave,arera colony,Flat,40.00,5479,Ready To Move,Well ventilated. Terrace use exclusive for thi...,Carpet area: 730\n(67.82 sq.m.) \nsq.ft.,3.0,NaN,10+ Year Old,NaN,"['Security / Fire Alarm', 'Park']",NaN,3,2,2,Not Available,730.06
277,"3 Bedroom House for sale in E 7 Arera colony, ...",e 7 arera colony,e 7 arera colony,House,295.00,12291,Ready To Move,Wishing to settle down in an individual house ...,Plot area 2400\n(222.97 sq.m.) \nsq.ft.,1.0,East,10+ Year Old,NaN,NaN,Main Road,3,3,1,Not Available,2400.13
300,"2 Bedroom House for sale in Arera Colony, Bhopal",paras city,arera colony,House,15.00,2500,Under Construction,We have a house/villa available for sale in vi...,Plot area 600\n(55.74 sq.m.) \nsq.ft.,1.0,NaN,NaN,NaN,NaN,NaN,2,1,0,Not Available,600.00
322,"4 Bedroom House for sale in Arera Colony, Bhopal",arera colony,arera colony,House,432.00,18000,Ready To Move,Ultra premium house,Plot area 2400\n(222.97 sq.m.)\nBuilt Up area:...,2.0,West,10+ Year Old,NaN,"['Water Storage', 'Park', 'Visitor Parking']","Park/Garden,Main Road",4,3,2,"pooja room,study room,others",2400.00
323,"3 BHK Flat in Arera Colony, Bhopal",sai dev apartment,arera colony,Flat,45.00,4500,Ready To Move,Its in posh area e7 arera colony bhopal also m...,Carpet area: 1000\n(92.9 sq.m.) \nsq.ft.,0.0,NaN,10+ Year Old,NaN,NaN,NaN,3,2,2,Not Available,1000.00
351,"3 BHK Flat in Arera Colony, Bhopal",baba apartments e7 arera colony,arera colony,Flat,50.00,3333,Ready To Move,We are the proud owners of this 3 bhk apartmen...,Super Built up area 1500\n(139.35 sq.m.)\nCarp...,2.0,NaN,10+ Year Old,NaN,"['Park', 'Visitor Parking', 'Water Storage', '...",NaN,3,2,3,Not Available,1500.15
458,"5 Bedroom House for sale in Arera Colony, Bhopal",lala lajpat rai society,arera colony,House,225.00,16000,Ready To Move,Looking for buyer to purchase our house/villa ...,Plot area 1406.25\n(130.64 sq.m.) \nsq.ft.,3.0,NaN,5 to 10 Year Old,NaN,NaN,NaN,5,6,3,Not Available,1406.25
523,"3 Bedroom House for sale in E 7 Arera colony, ...",e 7 arera colony,e 7 arera colony,House,190.00,12666,Ready To Move,"E7 arera colony, 1100 quaters. Benind hanuman ...",Plot area 1500\n(139.35 sq.m.) \nsq.ft.,NaN,West,10+ Year Old,NaN,['Park'],"Park/Garden,Main Road",3,2,1,Not Available,1500.08
540,"2 Bedroom House for sale in Arera Colony, Bhopal",mahendra city,arera colony,House,15.50,2583,Under Construction,We are proud owners of house/villa available f...,Plot area 600\n(55.74 sq.m.) \nsq.ft.,1.0,NaN,NaN,NaN,NaN,NaN,2,1,0,Not Available,600.08
584,"2 BHK Flat in Arera Colony, Bhopal",shiva apartment,arera colony,Flat,25.90,3453,Ready To Move,For sale: A well-Maintained 2bhk residential f...,Super Built up area 750\n(69.68 sq.m.)\nBuilt ...,1.0,North,10+ Year Old,"['2 Wardrobe', '20 Light', '1 Modular Kitchen'...",['Visitor Parking'],Main Road,2,2,1,Not Available,750.07
665,"2 BHK Flat in E8 Arera Colony, Bhopal",fine homes,e8 arera colony,Flat,30.00,352941,Ready To Move,Ground flour or 2 flat me ane jane k liye 2 ma...,Carpet area: 8.5\n(0.79 sq.m.) \nsq.ft.,0.0,NaN,10+ Year Old,NaN,NaN,NaN,2,2,0,Not Available,8.50
674,"5 Bedroom House for sale in E 5 Arera colony, ...",e 5 arera colony,e 5 arera colony,House,600.00,25000,Ready To Move,Independet house for sale at e-5 arera colony ...,Plot area 2400\n(222.97 sq.m.)\nBuilt Up area:...,2.0,North,10+ Year Old,"['9 Fan', '13 Light', 'No AC', 'No Bed', 'No C...","['Water Storage', 'Visitor Parking', 'Rain Wat...",NaN,5,7,3,"pooja room,study room,others",2400.00
690,"4 Bedroom House for sale in Arera Colony, Bhopal",brokar,arera colony,House,550.00,15714,Ready To Move,Dismental house and very good locations,Plot area 2400\n(222.97 sq.m.)\nBuilt Up area:...,2.0,NaN,10+ Year Old,NaN,NaN,NaN,4,5,2,Not Available,3500.06
711,"4 Bedroom House for sale in E 3 Arera Colony, ...",e 3 arera colony,e 3 arera colony,House,420.00,21000,Ready To Move,Property on 10 no bus stop to habibganj naka road,Plot area 2000\n(185.81 sq.m.) \nsq.ft.,1.0,NaN,10+ Year Old,NaN,NaN,NaN,4,2,1,Not Available,2000.00
753,"4 Bedroom House for sale in E 7 Arera colony, ...",e 7 arera colony,e 7 arera colony,House,350.00,14510,Ready To Move,Prime location near to 11 nos market can be us...,Plot area 2412\n(224.08 sq.m.) \nsq.ft.,2.0,North,10+ Year Old,NaN,"['Water Storage', 'Visitor Parking', 'Waste Di...",Main Road,4,4,3,"pooja room,study room,servant room",2412.13
791,"4 BHK Flat in Arera Colony, Bhopal",lilasons kanha towers,arera colony,Flat,200.00,7659,Ready To Move,We are the proud owners of this 4 bhk apartmen...,Carpet area: 2611\n(242.57 sq.m.) \nsq.ft.,5.0,NaN,5 to 10 Year Old,"['1 Water Purifier', '6 Fan', '1 Fridge', '1 E...",NaN,NaN,4,3,3,Not Available,2611.31
805,"3 BHK Flat in Arera Colony, Bhopal",mahendra township,arera colony,Flat,27.25,2270,Ready To Move,"This beautiful 3 bhk flat in arera colony, bho...",Super Built up area 1200\n(111.48 sq.m.)\nCarp...,3.0,West,1 to 5 Year Old,NaN,"['Maintenance Staff', 'Park', 'Visitor Parking']","Park/Garden,Main Road",3,2,1,Not Available,1200.44
809,"3 BHK Flat in Arera Colony, Bhopal",mirchandani shalimar regency,arera colony,Flat,52.00,5777,Ready To Move,Check out this 3 bhk apartment for sale in mir...,Carpet area: 900\n(83.61 sq.m.) \nsq.ft.,0.0,NaN,1 to 5 Year Old,"['3 Wardrobe', '1 Modular Kitchen', 'No AC', '...","['Lift(s)', 'Water Storage', 'Park', 'Visitor ...",Park/Garden,3,3,2,Not Available,900.12
890,"2 BHK Flat in Arera Colony, Bhopal",lala lajpat rai society,arera colony,Flat,15.00,3000,Ready To Move,Located in the popular residential address of ...,Carpet area: 500\n(46.45 sq.m.) \nsq.ft.,1.0,NaN,10+ Year Old,NaN,NaN,NaN,2,2,1,Not Available,500.00
900,"3 BHK Flat in 12 No Stop Arera Colony, Bhopal",12no. bus stop multi,12 no stop arera colony,Flat,65.00,6500,Ready To Move,We are the proud owners of this 3 bhk apartmen...,Carpet area: 1000\n(92.9 sq.m.) \nsq.ft.,1.0,NaN,0 to 1 Year Old,NaN,NaN,NaN,3,2,2,Not Available,1000.00
931,"6 Bedroom House for sale in E 4 Arera Colony, ...",e 4 arera colony,e 4 arera colony,House,375.00,15625,Ready To Move,Independent property at prime location of bhop...,Plot area 2400\n(222.97 sq.m.)\nBuilt Up area:...,1.0,NaN,10+ Year Old,"['1 Water Purifier', '6 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Water purifier',...","Main Road,Others",6,4,3,"pooja room,study room,servant room,store room",2400.00
956,"4 BHK Flat in Arera Colony, Bhopal",ibd kings park,arera colony,Flat,65.00,3466,Ready To Move,Located in the popular residential address of ...,Super Built up area 1875\n(174.19 sq.m.)\nCarp...,2.0,East,0 to 1 Year Old,NaN,"['Power Back-up', 'Lift(s)', 'Swimming Pool', ...","Park/Garden,Club,Main Road",4,3,3,Not Available,1875.36
959,"4 Bedroom House for sale in Arera Colony, Bhopal",arera colony,arera colony,House,750.00,25000,Ready To Move,This proparty is very good locations near by m...,Plot area 3000\n(278.71 sq.m.) \nsq.ft.,3.0,NaN,10+ Year Old,NaN,"['Maintenance Staff', 'Park', 'Visitor Parking']",NaN,4,4,3,"servant room,store room",3000.00
968,"4 Bedroom House for sale in Arera Colony, Bhopal",area colony,arera colony,House,1700.00,40476,Ready To Move,"This proparty is very good location .,this pro...",Plot area 4200\n(390.19 sq.m.) \nsq.ft.,2.0,NaN,10+ Year Old,"['1 Water Purifier', '1 Fan', '1 Fridge', '1 G...",NaN,NaN,4,4,3,"store room,servant room",4200.02
1027,"4 BHK Flat in Arera Colony, Bhopal",topaz,arera colony,Flat,60.00,4000,Ready To Move,Big size 4bhk flat for sale 1900sq.Ft. Rohit n...,Built Up area: 1864\n(173.17 sq.m.)\nCarpet ar...,5.0,East,5 to 10 Year Old,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...",Park/Garden,4,3,2,"pooja room,servant room",1500.00
1028,"6 Bedroom House for sale in E 5 Arera colony, ...",e 5 arera colony,e 5 arera colony,House,515.00,21458,Ready To Move,Key highlights:,Plot area 2400\n(222.97 sq.m.)\nBuilt Up area:...,2.0,North,10+ Year Old,NaN,"['Feng Shui / Vaastu Compliant', 'Natural Ligh...",NaN,6,5,2,Not Available,2400.04
1031,"3 Bedroom House for sale in Arera Colony, Bhopal",ag8 aakriti flamingo 3,arera colony,House,127.00,12700,Ready To Move,For sale 3 bhk duplex east facing in flamingo ...,Plot area 1000\n(92.9 sq.m.) \nsq.ft.,1.0,East,1 to 5 Year Old,"['3 Wardrobe', '1 Modular Kitchen', 'No AC', '...","['Water Storage', 'Park', 'Visitor Parking']",Park/Garden,3,3,2,Not Available,1000.00
1060,"2 BHK Flat in E 7 Arera colony, Bhopal",rachna kunj 01/313,e 7 arera colony,Flat,35.00,5384,Ready To Move,In the ground floor / front side / 11 no marke...,Carpet area: 650\n(60.39 sq.m.) \nsq.ft.,0.0,NaN,10+ Year Old,NaN,NaN,NaN,2,2,1,Not Available,650.07
1077,"4 Bedroom House for sale in Arera Hills, Bhopal",green meadows,arera hills,House,225.00,16071,Ready To Move,4 bhk ready to move in row house duplex in gre...,Plot area 1400\n(130.06 sq.m.)\nBuilt Up area:...,2.0,South,5 to 10 Year Old,NaN,"['No open drainage around', 'Security Personne...","Park/Garden,Club",4,3,3,Not Available,1400.04
1084,"4 Bedroom House for sale in E 7 Arera colony, ...",e 7 arera colony,e 7 arera colony,House,200.00,11111,Ready To Move,Best villa in arera colony bhopal,Plot area 1800\n(167.23 sq.m.) \nsq.ft.,2.0,West,5 to 10 Year Old,"['5 Fan', '3 Light', 'No AC', 'No Bed', 'No Ch...","['Feng Shui / Vaastu Compliant', 'Private Gard...","Pool,Others,Park/Garden,Club,Main Road",4,3,2,"pooja room,store room,study room,servant room",1800.02
1117,"5 BHK Flat in Arera Colony, Bhopal",ibd kings park,arera colony,Flat,75.00,3000,Ready To Move,Located in the popular residential address of ...,Carpet area: 2500\n(232.26 sq.m.) \nsq.ft.,5.0,East,0 to 1 Year Old,NaN,"['Power Back-up', 'Lift(s)', 'Swimming Pool', ...","Park/Garden,Main Road",5,4,3,Not Available,2500.00
1168,"2 BHK Flat in E 3 Arera Colony, Bhopal",nupurkunj,e 3 arera colony,Flat,55.00,5000,Ready To Move,This lovely 3 bhk apartment/flat in e 3 arera ...,Carpet area: 1100\n(102.19 sq.m.) \nsq.ft.,0.0,NaN,5 to 10 Year Old,"['1 Fan', '1 Exhaust Fan', '2 Light', '1 Modul...",NaN,NaN,2,2,2,Not Available,1100.00
1222,"1 Bedroom House for sale in Arera Colony, Bhopal",arera colony,arera colony,House,900.00,17708,Ready To Move,For sale independent bungalow in arera colony ...,Plot area 4000\n(371.61 sq.m.) \nsq.ft.,2.0,West,10+ Year Old,NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard...",Park/Garden,1,1,2,"pooja room,study room,servant room,store room",5082.45
1234,"3 Bedroom House for sale in E 6 Arera Colony, ...",e 6 arera colony,e 6 arera colony,House,125.00,13888,Ready To Move,Looking to buy an independent house in bhopal?...,Plot area 900\n(83.61 sq.m.) \nsq.ft.,1.0,West,10+ Year Old,"['4 Fan', '1 Exhaust Fan', '10 Light', '1 Modu...",['Visitor Parking'],Others,3,2,2,Not Available,900.06
1237,"5 Bedroom House for sale in E 5 Arera colony, ...",e 5 arera colony,e 5 arera colony,House,600.00,25000,Ready To Move,Wishing to settle down in an individual house ...,Plot area 2400\n(222.97 sq.m.) \nsq.ft.,2.0,North,10+ Year Old,NaN,NaN,Main Road,5,4,3,Not Available,2400.00
1270,"4 Bedroom House for sale in Arera Colony, Bhopal",dk devsthali,arera colony,House,135.00,11739,Ready To Move,It is a resale property in dk devsthali near d...,Plot area 1150\n(106.84 sq.m.) \nsq.ft.,2.0,West,10+ Year Old,"['1 Wardrobe', '1 Stove', '1 Modular Kitchen',...","['Feng Shui / Vaastu Compliant', 'Private Gard...","Park/Garden,Main Road,Club",4,4,1,"pooja room,study room,servant room,store room",1150.01
1311,"2 BHK Flat in Arera Colony, Bhopal",mirchandani shalimar enclave,arera colony,Flat,35.00,4375,Ready To Move,You own the terrace its private and also can i...,Carpet area: 800\n(74.32 sq.m.) \nsq.ft.,3.0,NaN,10+ Year Old,NaN,NaN,NaN,2,2,2,Not Available,800.00
1387,"2 Bedroom House for sale in E 3 Arera Colony, ...",e 3 arera colony,e 3 arera colony,House,325.00,21666,Ready To Move,"It is in arera colony e3 sector , near nationa...",Plot area 1500\n(139.35 sq.m.) \nsq.ft.,1.0,South,10+ Year Old,NaN,NaN,Park/Garden,2,2,0,Not Available,1500.05
1489,10 Bedroom House for sale in 10 No Stop Arera ...,10 no stop arera colony,10 no stop arera colony,House,1550.00,34444,Ready To Move,This 10 bhk house for sale in 10 no stop arera...,Plot area 4500\n(418.06 sq.m.) \nsq.ft.,2.0,East,1 to 5 Year Old,"['1 Water Purifier', '10 Fan', '1 Fridge', '1 ...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","Park/Garden,Main Road,Others",10,9,2,"servant room,study room,pooja room,store room",4500.06
1543,5 Bedroom House for sale in 1100 Quarters Arer...,1100 quarters arera colony,1100 quarters arera colony,House,165.00,9166,Ready To Move,Very good location arera colony,Plot area 1800\n(167.23 sq.m.) \nsq.ft.,2.0,East,5 to 10 Year Old,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...","['Private Garden / Terrace', 'Water Storage', ...",Park/Garden,5,4,2,"pooja room,study room",1800.13

In [1200]:
idx = [185,277,523,665,674,711,753,900,931,1028,1060,1084,1168,1234,1237,1387,1489,1543]
df.loc[idx, ['colony']] ='arera colony'

In [1201]:
df[df['colony'].str.contains('karond')]

,pname,society,colony,property_type,price_outer,price_per_sqft,possesion,description,Area,Total Floors,Facing,Property Age,furnishing,features,Overlooking,bedrooms,bathrooms,balconies,additional_room,area
70,"4 Bedroom House for sale in Karond, Bhopal",karond,karond,House,70.0,7000,Ready To Move,Property urgent sale karni hai lene wale hi co...,Plot area 1000\n(92.9 sq.m.) \nsq.ft.,2.0,West,1 to 5 Year Old,"['1 Bed', '6 Fan', '1 Sofa', '11 Light', '1 AC...",['Maintenance Staff'],"Park/Garden,Main Road",4,2,1,others,1000.00
132,"7 Bedroom House for sale in Karond, Bhopal",karond,karond,House,95.0,2111,Ready To Move,Wishing to settle down in an individual house ...,Built Up area: 4500\n(418.06 sq.m.) \nsq.ft.,3.0,NaN,NaN,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,NaN,7,6,0,Not Available,4500.24
218,"6 Bedroom House for sale in Karond, Bhopal",karond,karond,House,95.0,3958,Ready To Move,Do you wish to buy an independent house in kar...,Plot area 2400\n(222.97 sq.m.) \nsq.ft.,1.0,South,10+ Year Old,"['2 Wardrobe', '1 Modular Kitchen', 'No AC', '...",NaN,NaN,6,5,1,Not Available,2400.20
257,"3 BHK Flat in Karond, Bhopal",surya plaza,karond,Flat,35.0,3500,Ready To Move,We are the proud owners of this 3 bhk apartmen...,Super Built up area 1000\n(92.9 sq.m.) \nsq.ft.,1.0,NaN,1 to 5 Year Old,NaN,NaN,NaN,3,2,1,Not Available,1000.00
377,"2 Bedroom House for sale in Karond, Bhopal",elixir greens,karond,House,55.0,4761,Ready To Move,2 bhk + terrace in well maintained society. Id...,Plot area 1050\n(97.55 sq.m.) \nsq.ft.,1.0,NaN,5 to 10 Year Old,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Li...","['Feng Shui / Vaastu Compliant', 'Private Gard...",Park/Garden,2,2,2,Not Available,1155.22
410,"2 BHK Flat in Karond, Bhopal",dwarka dham society,karond,Flat,26.0,3527,Ready To Move,"Parking facility, secure colony, proper vantil...",Carpet area: 737\n(68.47 sq.m.) \nsq.ft.,3.0,East,1 to 5 Year Old,NaN,"['Security / Fire Alarm', 'Maintenance Staff',...",Others,2,2,2,Not Available,737.17
436,2 Bedroom House for sale in Karond bye pass ro...,karond bye pass road,karond bye pass road,House,60.0,4000,Ready To Move,Has borewell with submersible. Plus municipali...,Plot area 1500\n(139.35 sq.m.) \nsq.ft.,NaN,North-East,10+ Year Old,NaN,['Private Garden / Terrace'],NaN,2,2,1,Not Available,1500.00
549,"5 Bedroom House for sale in Karond Chouraha, B...",karond chouraha,karond chouraha,House,105.0,3088,Ready To Move,I am looking for buyer to purchase house/villa...,Built Up area: 3400\n(315.87 sq.m.) \nsq.ft.,4.0,NaN,0 to 1 Year Old,NaN,NaN,NaN,5,10,3,Not Available,3400.26
550,"3 Bedroom House for sale in Karond, Bhopal",karond,karond,House,35.0,2916,Ready To Move,Direct owner sell this property and good area.,Plot area 1200\n(111.48 sq.m.)\nBuilt Up area:...,1.0,NaN,10+ Year Old,NaN,NaN,NaN,3,2,0,Not Available,1200.27
554,"2 Bedroom House for sale in Karond, Bhopal",signature business park,karond,House,27.0,4500,Ready To Move,"The new bus stand is 1 kilometres, The shoppin...",Plot area 600\n(55.74 sq.m.)\nBuilt Up area: 6...,1.0,South-West,5 to 10 Year Old,"['1 Exhaust Fan', '1 Light', '1 Modular Kitche...",NaN,NaN,2,1,0,Not Available,600.00
632,"4 Bedroom House for sale in Karond, Bhopal",mp housing park colony,karond,House,40.0,4634,Ready To Move,I am looking for buyer to purchase house/villa...,Plot area 863\n(80.18 sq.m.) \nsq.ft.,2.0,North,1 to 5 Year Old,NaN,['Feng Shui / Vaastu Compliant'],Park/Garden,4,2,2,Not Available,863.19
663,"4 Bedroom House for sale in Karond, Bhopal",globus coral casa,karond,House,125.0,12413,Ready To Move,I have a house/villa available for sale in bha...,Plot area 1007\n(93.55 sq.m.) \nsq.ft.,2.0,NaN,5 to 10 Year Old,NaN,NaN,NaN,4,3,0,Not Available,1007.01
691,"3 Bedroom House for sale in Karond Chouraha, B...",karond chouraha,karond chouraha,House,210.0,26250,Ready To Move,Situated on ayodhya bypass road karond square ...,Plot area 800\n(74.32 sq.m.)\nBuilt Up area: 8...,2.0,South,10+ Year Old,NaN,NaN,Main Road,3,2,1,Not Available,800.00
723,"3 BHK Flat in Karond, Bhopal",globus coral casa,karond,Flat,35.0,3043,Ready To Move,We are the proud owners of this 3 bhk apartmen...,Built Up area: 1150\n(106.84 sq.m.) \nsq.ft.,1.0,NaN,0 to 1 Year Old,NaN,NaN,NaN,3,2,1,Not Available,1150.18
828,"3 Bedroom House for sale in Karond Chouraha, B...",karond chouraha,karond chouraha,House,25.0,5555,Ready To Move,We want to sale our home 450 sq feet x 2 floor...,Plot area 450\n(41.81 sq.m.) \nsq.ft.,2.0,South,0 to 1 Year Old,"['1 Fan', '1 Exhaust Fan', '1 Dining Table', '...","['Water Storage', 'Visitor Parking']",NaN,3,2,1,"pooja room,others",450.05
1106,"5 Bedroom House for sale in Karond, Bhopal",indus regency,karond,House,85.0,7391,Ready To Move,This 5 bhk house for sale in karond is an idea...,Carpet area: 1150\n(106.84 sq.m.) \nsq.ft.,3.0,North,NaN,"['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN,NaN,5,4,2,Not Available,1150.05
1227,"3 Bedroom House for sale in Karond, Bhopal",globus coral casa,karond,House,72.0,3557,Ready To Move,We have a house/villa available for sale in ka...,Plot area 1012\n(94.02 sq.m.)\nBuilt Up area: ...,1.0,NaN,5 to 10 Year Old,NaN,"['Private Garden / Terrace', 'Maintenance Staf...",Park/Garden,3,3,2,Not Available,2024.18
1295,"3 Bedroom House for sale in Karond, Bhopal",karond,karond,House,23.0,1533,Ready To Move,Best in class property available at karond loc...,Built Up area: 1500\n(139.35 sq.m.) \nsq.ft.,1.0,NaN,NaN,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,NaN,3,1,0,Not Available,1500.33
1347,"3 Bedroom House for sale in Karond, Bhopal",sweet home residency,karond,House,52.0,7222,Ready To Move,Only 1 units left luxury 3bhk duplex near peop...,Plot area 720\n(66.89 sq.m.)\nBuilt Up area: 1...,2.0,West,0 to 1 Year Old,NaN,"['False Ceiling Lighting', 'Water Storage']","Main Road,Others",3,2,1,Not Available,720.02
1368,"3 Bedroom House for sale in Karond, Bhopal",globus coral casa,karond,House,75.0,6944,Ready To Move,Independent house at best location and in best...,Plot area 1008\n(93.65 sq.m.) \nsq.ft.,2.0,West,5 to 10 Year Old,"['1 Bed', '2 Wardrobe', '3 Fan', '1 Exhaust Fa...","['Maintenance Staff', 'Visitor Parking']",NaN,3,3,2,Not Available,1080.07
1448,"2 Bedroom House for sale in Karond, Bhopal",karond,karond,House,18.0,3000,Ready To Move,Are you planning to buy your dream home? You c...,Built Up area: 600\n(55.74 sq.m.) \nsq.ft.,1.0,NaN,NaN,NaN,NaN,NaN,2,2,0,Not Available,600.00
1510,"10 Bedroom House for sale in Karond Chouraha, ...",karond chouraha,karond chouraha,House,200.0,5405,Ready To Move,This property is very close to bhopal first me...,Plot area 3700\n(343.74 sq.m.) \nsq.ft.,3.0,East,1 to 5 Year Old,NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard...",Main Road,10,8,3,Not Available,3700.28
1569,"5 Bedroom House for sale in Karond Chouraha, B...",karond chouraha,karond chouraha,House,62.0,7750,Ready To Move,"Open parking, near school, near hospital, near...",Plot area 800\n(74.32 sq.m.) \nsq.ft.,2.0,East,1 to 5 Year Old,"['1 Fan', '1 Light', 'No AC', 'No Bed', 'No Ch...",['Park'],"Main Road,Park/Garden",5,3,1,"pooja room,study room",800.00

In [1202]:
idx = [90,102,183,643,868,957,992,1229,1252,1271,1371,1492]
df.loc[idx, ['colony']] = 'ayodhya bypass'

In [1203]:
df[df['colony'].str.contains('misrod')]
df.loc[1279,['colony']] = 'misrod'

In [1204]:
df[df['colony'].str.contains('airport')]
df.loc[[269,564],['colony']] = 'airport road'

In [1205]:
idx = [436,549,691,828,1510,1569]
df.loc[idx, ['colony']] = 'karond'

In [1206]:
idx = df[df['colony'].str.contains('janki nagar')].index
df.loc[idx, ['colony']] = 'chuna bhatti'

In [1207]:
idx = df[df['colony'].str.contains('trilanga')].index
df.loc[idx, ['colony']] = 'shahpura'

In [1208]:
df[df['colony'].str.contains('shahpura')]
idx = [52,251,455,583,718,785,894]
df.loc[idx, ['colony']] = 'shahpura'

In [1209]:
df[df['colony'].str.contains('mp nagar')]
df.loc[713,['colony']] = 'mp nagar'

In [1210]:
df[df['colony'].str.contains('patel nagar')]
df.loc[64,['colony']] = 'patel nagar'

In [1211]:
idx = df[df['colony'].str.contains('airport') |df['colony'].str.contains('sanjeev nagar')].index
df.loc[idx,['colony']] = 'gandhinagar'

In [1212]:

idx = df[df['colony'].str.contains('danish kunj') | df['colony'].str.contains('rajharsh colony')| df['colony'].
str.contains('bairagarh chichali') |df['colony'].str.contains('gehun kheda')].index
df.loc[idx,['colony']] = 'gehu kheda'

In [1213]:
df['colony'].value_counts().shape

(270,)

In [1214]:
df['colony'].value_counts()

colony
kolar road                         127
hoshangabad road                   125
katara hills                        99
ayodhya bypass                      75
bawadia kalan                       75
misrod                              51
awadhpuri                           51
gandhinagar                         47
arera colony                        44
chuna bhatti                        35
salaiya                             34
bagmugaliya                         34
gehu kheda                          33
shahpura                            32
karond                              23
bypass road                         21
jatkhedi                            17
saket nagar                         16
shirdipuram                         16
kohefiza                            15
mahawadiya                          14
khajuri kalan                       13
ashoka garden                       13
indus towne                         12
mp nagar                            12
patel nagar                         12
tt nagar                            12
mandideep                           12
lambakheda                          10
idgah hills                          9
neelbad                              8
bagli                                8
gulmohar colony                      8
danish nagar                         8
nehru nagar                          7
rohit nagar                          7
sonagiri                             7
new minal residency                  7
nayapura                             6
govindpura                           6
lalghati                             6
jahangirabad                         6
shivaji nagar                        6
samardha                             6
bairagarh                            6
indrapuri                            6
gopal nagar                          6
kotra sultanabad                     6
mahabali nagar                       5
shahjahanabad                        5
vijay nagar                          5
shakti nagar                         5
bhanpur                              5
lalita nagar                         5
karamveer nagar                      5
laharpur                             5
barkhera pathani                     4
teela jamalpura                      4
kalpana nagar                        4
panchwati colony                     4
punjabi bagh                         4
aishbagh                             4
nariyalkheda                         4
ayodhya nagar                        4
new central jail                     3
peer gate area                       3
rachna nagar                         3
shiv sangam nagar                    3
borda                                3
bagsewaniya                          3
fatehgarh                            3
ruchi lifescape                      3
phanda kala                          3
lakherapura                          3
narayan nagar                        3
harshavardhan nagar                  3
sukhi sewania                        3
ibrahimpura                          3
katara                               3
rajat bihar colony                   3
parthsarthy enclave                  3
hinotiya alam                        3
vidisha road                         3
old subhash nagar colony             3
ratibad                              3
shri rameshwaram                     3
indra vihar colony                   3
gurunanak pura                       3
vidya nagar                          3
rasla khedi                          3
kalapani                             3
regal town                           3
barkhedi                             3
gautam nagar                         2
aradhana nagar                       2
navi bagh                            2
housing board colony                 2
talaiya                              2
new choksey nagar                    2
karariya sajidabad                   2
priyanka nagar                       2
singarcholi                          2
aashirwad colony                     2
pallavi nagar                        2
zone 1                               2
amrawad khurd                        2
bhel sangam colony                   2
shankracharya nagar                  2
sivoy                                2
sector b indrapuri                   2
sehore road                          2
bharat nagar, indrapuri              2
arvind vihar                         2
kunjan nagar phase 1                 2
bda colony                           2
peoples campus                       2
anand nagar                          2
bharati niketan                      2
sector c indrapuri                   2
tilak society                        2
gulmohar g3                          2
rajved colony                        2
chanakyapuri                         2
habib ganj                           2
semri kalan                          2
sankhedi                             2
mandakini colony                     2
jk road                              2
paraspar colony                      1
vineet kunj                          1
rasuliya pathar                      1
jayshree apartment                   1
kalyan bhiwandi                      1
raisen road                          1
chowki talaiya                       1
9b saket nagar                       1
arera hills                          1
crystal campus                       1
morga                                1
rusalli                              1
khushipura                           1
sant asharam nagar phase 3           1
vaishali nagar                       1
kamla nagar                          1
abbas nagar                          1
sant asharam nagar phase 2           1
prabhu nagar                         1
crystal                              1
hazrat nizamuddin colony             1
sai ram colony sai mandir            1
raghunath nagar                      1
berkheda                             1
bagh umrao dulha                     1
chitragupt nagar                     1
berkhedi kalan                       1
adarsh colony                        1
budhwara                             1
tilak nagar                          1
chandan nagar                        1
mungalia kot                         1
sarvadharam c sector                 1
malikhedi                            1
dwarka nagar                         1
kadambini                            1
bagh dilkusha                        1
transport nagar                      1
rajendra nagar                       1
bhojpur road                         1
sargam cinema                        1
chouksey nagar                       1
sai vihar colony                     1
peace valley-1, narela shankari      1
good shepherd colony                 1
firdous nagar                        1
isro colony                          1
aiims                                1
empire hights                        1
badwai                               1
ahmedpur kalan                       1
c sector shirdipuram                 1
akbarpur                             1
chola naka                           1
viswakarma nagar                     1
siddharth enclave                    1
barrai                               1
shymala hills                        1
sarvdharm                            1
mendua                               1
sajida nagar                         1
afkar colony                         1
shahid nagar colony                  1
jhagariya khurd                      1
hoshangabad                          1
suraj nagar                          1
akashganga colony                    1
chinar fortune city                  1
ratnagiri jaswant apartment          1
chobdarpura                          1
congress nagar                       1
ghora nakkas                         1
arwaliya                             1
jumerati                             1
professors colony                    1
rasipuram road                       1
peepalner                            1
golden city                          1
dr a s rao nagar colony              1
chopra kalan, vidisha road           1
ahinsa vihar colony                  1
khejrabaramad                        1
krishna nagar                        1
sourabh colony                       1
panchwati                            1
karod                                1
piplani                              1
semra                                1
naveen nagar                         1
coach factory                        1
gomti colony                         1
fine avenue phase 2                  1
khajuri                              1
noor mahal ashok colony              1
data colony                          1
malviya nagar                        1
dam kheda                            1
huzur                                1
bangrasia                            1
sagar eden garden                    1
pushpa nagar                         1
panchvati market                     1
shankar nagar                        1
kailash nagar                        1
new market                           1
sneh nagar                           1
eint khedi                           1
kamlesh nagar                        1
kolua kalan                          1
green city                           1
lumbini complex, mata mandir         1
sarvdharm colony                     1
ravidas nagar                        1
manak vihar                          1
indra nagar                          1
tulsi nagar                          1
mubarakpur square                    1
mathai nagar cto bairagarh           1
basant kunj                          1
gulabi nagar                         1
radha krishna colony                 1
neerja nagar                         1
rahul nagar mata mandir              1
chhatrapati nagar                    1
ibrahimganj                          1
rent out residential                 1
berasia                              1
minal residency                      1
jr lig colony                        1
old city                             1
industrial area                      1
lala lajpat rai colony               1
khajoori sadak                       1
sagar avenue                         1
nishatpura                           1
tilak nagar, bawadiya kalan          1
sector a rajeev nagar                1
laxmi nagar                          1
old subhash nagar                    1
chola rod                            1
nagarjun nagar                       1
jawahar chowk                        1
Name: count, dtype: int64

In [1215]:
#  bawadia kalan  ->  gulmohar colony , pallavi nagar,tilak nagar, bawadiya kalan
# nehru nagar -> tt nagar , kotra sultanabad
# rohit nagar -> bawadia kalan

# tt nagar , nehru nagar  , mp nagar shivaji nagar ,kotra sultanabad-> central bhopal , new market , harshavardhan nagar , aradhana nagar , zone 1 ,gautam nagar , jawahar chowk
#,tulsi nagar,
# lalgathi -> data colony, panchwati colony , indra vihar colony , singarcholi , tilak society
# patel nagar -> gopal nagar , nagarjun nagar
# piplanin -> sonagiri, indrapuri , anandnagar, karamveer nagar , kalpana nagar,anand nagar,laxmi nagar,ratnagiri jaswant apartment
# habib ganj -> saket nagar , sakti nagar , aiims , barkhera pathani , narayan nagar , bharati niketan
# jahagirabad , aish bagh , vijay nagar,
# gehu kheda -> mahabali nagar  , lalita nagar ,aashirwad colony , rajved colony
# idgah hills , koheziha, shahjahanabad , teela jamalpura,
#  bagmuliya -> laharpura , parthsarthy enclave , bagsewaniya , shri rameshwaram , arvind vihar , bhel sangam colony

# ayodhya nagar -> new minal residency,minal residency,chhatrapati nagar,sagar avenue
# govindpura , panjabi bagh , rachna nagar , old subhash nagar colony , old subhash nagar,industrial area
# karond ,bhanpur, nariyalkheda , rasla khedi , peoples campus , housing board colony , karod,radha krishna colony , berasia,peace valley-1, narela shankari,rusalli
# aish bagh  , jahagirabad , gurunanak pura , shankracharya nagar,lala lajpat rai colony , vijay nagar
# gandhinagar -> new central jail
# peer gate area -> lakherapura , fatehgarh , ibrahimpura , talaiya,old city,ibrahimganj
# awadhpuri -> shiv sangam nagar , regal town , amrawad khurd ,bda colony
# misrod -> ruchi lifescape , katara
# outside bhopal -> sukhi sewania , phanda kala , borda , kalapani  , semri kalan,mubarakpur square
# neelbad -> barkhedi , ratibad
# mandideep -> vidya nagar , samardha
# salaiya -> hinotiya alam , sankhedi
# navi bagh -> new choksey nagar , lambakheda , navi bagh
# semra -> karariya sajidabad
# bairagarh -> priyanka nagar
# shahpure -> gulmohar g3  , sivoy  , mandakini colony
# chhunbatti -> chanakyapuri
# bangrasia ->

In [1216]:
idx = df[df['colony'].str.contains('kohefiza')].index
df.loc[idx,['colony']] = 'idgah hills'

In [1217]:
idx = df[df['colony'].str.contains('danish nagar') | df['colony'].str.contains('rajat bihar colony') | df['colony'].str.contains('kunjan nagar phase 1') ].index
df.loc[idx,['colony']] = 'bagmugaliya'

In [1218]:
idx = df[df['colony'].str.contains('jatkhedi') | df['colony'].str.contains('bagli') | df['colony'].str.contains('indus towne') ].index
df.loc[idx,['colony']] = 'misrod'

In [1219]:
idx = df[df['colony'].str.contains('gulmohar colony') | df['colony'].str.contains('rohit nagar')].index
df.loc[idx,['colony']] = 'bawadia kalan'

In [1220]:
idx = df[df['colony'].str.contains('tt nagar') | df['colony'].str.contains('nehru nagar') | df['colony'].str.contains('mp nagar') | df['colony'].str.contains('shivaji nagar') | df['colony'].str.contains('arera hill') | df['colony'].str.contains('new market') | df['colony'].str.contains('kotra sultanabad')].index
df.loc[idx,['colony']] = 'central bhopal'

In [1221]:
idx = df[df['colony'].str.contains('nayapura') | df['colony'].str.contains('data colony')].index
df.loc[idx,['colony']] = 'lalghati'

In [1222]:
idx = df[df['colony'].str.contains('gopal nagar')].index
df.loc[idx,['colony']] = 'patel nagar'

In [1223]:
idx = df[df['colony'].str.contains('saket nagar') | df['colony'].str.contains('shakti') | df['colony'].str.contains('aiims') ].index
df.loc[idx,['colony']] = 'habib ganj'

In [1224]:
idx = df[df['colony'].str.contains('sonagiri') | df['colony'].str.contains('indrapuri') | df['colony'].str.contains('anandnagar') ].index
df.loc[idx,['colony']] = 'piplani'

In [1225]:
#  bawadia kalan  ->  gulmohar colony , pallavi nagar,tilak nagar, bawadiya kalan
idx = df[df['colony'].str.contains('gulmohar colony') | df['colony'].str.contains('pallavi nagar') | df['colony'].str.contains('tilak nagar') | df['colony'].str.contains('bawadiya kalan') ].index
df.loc[idx,['colony']] = 'bawadia kalan'

In [1226]:
# tt nagar , nehru nagar  , mp nagar shivaji nagar ,kotra sultanabad-> central bhopal , newmarket , harshavardhan nagar , aradhana nagar , zone 1 ,gautam nagar , jawahar chowk,tulsi nagar,
idx = df[df['colony'].str.contains('tt nagar') | df['colony'].str.contains('nehru nagar') | df['colony'].str.contains('mp nagar') | df['colony'].str.contains('shivaji nagar')
| df['colony'].str.contains('kotra sultanabad') | df['colony'].str.contains('new market') | df['colony'].str.contains('harshavardhan nagar') | df['colony'].str.contains('aradhana nagar')
| df['colony'].str.contains('zone 1')
| df['colony'].str.contains('gautam nagar')
| df['colony'].str.contains('jawahar chowk')| df['colony'].str.contains('tulsi nagar')

].index
df.loc[idx,['colony']] = 'central bhopal'

In [1227]:
# lalgathi -> data colony, panchwati colony , indra vihar colony , singarcholi , tilak society
idx = df[df['colony'].str.contains('data colony') | df['colony'].str.contains('panchwati colony') | df['colony'].str.contains('indra vihar colony') | df['colony'].str.contains('singarcholi')
| df['colony'].str.contains('tilak society')  | df['colony'].str.contains('lalghati')].index
df.loc[idx,['colony']] = 'lalgathi'

In [1228]:
# patel nagar -> gopal nagar , nagarjun nagar
idx = df[df['colony'].str.contains('gopal nagar') | df['colony'].str.contains('nagarjun nagar')].index
df.loc[idx,['colony']] = 'patel nagar'

In [1229]:
# piplanin -> sonagiri, indrapuri , anandnagar, karamveer nagar , kalpana nagar,anand nagar,laxmi nagar,ratnagiri jaswant apartment
idx = df[df['colony'].str.contains('sonagiri') | df['colony'].str.contains('indrapuri') | df['colony'].str.contains('anandnagar') | df['colony'].str.contains('karamveer nagar')
| df['colony'].str.contains('kalpana nagar') | df['colony'].str.contains('anand nagar') | df['colony'].str.contains('laxmi nagar')
| df['colony'].str.contains('ratnagiri jaswant apartment')
].index
df.loc[idx,['colony']] = 'piplani'

In [1230]:
# habib ganj -> saket nagar , sakti nagar , aiims , barkhera pathani , narayan nagar , bharati niketan
idx = df[df['colony'].str.contains('saket nagar') | df['colony'].str.contains('sakti nagar') | df['colony'].str.contains('aiims') | df['colony'].str.contains('barkhera pathani')
| df['colony'].str.contains('narayan nagar') | df['colony'].str.contains('bharati niketan')
].index
df.loc[idx,['colony']] = 'habib ganj'

In [1231]:
# # aish bagh  ,jahangirabad ,jahagirabad , gurunanak pura , shankracharya nagar,lala lajpat rai colony , vijay nagar
idx = df[df['colony'].str.contains('aish bagh') | df['colony'].str.contains('jahagirabad') | df['colony'].str.contains('vijay nagar') | df['colony'].str.contains('gurunanak pura') | df['colony'].str.contains('shankracharya nagar')
| df['colony'].str.contains('lala lajpat rai colony') | df['colony'].str.contains('jahangirabad') | df['colony'].str.contains('vijay nagar') ].index
df.loc[idx,['colony']] = 'aishbagh'

In [1232]:
# gandhinagar -> new central jail , abbas nagar , dwarka
idx = df[df['colony'].str.contains('new central jail') | df['colony'].str.contains('abbas nagar') |  df['colony'].str.contains('dwarka')].index
df.loc[idx,['colony']] = 'gandhinagar'

In [1233]:
# peer gate area -> lakherapura , fatehgarh , ibrahimpura , talaiya,old city,ibrahimganj
idx = df[df['colony'].str.contains('lakherapura') | df['colony'].str.contains('fatehgarh') | df['colony'].str.contains('ibrahimpura') | df['colony'].str.contains('talaiya')
| df['colony'].str.contains('old city') | df['colony'].str.contains('ibrahimganj')].index
df.loc[idx,['colony']] = 'peer gate area'

In [1234]:
# awadhpuri -> shiv sangam nagar , regal town , amrawad khurd ,bda colony
idx = df[df['colony'].str.contains('shiv sangam nagar') | df['colony'].str.contains('regal town') | df['colony'].str.contains('amrawad khurd') | df['colony'].str.contains('bda colony')].index
df.loc[idx,['colony']] = 'awadhpuri'

In [1235]:
# misrod -> ruchi lifescape , katara
idx = df[df['colony'].str.contains('ruchi lifescape') | (df['colony']=='katara')].index
df.loc[idx,['colony']] = 'misrod'

In [1236]:
# outside bhopal -> sukhi sewania , phanda kala , borda , kalapani  , semri kalan,mubarakpur square
idx = df[df['colony'].str.contains('sukhi sewania') | df['colony'].str.contains('phanda kala') | df['colony'].str.contains('borda') | df['colony'].str.contains('kalapani') |
df['colony'].str.contains('semri kalan') | df['colony'].str.contains('mubarakpur square')
].index
df.loc[idx,['colony']]  = 'outside bhopal'

In [1237]:
# neelbad -> barkhedi , ratibad
idx = df[df['colony'].str.contains('barkhedi') | df['colony'].str.contains('ratibad')].index
df.loc[idx,['colony']] = 'neelbad'

In [1238]:
# mandideep -> vidya nagar , samardha
idx = df[df['colony'].str.contains('vidya nagar') | df['colony'].str.contains('samardha')].index
df.loc[idx,['colony']] = 'mandideep'

In [1239]:
# salaiya -> hinotiya alam , sankhedi
idx = df[df['colony'].str.contains('hinotiya alam') | df['colony'].str.contains('sankhedi')].index
df.loc[idx,['colony']] = 'salaiya'

In [1240]:
# navi bagh -> new choksey nagar , lambakheda , navi bagh
idx = df[df['colony'].str.contains('new choksey nagar') | df['colony'].str.contains('lambakheda') | df['colony'].str.contains('navi bagh')].index
df.loc[idx,['colony']] = 'navi bagh'

In [1241]:
# semra -> karariya sajidabad
idx = df[df['colony'].str.contains('karariya') | df['colony'].str.contains('sajidabad')].index
df.loc[idx,['colony']] = 'semra'

In [1242]:
# bairagarh -> priyanka nagar
idx = df[df['colony'].str.contains('priyanka nagar')].index
df.loc[idx,['colony']] = 'bairagarh'

In [1243]:
# shahpure -> gulmohar g3  , sivoy  , mandakini colony
idx = df[df['colony'].str.contains('gulmohar g3') | df['colony'].str.contains('sivoy') | df['colony'].str.contains('mandakini colony') | df['colony'].str.contains('shahpure')].index
df.loc[idx,['colony']] = 'shahpura'

In [1244]:
# chhunbatti -> chanakyapuri
idx = df[df['colony'].str.contains('chanakyapuri') | df['colony'].str.contains('chhunbatti')].index
df.loc[idx,['colony']] = 'chuna bhatti'

In [1245]:
df['colony'].value_counts().shape

(181,)

In [1246]:
df['colony'].value_counts()

colony
kolar road                         127
hoshangabad road                   125
katara hills                        99
bawadia kalan                       94
misrod                              94
ayodhya bypass                      75
awadhpuri                           61
central bhopal                      56
gandhinagar                         52
bagmugaliya                         47
arera colony                        44
salaiya                             39
shahpura                            38
chuna bhatti                        37
habib ganj                          34
piplani                             33
gehu kheda                          33
lalgathi                            24
idgah hills                         24
karond                              23
mandideep                           21
aishbagh                            21
bypass road                         21
patel nagar                         19
peer gate area                      17
shirdipuram                         16
outside bhopal                      15
navi bagh                           14
neelbad                             14
mahawadiya                          14
khajuri kalan                       13
ashoka garden                       13
bairagarh                            8
new minal residency                  7
govindpura                           6
mahabali nagar                       5
lalita nagar                         5
shahjahanabad                        5
laharpur                             5
bhanpur                              5
teela jamalpura                      4
ayodhya nagar                        4
nariyalkheda                         4
punjabi bagh                         4
old subhash nagar colony             3
rasla khedi                          3
rachna nagar                         3
shri rameshwaram                     3
vidisha road                         3
parthsarthy enclave                  3
bagsewaniya                          3
semra                                3
peoples campus                       2
aashirwad colony                     2
bhel sangam colony                   2
arvind vihar                         2
housing board colony                 2
sehore road                          2
jk road                              2
rajved colony                        2
crystal campus                       1
jayshree apartment                   1
hoshangabad                          1
shahid nagar colony                  1
berkhedi kalan                       1
c sector shirdipuram                 1
akbarpur                             1
chitragupt nagar                     1
raghunath nagar                      1
chola naka                           1
hazrat nizamuddin colony             1
viswakarma nagar                     1
crystal                              1
siddharth enclave                    1
shymala hills                        1
prabhu nagar                         1
isro colony                          1
sarvdharm                            1
mendua                               1
sant asharam nagar phase 3           1
khushipura                           1
kalyan bhiwandi                      1
kamla nagar                          1
vineet kunj                          1
morga                                1
sant asharam nagar phase 2           1
jhagariya khurd                      1
mungalia kot                         1
chandan nagar                        1
berkheda                             1
sai ram colony sai mandir            1
rusalli                              1
vaishali nagar                       1
raisen road                          1
rasuliya pathar                      1
paraspar colony                      1
adarsh colony                        1
budhwara                             1
afkar colony                         1
sajida nagar                         1
barrai                               1
ahmedpur kalan                       1
badwai                               1
neerja nagar                         1
empire hights                        1
firdous nagar                        1
sarvadharam c sector                 1
malikhedi                            1
kadambini                            1
bagh dilkusha                        1
transport nagar                      1
sargam cinema                        1
sai vihar colony                     1
peace valley-1, narela shankari      1
rajendra nagar                       1
good shepherd colony                 1
chouksey nagar                       1
bhojpur road                         1
panchwati                            1
berasia                              1
radha krishna colony                 1
dr a s rao nagar colony              1
peepalner                            1
rasipuram road                       1
jumerati                             1
suraj nagar                          1
arwaliya                             1
ghora nakkas                         1
congress nagar                       1
chobdarpura                          1
chinar fortune city                  1
akashganga colony                    1
krishna nagar                        1
professors colony                    1
sourabh colony                       1
panchvati market                     1
pushpa nagar                         1
sagar eden garden                    1
bangrasia                            1
huzur                                1
dam kheda                            1
malviya nagar                        1
noor mahal ashok colony              1
karod                                1
khajuri                              1
fine avenue phase 2                  1
gomti colony                         1
coach factory                        1
naveen nagar                         1
golden city                          1
chopra kalan, vidisha road           1
gulabi nagar                         1
ahinsa vihar colony                  1
basant kunj                          1
mathai nagar cto bairagarh           1
manak vihar                          1
sneh nagar                           1
ravidas nagar                        1
sarvdharm colony                     1
lumbini complex, mata mandir         1
green city                           1
kolua kalan                          1
kamlesh nagar                        1
eint khedi                           1
rahul nagar mata mandir              1
chhatrapati nagar                    1
rent out residential                 1
chola rod                            1
old subhash nagar                    1
sector a rajeev nagar                1
nishatpura                           1
sagar avenue                         1
khajoori sadak                       1
industrial area                      1
jr lig colony                        1
minal residency                      1
indra nagar                          1
kailash nagar                        1
shankar nagar                        1
khejrabaramad                        1
bagh umrao dulha                     1
Name: count, dtype: int64

In [1247]:
# gehu kheda -> mahabali nagar  , lalita nagar ,aashirwad colony , rajved colony
# idgah hills , koheziha, shahjahanabad , teela jamalpura,
#  bagmuliya -> laharpura , parthsarthy enclave , bagsewaniya , shri rameshwaram , arvind vihar , bhel sangam colony

# ayodhya nagar -> new minal residency,minal residency,chhatrapati nagar,sagar avenue
# govindpura , panjabi bagh , rachna nagar , old subhash nagar colony , old subhash nagar,industrial area
# karond ,bhanpur, nariyalkheda , rasla khedi , peoples campus , housing board colony , karod,radha krishna colony , berasia,peace valley-1, narela shankari,rusalli
#

In [1248]:
# gehu kheda -> mahabali nagar  , lalita nagar ,aashirwad colony , rajved colony
idx = df[df['colony'].str.contains('mahabali nagar') | df['colony'].str.contains('lalita nagar') | df['colony'].str.contains('aashirwad colony') | 
df['colony'].str.contains('rajved colony') | df['colony'].str.contains('gehun kheda') ].index
df.loc[idx,['colony']]  = 'gehu kheda'

In [1249]:
# idgah hills , koheziha, shahjahanabad , teela jamalpura
idx = df[df['colony'].str.contains('idgah hills') | df['colony'].str.contains('koheziha') | df['colony'].str.contains('shahjahanabad') | 
df['colony'].str.contains('teela jamalpura') ].index
df.loc[idx,['colony']]  = 'shahjahanabad'

In [1250]:
#  bagmuliya -> laharpur , parthsarthy enclave , bagsewaniya , shri rameshwaram , arvind vihar , bhel sangam colony
idx = df[df['colony'].str.contains('laharpur') | df['colony'].str.contains('parthsarthy enclave') | df['colony'].str.contains('bagsewaniya') | 
df['colony'].str.contains('shri rameshwaram') | df['colony'].str.contains('arvind vihar') | df['colony'].str.contains('bhel sangam colony')  
| df['colony'].str.contains('sant asharam nagar')].index
df.loc[idx,['colony']] = 'bagmuliya'

In [1251]:
# ayodhya nagar -> new minal residency,minal residency,chhatrapati nagar,sagar avenue
idx = df[df['colony'].str.contains('new minal residency') | df['colony'].str.contains('minal residency') | df['colony'].str.contains('chhatrapati nagar') | 
df['colony'].str.contains('sagar avenue')].index
df.loc[idx,['colony']] = 'ayodhya nagar'

In [1252]:
# govindpura , panjabi bagh , rachna nagar , old subhash nagar colony , old subhash nagar,industrial area
idx = df[df['colony'].str.contains('punjabi') | df['colony'].str.contains('rachna nagar') | df['colony'].str.contains('old subhash nagar colony') | 
df['colony'].str.contains('old subhash nagar') | df['colony'].str.contains('industrial area')].index
df.loc[idx,['colony']] = 'govindpura'

In [1253]:
# karond ,bhanpur, nariyalkheda , rasla khedi , peoples campus , housing board colony , karod,radha krishna colony , berasia,peace valley-1, narela shankari,rusalli
idx = df[df['colony'].str.contains('karod') | df['colony'].str.contains('bhanpur') | df['colony'].str.contains('nariyalkheda') | 
df['colony'].str.contains('rasla khedi') | df['colony'].str.contains('peoples campus') | df['colony'].str.contains('housing board colony')
| df['colony'].str.contains('radha krishna colony')
| df['colony'].str.contains('berasia') | df['colony'].str.contains('peace valley-1') | df['colony'].str.contains('narela shankari') 
| df['colony'].str.contains('rusalli')].index
df.loc[idx,['colony']] = 'karond'

In [1254]:
# shirdipuram
idx = df[df['colony'].str.contains('shirdipuram') ].index
df.loc[idx,['colony']] = 'shirdipuram'

In [1255]:
df['colony'].value_counts().shape

(148,)

In [1256]:
df['colony'].value_counts()

colony
kolar road                      127
hoshangabad road                125
katara hills                     99
bawadia kalan                    94
misrod                           94
ayodhya bypass                   75
awadhpuri                        61
central bhopal                   56
gandhinagar                      52
bagmugaliya                      47
gehu kheda                       47
arera colony                     44
karond                           44
salaiya                          39
shahpura                         38
chuna bhatti                     37
habib ganj                       34
piplani                          33
shahjahanabad                    33
lalgathi                         24
mandideep                        21
aishbagh                         21
bypass road                      21
bagmuliya                        20
patel nagar                      19
govindpura                       18
shirdipuram                      17
peer gate area                   17
outside bhopal                   15
ayodhya nagar                    14
mahawadiya                       14
neelbad                          14
navi bagh                        14
khajuri kalan                    13
ashoka garden                    13
bairagarh                         8
vidisha road                      3
semra                             3
sehore road                       2
jk road                           2
siddharth enclave                 1
vineet kunj                       1
chola naka                        1
isro colony                       1
viswakarma nagar                  1
shymala hills                     1
akbarpur                          1
sarvdharm                         1
mendua                            1
kamla nagar                       1
jhagariya khurd                   1
jayshree apartment                1
crystal campus                    1
morga                             1
kalyan bhiwandi                   1
khushipura                        1
prabhu nagar                      1
crystal                           1
hazrat nizamuddin colony          1
chandan nagar                     1
raghunath nagar                   1
chitragupt nagar                  1
berkhedi kalan                    1
shahid nagar colony               1
hoshangabad                       1
mungalia kot                      1
ahmedpur kalan                    1
bhojpur road                      1
neerja nagar                      1
berkheda                          1
sai ram colony sai mandir         1
vaishali nagar                    1
raisen road                       1
rasuliya pathar                   1
paraspar colony                   1
adarsh colony                     1
budhwara                          1
afkar colony                      1
sajida nagar                      1
barrai                            1
badwai                            1
chouksey nagar                    1
empire hights                     1
firdous nagar                     1
sarvadharam c sector              1
malikhedi                         1
kadambini                         1
bagh dilkusha                     1
transport nagar                   1
sargam cinema                     1
sai vihar colony                  1
rajendra nagar                    1
good shepherd colony              1
panchwati                         1
indra nagar                       1
gulabi nagar                      1
rasipuram road                    1
suraj nagar                       1
arwaliya                          1
ghora nakkas                      1
congress nagar                    1
chobdarpura                       1
chinar fortune city               1
akashganga colony                 1
krishna nagar                     1
professors colony                 1
sourabh colony                    1
panchvati market                  1
pushpa nagar                      1
sagar eden garden                 1
bangrasia                         1
huzur                             1
dam kheda                         1
malviya nagar                     1
noor mahal ashok colony           1
khajuri                           1
fine avenue phase 2               1
gomti colony                      1
coach factory                     1
naveen nagar                      1
jumerati                          1
peepalner                         1
basant kunj                       1
golden city                       1
mathai nagar cto bairagarh        1
manak vihar                       1
sneh nagar                        1
ravidas nagar                     1
sarvdharm colony                  1
lumbini complex, mata mandir      1
green city                        1
kolua kalan                       1
kamlesh nagar                     1
eint khedi                        1
rahul nagar mata mandir           1
rent out residential              1
chola rod                         1
sector a rajeev nagar             1
nishatpura                        1
khajoori sadak                    1
jr lig colony                     1
kailash nagar                     1
shankar nagar                     1
khejrabaramad                     1
ahinsa vihar colony               1
chopra kalan, vidisha road        1
dr a s rao nagar colony           1
bagh umrao dulha                  1
Name: count, dtype: int64

In [1257]:
idx = df[df['colony'].apply(lambda x :(df['colony'] == x).sum()<5)].index
df.loc[idx,['colony']] = 'bhopal'

In [1258]:
df['colony'].value_counts().shape

(37,)

In [1259]:
df['colony'].value_counts()

colony
kolar road          127
hoshangabad road    125
bhopal              118
katara hills         99
bawadia kalan        94
misrod               94
ayodhya bypass       75
awadhpuri            61
central bhopal       56
gandhinagar          52
bagmugaliya          47
gehu kheda           47
karond               44
arera colony         44
salaiya              39
shahpura             38
chuna bhatti         37
habib ganj           34
shahjahanabad        33
piplani              33
lalgathi             24
bypass road          21
aishbagh             21
mandideep            21
bagmuliya            20
patel nagar          19
govindpura           18
shirdipuram          17
peer gate area       17
outside bhopal       15
navi bagh            14
ayodhya nagar        14
neelbad              14
mahawadiya           14
ashoka garden        13
khajuri kalan        13
bairagarh             8
Name: count, dtype: int64

In [1260]:
df.head()

,pname,society,colony,property_type,price_outer,price_per_sqft,possesion,description,Area,Total Floors,Facing,Property Age,furnishing,features,Overlooking,bedrooms,bathrooms,balconies,additional_room,area
0,"7 Bedroom House for sale in Jhagariya Khurd, B...",sage suncity,bhopal,House,105.0,3750,Ready To Move,Planning to buy an individual house in bhopal....,Built Up area: 2800\n(260.13 sq.m.) \nsq.ft.,1.0,NaN,NaN,NaN,NaN,NaN,7,5,0,Not Available,2800.00
1,"3 BHK Flat in Kolar Road, Bhopal",danish hills view,kolar road,Flat,85.0,6508,Ready To Move,3bhk spacious flat available for sale at kolar...,Carpet area: 1306\n(121.33 sq.m.) \nsq.ft.,2.0,North,0 to 1 Year Old,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...",Park/Garden,3,3,1,pooja room with view floor plan,1306.08
2,"2 BHK Flat in Katara Hills, Bhopal",narmada prem kesar,katara hills,Flat,25.0,2173,Ready To Move,This location is very attractive and near main...,Super Built up area 1150\n(106.84 sq.m.)\nCarp...,3.0,West,1 to 5 Year Old View Construction Status,NaN,"['Feng Shui / Vaastu Compliant', 'Lift(s)', 'M...","Park/Garden,Main Road",2,2,3,Not Available,1150.48
3,"8 Bedroom House for sale in Gurunanak Pura, Bh...",gurunanak pura independent house,aishbagh,House,65.0,5909,Ready To Move,Central bhopal location near by all facilities...,Plot area 1100\n(102.19 sq.m.)\nBuilt Up area:...,2.0,West,10+ Year Old,"['1 Water Purifier', '12 Fan', '1 Geyser', '22...","['Feng Shui / Vaastu Compliant', 'Private Gard...",Main Road,8,5,1,pooja room,1100.02
4,"6 Bedroom House for sale in Chuna Bhatti, Bhopal",chuna bhatti,chuna bhatti,House,650.0,16250,Ready To Move,Check out this 6 bhk house for sale in chuna b...,Plot area 4000\n(371.61 sq.m.) \nsq.ft.,3.0,NaN,1 to 5 Year Old,"['1 Water Purifier', '1 Fan', '1 Exhaust Fan',...",NaN,NaN,6,6,2,"pooja room,study room,servant room,store room",4000.00

In [1261]:
# feature engineering required -> possesion,Area, additionalRoom, facing, propertyage, furnish, features

In [1262]:
df.duplicated().sum()

0

In [1263]:
df.to_csv('BPL_cleaned_l3_v1.csv',index=False)
df.to_excel('BPL_cleaned_l3_v1.xlsx',index=False)