In [1]:
import pandas as pd 
import numpy as np

In [33]:
pd.set_option('display.max_columns',None)

In [7]:
df = pd.read_csv('BPL_feature_engineered_v1.csv')

In [8]:
df.shape

(1580, 23)

In [6]:
df.head()

,society,colony,property_type,price_outer,price_per_sqft,Total Floors,Facing,bedrooms,bathrooms,balconies,...,effective_area_sqft,study room,servant room,store room,pooja room,others,view floor plan,furnishing_type,luxury_score,Overlooking_Categories
0,sage suncity,bhopal,House,105.0,3750,1.0,NaN,7,5,0,...,NaN,0,0,0,0,0,0,1,71,Green View Homes
1,danish hills view,kolar road,Flat,85.0,6508,2.0,North,3,3,1,...,NaN,0,0,0,1,0,1,1,35,Green View Homes
2,narmada prem kesar,katara hills,Flat,25.0,2173,3.0,West,2,2,3,...,1150.0,0,0,0,0,0,0,1,15,Green View Homes
3,gurunanak pura independent house,aishbagh,House,65.0,5909,2.0,West,8,5,1,...,1100.0,0,0,0,1,0,0,0,18,Road Facing Homes
4,chuna bhatti,chuna bhatti,House,650.0,16250,3.0,NaN,6,6,2,...,4000.0,1,1,1,1,0,0,2,10,Road Facing Homes

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1580 entries, 0 to 1579
Data columns (total 23 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   society                 1576 non-null   object
 1   colony                  1580 non-null   object
 2   property_type           1580 non-null   object
 3   price_outer             1580 non-null   float64
 4   price_per_sqft          1580 non-null   int64
 5   Total Floors            1546 non-null   float64
 6   Facing                  876 non-null    object
 7   bedrooms                1580 non-null   int64
 8   bathrooms               1580 non-null   int64
 9   balconies               1580 non-null   int64
 10  area                    1580 non-null   float64
 11  built_up_area           450 non-null    float64
 12  carpet_area             655 non-null    float64
 13  effective_area_sqft     1095 non-null   float64
 14  study room              1580 non-null   int64
 15  servant room            1580 non-null   int64
 16  store room              1580 non-null   int64
 17  pooja room              1580 non-null   int64
 18  others                  1580 non-null   int64
 19  view floor plan         1580 non-null   int64
 20  furnishing_type         1580 non-null   int64
 21  luxury_score            1580 non-null   int64
 22  Overlooking_Categories  1580 non-null   object
dtypes: float64(6), int64(12), object(5)
memory usage: 284.0+ KB

In [37]:
df.head()

,society,colony,property_type,price_outer,price_per_sqft,Total Floors,Facing,bedrooms,bathrooms,balconies,area,built_up_area,carpet_area,effective_area_sqft,study room,servant room,store room,pooja room,others,view floor plan,furnishing_type,luxury_score,Overlooking_Categories
0,sage suncity,bhopal,House,105.0,3750,1.0,NaN,7,5,0,2800.00,2800.0,NaN,NaN,0,0,0,0,0,0,1,71,Green View Homes
1,danish hills view,kolar road,Flat,85.0,6508,2.0,North,3,3,1,1306.08,NaN,1306.0,NaN,0,0,0,1,0,1,1,35,Green View Homes
2,narmada prem kesar,katara hills,Flat,25.0,2173,3.0,West,2,2,3,1150.48,NaN,850.0,1150.0,0,0,0,0,0,0,1,15,Green View Homes
3,gurunanak pura independent house,aishbagh,House,65.0,5909,2.0,West,8,5,1,1100.02,2400.0,2200.0,1100.0,0,0,0,1,0,0,0,18,Road Facing Homes
4,chuna bhatti,chuna bhatti,House,650.0,16250,3.0,NaN,6,6,2,4000.00,NaN,NaN,4000.0,1,1,1,1,0,0,2,10,Road Facing Homes

In [38]:
def Area(data):
    if not pd.isnull(data['built_up_area']):
        return data['built_up_area']
    elif not pd.isnull(data['carpet_area']):
        return data['carpet_area']
    else:
        return data['effective_area_sqft']

In [39]:
area = df[['built_up_area','carpet_area','effective_area_sqft']].apply(Area,axis=1)
df.insert(11,'mainarea',area)

In [40]:
df.head()

,society,colony,property_type,price_outer,price_per_sqft,Total Floors,Facing,bedrooms,bathrooms,balconies,area,mainarea,built_up_area,carpet_area,effective_area_sqft,study room,servant room,store room,pooja room,others,view floor plan,furnishing_type,luxury_score,Overlooking_Categories
0,sage suncity,bhopal,House,105.0,3750,1.0,NaN,7,5,0,2800.00,2800.0,2800.0,NaN,NaN,0,0,0,0,0,0,1,71,Green View Homes
1,danish hills view,kolar road,Flat,85.0,6508,2.0,North,3,3,1,1306.08,1306.0,NaN,1306.0,NaN,0,0,0,1,0,1,1,35,Green View Homes
2,narmada prem kesar,katara hills,Flat,25.0,2173,3.0,West,2,2,3,1150.48,850.0,NaN,850.0,1150.0,0,0,0,0,0,0,1,15,Green View Homes
3,gurunanak pura independent house,aishbagh,House,65.0,5909,2.0,West,8,5,1,1100.02,2400.0,2400.0,2200.0,1100.0,0,0,0,1,0,0,0,18,Road Facing Homes
4,chuna bhatti,chuna bhatti,House,650.0,16250,3.0,NaN,6,6,2,4000.00,4000.0,NaN,NaN,4000.0,1,1,1,1,0,0,2,10,Road Facing Homes

In [43]:
price = (df['mainarea']  * df['price_per_sqft']) / 100000
df.insert(4,'price',price)

In [44]:
df.head()

,society,colony,property_type,price_outer,price,price_per_sqft,Total Floors,Facing,bedrooms,bathrooms,balconies,area,mainarea,built_up_area,carpet_area,effective_area_sqft,study room,servant room,store room,pooja room,others,view floor plan,furnishing_type,luxury_score,Overlooking_Categories
0,sage suncity,bhopal,House,105.0,105.00000,3750,1.0,NaN,7,5,0,2800.00,2800.0,2800.0,NaN,NaN,0,0,0,0,0,0,1,71,Green View Homes
1,danish hills view,kolar road,Flat,85.0,84.99448,6508,2.0,North,3,3,1,1306.08,1306.0,NaN,1306.0,NaN,0,0,0,1,0,1,1,35,Green View Homes
2,narmada prem kesar,katara hills,Flat,25.0,18.47050,2173,3.0,West,2,2,3,1150.48,850.0,NaN,850.0,1150.0,0,0,0,0,0,0,1,15,Green View Homes
3,gurunanak pura independent house,aishbagh,House,65.0,141.81600,5909,2.0,West,8,5,1,1100.02,2400.0,2400.0,2200.0,1100.0,0,0,0,1,0,0,0,18,Road Facing Homes
4,chuna bhatti,chuna bhatti,House,650.0,650.00000,16250,3.0,NaN,6,6,2,4000.00,4000.0,NaN,NaN,4000.0,1,1,1,1,0,0,2,10,Road Facing Homes

In [49]:
df[(df['price'] - df['price_outer']) > 1]

,society,colony,property_type,price_outer,price,price_per_sqft,Total Floors,Facing,bedrooms,bathrooms,balconies,area,mainarea,built_up_area,carpet_area,effective_area_sqft,study room,servant room,store room,pooja room,others,view floor plan,furnishing_type,luxury_score,Overlooking_Categories
3,gurunanak pura independent house,aishbagh,House,65.0,141.81600,5909,2.0,West,8,5,1,1100.02,2400.0,2400.0,2200.0,1100.0,0,0,0,1,0,0,0,18,Road Facing Homes
5,ankit parisar nayapura,kolar road,House,75.0,112.48800,4687,1.0,East,4,6,2,1600.17,2400.0,2400.0,NaN,1600.0,1,0,1,1,0,0,1,37,Road Facing Homes
10,chitrance sai vihar,outside bhopal,House,80.0,126.30000,4210,2.0,North,3,3,2,1900.24,3000.0,3000.0,2200.0,1900.0,0,0,0,0,0,0,0,17,Green View Homes
11,aakriti aqua city,hoshangabad road,House,36.9,63.25200,5271,1.0,NaN,3,3,1,700.06,1200.0,1200.0,NaN,700.0,0,0,0,0,0,0,1,9,Green View Homes
16,agrawal sagar lakeview homes,ayodhya bypass,Flat,69.0,74.99924,4162,3.0,NaN,3,3,3,1657.86,1802.0,NaN,NaN,1802.0,0,0,1,0,0,0,0,117,Amenity Facing Homes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1549,chunabhatti,chuna bhatti,House,150.0,270.00000,10000,2.0,East,4,4,2,1500.00,2700.0,2700.0,NaN,1500.0,1,0,0,1,1,0,1,22,Green View Homes
1570,comfort green airport road,gandhinagar,House,95.0,180.94000,9047,2.0,North-East,4,3,1,1050.07,2000.0,2000.0,NaN,1050.0,0,0,0,1,0,0,1,14,Green View Homes
1572,priyadarshini pristine,salaiya,House,55.0,91.52706,6547,1.0,West,3,3,2,840.08,1398.0,1398.0,NaN,840.0,1,1,1,1,0,0,2,146,Amenity Facing Homes
1577,agrawal sagar pearl,hoshangabad road,House,155.0,253.62000,14090,2.0,East,4,4,2,1100.07,1800.0,1800.0,NaN,1100.0,0,0,0,0,0,0,2,4,Amenity Facing Homes
1578,ruchi lifescape,misrod,House,100.0,233.10400,6856,2.0,North-East,5,6,3,1458.58,3400.0,3400.0,NaN,1459.0,0,0,0,0,0,0,1,22,Amenity Facing Homes

In [50]:
df.head()

,society,colony,property_type,price_outer,price,price_per_sqft,Total Floors,Facing,bedrooms,bathrooms,balconies,area,mainarea,built_up_area,carpet_area,effective_area_sqft,study room,servant room,store room,pooja room,others,view floor plan,furnishing_type,luxury_score,Overlooking_Categories
0,sage suncity,bhopal,House,105.0,105.00000,3750,1.0,NaN,7,5,0,2800.00,2800.0,2800.0,NaN,NaN,0,0,0,0,0,0,1,71,Green View Homes
1,danish hills view,kolar road,Flat,85.0,84.99448,6508,2.0,North,3,3,1,1306.08,1306.0,NaN,1306.0,NaN,0,0,0,1,0,1,1,35,Green View Homes
2,narmada prem kesar,katara hills,Flat,25.0,18.47050,2173,3.0,West,2,2,3,1150.48,850.0,NaN,850.0,1150.0,0,0,0,0,0,0,1,15,Green View Homes
3,gurunanak pura independent house,aishbagh,House,65.0,141.81600,5909,2.0,West,8,5,1,1100.02,2400.0,2400.0,2200.0,1100.0,0,0,0,1,0,0,0,18,Road Facing Homes
4,chuna bhatti,chuna bhatti,House,650.0,650.00000,16250,3.0,NaN,6,6,2,4000.00,4000.0,NaN,NaN,4000.0,1,1,1,1,0,0,2,10,Road Facing Homes

In [54]:
df['price'] = round(df['price'],2)

In [55]:
df.head()

,society,colony,property_type,price_outer,price,price_per_sqft,Total Floors,Facing,bedrooms,bathrooms,balconies,area,mainarea,built_up_area,carpet_area,effective_area_sqft,study room,servant room,store room,pooja room,others,view floor plan,furnishing_type,luxury_score,Overlooking_Categories
0,sage suncity,bhopal,House,105.0,105.00,3750,1.0,NaN,7,5,0,2800.00,2800.0,2800.0,NaN,NaN,0,0,0,0,0,0,1,71,Green View Homes
1,danish hills view,kolar road,Flat,85.0,84.99,6508,2.0,North,3,3,1,1306.08,1306.0,NaN,1306.0,NaN,0,0,0,1,0,1,1,35,Green View Homes
2,narmada prem kesar,katara hills,Flat,25.0,18.47,2173,3.0,West,2,2,3,1150.48,850.0,NaN,850.0,1150.0,0,0,0,0,0,0,1,15,Green View Homes
3,gurunanak pura independent house,aishbagh,House,65.0,141.82,5909,2.0,West,8,5,1,1100.02,2400.0,2400.0,2200.0,1100.0,0,0,0,1,0,0,0,18,Road Facing Homes
4,chuna bhatti,chuna bhatti,House,650.0,650.00,16250,3.0,NaN,6,6,2,4000.00,4000.0,NaN,NaN,4000.0,1,1,1,1,0,0,2,10,Road Facing Homes

In [56]:
df.drop(columns=['price_outer','area','built_up_area','carpet_area','effective_area_sqft'],inplace=True)

In [57]:
df.head(1)

,society,colony,property_type,price,price_per_sqft,Total Floors,Facing,bedrooms,bathrooms,balconies,mainarea,study room,servant room,store room,pooja room,others,view floor plan,furnishing_type,luxury_score,Overlooking_Categories
0,sage suncity,bhopal,House,105.0,3750,1.0,NaN,7,5,0,2800.0,0,0,0,0,0,0,1,71,Green View Homes

In [58]:
df.to_csv('BPL_cleaned_l3_v2.csv',index=False)