In [1]:
import pandas as pd 
import numpy as np

In [3]:
houses = pd.read_csv('bpl_house_cleaned_l1.csv')
flats = pd.read_csv('bpl_flats_cleaned_l1.csv')

In [4]:
houses.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 798 entries, 0 to 797
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pname            798 non-null    object
 1   society          797 non-null    object
 2   price_outer      798 non-null    float64
 3   price_per_sqft   798 non-null    int64
 4   possesion        798 non-null    object
 5   description      798 non-null    object
 6   Area             798 non-null    object
 7   Total Floors     764 non-null    float64
 8   Facing           485 non-null    object
 9   Property Age     715 non-null    object
 10  furnishing       302 non-null    object
 11  features         447 non-null    object
 12  Overlooking      378 non-null    object
 13  bedrooms         798 non-null    int64
 14  bathrooms        798 non-null    int64
 15  balconies        798 non-null    int64
 16  additional_room  798 non-null    object
 17  area             798 non-null    float64
dtypes: float64(3), int64(4), object(11)
memory usage: 112.3+ KB

In [6]:
flats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 782 entries, 0 to 781
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pname            782 non-null    object
 1   society          779 non-null    object
 2   price_outer      782 non-null    float64
 3   price_per_sqft   782 non-null    int64
 4   possesion        782 non-null    object
 5   description      782 non-null    object
 6   Area             782 non-null    object
 7   Floor Number     782 non-null    object
 8   Facing           391 non-null    object
 9   Property Age     728 non-null    object
 10  furnishing       371 non-null    object
 11  features         568 non-null    object
 12  Overlooking      414 non-null    object
 13  bedrooms         782 non-null    int64
 14  bathrooms        782 non-null    int64
 15  balconies        782 non-null    int64
 16  additional_room  782 non-null    object
 17  Floor_On         782 non-null    int64
 18  Total_Floors     782 non-null    int64
 19  area             782 non-null    float64
dtypes: float64(2), int64(6), object(12)
memory usage: 122.3+ KB

In [8]:
flats.rename(columns={'Floor Number':'Total Floors'},inplace=True)

In [9]:
flats['Total Floors'] = flats['Floor_On']

In [13]:
flats.head(2)

,pname,society,price_outer,price_per_sqft,possesion,description,Area,Total Floors,Facing,Property Age,furnishing,features,Overlooking,bedrooms,bathrooms,balconies,additional_room,area
0,"3 BHK Flat in Shahpura, Bhopal",green heights,75.0,6000,Ready To Move,"Situated in shahpura, bhopal, green heights is...",Carpet area: 1250\n(116.13 sq.m.) \nsq.ft.,1,East,5 to 10 Year Old,"['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '3 Ge...","['Feng Shui / Vaastu Compliant', 'Security / F...",NaN,3,3,2,Not Available,1250.0
1,"3 BHK Flat in MP Nagar, Bhopal",keelandev apartments,185.0,10481,Ready To Move,For sale 3.5 bhk flat kilandev tower shivaji n...,Super Built up area 1765\n(163.97 sq.m.) \nsq...,5,North-West,1 to 5 Year Old,"['2 Wardrobe', '3 Fan', '1 Exhaust Fan', '2 Ge...","['Intercom Facility', 'Lift(s)', 'Maintenance ...",Main Road,3,3,2,servant room,1765.1

In [12]:
flats.drop(columns=['Floor_On','Total_Floors'],inplace=True)

In [14]:
flats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 782 entries, 0 to 781
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pname            782 non-null    object
 1   society          779 non-null    object
 2   price_outer      782 non-null    float64
 3   price_per_sqft   782 non-null    int64
 4   possesion        782 non-null    object
 5   description      782 non-null    object
 6   Area             782 non-null    object
 7   Total Floors     782 non-null    int64
 8   Facing           391 non-null    object
 9   Property Age     728 non-null    object
 10  furnishing       371 non-null    object
 11  features         568 non-null    object
 12  Overlooking      414 non-null    object
 13  bedrooms         782 non-null    int64
 14  bathrooms        782 non-null    int64
 15  balconies        782 non-null    int64
 16  additional_room  782 non-null    object
 17  area             782 non-null    float64
dtypes: float64(2), int64(5), object(11)
memory usage: 110.1+ KB

In [15]:
flats.insert(2,'property_type','Flat')

In [16]:
houses.insert(2,'property_type','House')

In [17]:
flats.head(2)

,pname,society,property_type,price_outer,price_per_sqft,possesion,description,Area,Total Floors,Facing,Property Age,furnishing,features,Overlooking,bedrooms,bathrooms,balconies,additional_room,area
0,"3 BHK Flat in Shahpura, Bhopal",green heights,Flat,75.0,6000,Ready To Move,"Situated in shahpura, bhopal, green heights is...",Carpet area: 1250\n(116.13 sq.m.) \nsq.ft.,1,East,5 to 10 Year Old,"['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '3 Ge...","['Feng Shui / Vaastu Compliant', 'Security / F...",NaN,3,3,2,Not Available,1250.0
1,"3 BHK Flat in MP Nagar, Bhopal",keelandev apartments,Flat,185.0,10481,Ready To Move,For sale 3.5 bhk flat kilandev tower shivaji n...,Super Built up area 1765\n(163.97 sq.m.) \nsq...,5,North-West,1 to 5 Year Old,"['2 Wardrobe', '3 Fan', '1 Exhaust Fan', '2 Ge...","['Intercom Facility', 'Lift(s)', 'Maintenance ...",Main Road,3,3,2,servant room,1765.1

In [18]:
houses.head(2)

,pname,society,property_type,price_outer,price_per_sqft,possesion,description,Area,Total Floors,Facing,Property Age,furnishing,features,Overlooking,bedrooms,bathrooms,balconies,additional_room,area
0,"3 Bedroom House for sale in Kolar Road, Bhopal",ultimate english villa,House,60.0,8534,Ready To Move,Na....................................,Plot area 703\n(65.31 sq.m.) \nsq.ft.,2.0,West,5 to 10 Year Old,"['2 Wardrobe', '1 Light', '1 Modular Kitchen',...","['Maintenance Staff', 'Water Storage', 'Park',...",NaN,3,3,1,Not Available,703.07
1,"4 Bedroom House for sale in Lalghati, Bhopal",globus greens,House,225.0,15000,Ready To Move,It's very spacious bunglow ..It's prime locati...,Plot area 1500\n(139.35 sq.m.)\nBuilt Up area:...,2.0,West,5 to 10 Year Old,"['4 Bed', '8 Wardrobe', '6 Fan', '1 Sofa', '1 ...","['Private Garden / Terrace', 'Park', 'Visitor ...","Park/Garden,Club",4,3,1,pooja room,1500.00

In [19]:
df = pd.concat([flats,houses],ignore_index=True)

In [20]:
df.shape

(1580, 19)

In [22]:
df.sample(5)

,pname,society,property_type,price_outer,price_per_sqft,possesion,description,Area,Total Floors,Facing,Property Age,furnishing,features,Overlooking,bedrooms,bathrooms,balconies,additional_room,area
102,"4 BHK Flat in Misrod, Bhopal",globus coral woods,Flat,93.00,4823,Ready To Move,Globus coral woods is one of the most popular ...,Super Built up area 1928\n(179.12 sq.m.) \nsq...,6.0,NaN,5 to 10 Year Old View Construction Status,"['1 Water Purifier', '4 Fan', '1 Fridge', '1 E...","['Power Back-up', 'Feng Shui / Vaastu Complian...",Pool,4,3,2,Not Available,1928.26
1364,"2 Bedroom House for sale in Krishna Nagar, Bhopal",krishna nagar,House,6.25,1388,Ready To Move,"House for sale near by polytechnic square, ttt...",Plot area 450\n(41.81 sq.m.) \nsq.ft.,1.0,East,10+ Year Old,NaN,"['Water Storage', 'Park']",Others,2,2,1,Not Available,450.29
352,"2 BHK Flat in Misrod, Bhopal",aryan heights,Flat,25.00,3571,Ready To Move,Property description:- Property services want ...,Super Built up area 700\n(65.03 sq.m.) \nsq.ft.,3.0,North,5 to 10 Year Old,NaN,"['Feng Shui / Vaastu Compliant', 'Lift(s)', 'W...",Park/Garden,2,2,2,Not Available,700.08
532,"1 BHK Flat in Ayodhya Bypass , Bhopal",paras heights,Flat,14.00,3111,Ready To Move,Mujhe flate sell karna hi jisme sabhi subhidha...,Carpet area: 450\n(41.81 sq.m.) \nsq.ft.,3.0,North-East,1 to 5 Year Old View Construction Status,NaN,"['Security / Fire Alarm', 'Lift(s)', 'Maintena...","Park/Garden,Main Road",1,1,1,others,450.02
1018,"5 Bedroom House for sale in Basant Kunj, Bhopal",basant kunj,House,275.00,12222,Ready To Move,Planning to buy an individual house in bhopal....,Plot area 2250\n(209.03 sq.m.)\nBuilt Up area:...,2.0,North,5 to 10 Year Old,"['1 Wardrobe', '1 Fan', '1 Light', '1 Modular ...",NaN,Park/Garden,5,5,3,Not Available,2250.04

In [23]:
df = df.sample(df.shape[0],ignore_index=True)

In [24]:
df.to_csv('BPL_merged_cleaned_l2.csv',index=False)